### ISSUE TITLE
[Bug] Adding More Link values later breaks link formatting

### ISSUE THREAD

**Issue by SlRvb** [mdelobelle/metadatamenu#1]
Adding more link values from a multiselect to a field that already has links in it breaks some of the existing links in that field.

# Example

Field with links:
```js
Category:: [[Cat-Uni - Alternate Universe|Alternate Universe]], [[Cat-Uni - College|College]], [[Cat-Uni - Zombie Apocalypse|Zombie Apocalypse]], [[Cat-Uni - Fantasy|Fantasy]], [[Cat-Uni - Slice Of Life|Slice Of Life]]
```

Result when adding more to this field using the modal:
```js
Category:: [Cat-Uni - Alternate Universe|Alternate Universe]], [[Cat-Uni - College|College]], [[Cat-Uni - Zombie Apocalypse|Zombie Apocalypse]], [[Cat-Uni - Fantasy|Fantasy]], [[Cat-Uni - Slice Of Life|Slice Of Life], [[Cat-Uni - Medical|Medical]], [[Cat-Uni - Time Travel|Time Travel]], [[Cat-Uni - Action|Action]]
```

`Alternate Universe` link is missing the first opening bracket and `Slice of Life` link is missing the last closing bracket.

---
![Obsidian_FiN9rguixQ](https://user-images.githubusercontent.com/54087190/176673640-00120e82-75a8-403b-8a85-6a11c157796b.gif)

**Comment by mdelobelle** [comment]
thanks for pointing this out.
0.0.2 should fix this
