### ISSUE TITLE
[BUG] Inline formated dataview fields are not shown

### ISSUE THREAD

**Issue by AtlcatlQ** [mdelobelle/metadatamenu#10]
All the fields that are in *italics*, **bold**, or dataview styled ([key:: Value]) are not shown, Idk if works for the strike-through fields, but for the `code` formated fields works well.

**Comment by zackdn** [comment]
Adding my experience here, too. I want to use DataView fields in my notes and have their values autocompleted. However, autocomplete does not work if you include the brackets.

**This works:**
![SNAG-0029](https://user-images.githubusercontent.com/13019690/180470771-32cb2620-b847-45a8-8b66-bdf9d5ca8ff1.jpg)

**This does not:**
![SNAG-0030](https://user-images.githubusercontent.com/13019690/180470792-2584614a-e8de-4c25-b0e0-eec4c4d24afc.jpg)

**Here is the field as defined in my fileClass file:**
![SNAG-0031](https://user-images.githubusercontent.com/13019690/180470897-ac7c352a-7d30-42d7-aa40-4cfe9610aae2.jpg)

**Comment by AtlcatlQ** [comment]
I just found out that i need to put `:: {}` (Like: ``) after all the fields in the fileClass that I want to make available, which is a difference from Supercharged Plugin. I'll close this.

Thank you for the Plugin, btw.

**Comment by zackdn** [comment]
@AtlcatlQ can you give an example? I still can’t figure this out.

**Comment by AtlcatlQ** [comment]
All of the fields to be displayed, need be written like `field:: {}` (Accept any value). What was my big problem was i think it didn't recognize *italics* and **bold**. Making tests I just found out that the dataview styled fields still aren't getting displayed, tough. But the auto completion works well for the other formats if you doesn't have anything more in the same line.

But that exceeds this issue, if you agree I can open another about this (Similar behavior had the functionality when it was in the Supercharged links plugin)

```Markdown
field:: Works

- field2:: doesn't work

[field3:: Doesn't work either]

*field4*:: But this works
```

**Comment by zackdn** [comment]
Ahh, ok got it. Yeah, if you open the feature request that would be great! Thanks!
