### ISSUE TITLE
[FR]:  DVJS builder UI

### ISSUE THREAD

**Issue by thecookiemomma** [mdelobelle/metadatamenu#100]
I use this plugin in its basic form to limit one or two fields.  I'd like to use more of the features, but I don't know JS very well, and I could learn, but it might take a while. I was wondering if it might be possible to set up a "builder" for the DVJS tables that would set up the ability to use MM  in them, much like the field builder you already have in place.
Thanks again for a neat plugin.

**Comment by mdelobelle** [comment]
Thank you for your feedback.

I get your point and having features to ease the building of dataviewJS queries is a need that many have, but not only for this plugin. Therefore I won't consider include that in Metadata Menu plugin for the moment

You can check https://s-blu.github.io/obsidian_dataview_example_vault/ for great resources on how to build a dvjs query

And there's an early stage app to build dv queries with a simple UI. It's not building DvJS queries at the moment but i think it will evolve over time.
https://s-blu.github.io/basic-dataview-query-builder/question/3

BTW learning how to build DVJS queries do take some time indeed, but it's a good introduction to javascript and it's worth the try

Good luck!
