### ISSUE TITLE
FR: Display Field Names in popup menu

### ISSUE THREAD

**Issue by brimwats** [mdelobelle/metadatamenu#104]
I went to update ProjectStatus in a note.

I made sure it was added
![image](https://user-images.githubusercontent.com/73113656/191980506-c73436e6-853b-4a57-bb83-216c78e9c81d.png)

and in settings
![image](https://user-images.githubusercontent.com/73113656/191979915-9032c87f-c7a1-4961-8b5e-55506fd22187.png)

use the hotkey
![image](https://user-images.githubusercontent.com/73113656/191979880-b98298d8-f032-4824-980f-078bb0d55366.png)

but only `null` shows up

![image](https://user-images.githubusercontent.com/73113656/191979968-d13f1559-1265-43be-b2d1-fbde59186f1d.png)

even when the note has null in it the next value does not appear
![image](https://user-images.githubusercontent.com/73113656/191980035-b8a3ef4e-9e99-4f55-999f-43dc40fd6a82.png)

its in the note too:
![image](https://user-images.githubusercontent.com/73113656/191980550-69d43075-e82a-4243-8284-cb66692b6d6a.png)

**Comment by mdelobelle** [comment]
Hi can you remove the value in "path of the note containing values" and see if it fixes your problem?
This option (path of the note containing values) is made for buidling a simple list of values instead of defining values one by one. It seems that you have used it to define the path to your fileClass note

**Comment by brimwats** [comment]
that worked! I would recommend updating that description or perhaps putting it under a fold? it's not clear what it does now. but thankks for the help :)

**Comment by zcysxy** [comment]
This feature seems to be broken in the latest version 🤔

**Comment by zcysxy** [comment]
> This feature seems to be broken in the latest version 🤔

Fixed in version 0.2.2 :rocket::heart:
