### ISSUE TITLE
broken link on https://mdelobelle.github.io/metadatamenu/ website

### ISSUE THREAD

**Issue by l-x-u** [mdelobelle/metadatamenu#105]
just a heads up that the GitHub link with the icon in the top right of the https://mdelobelle.github.io/metadatamenu/ website links to https://github.com/mdelobelle/metadata-menu - which leads to a 404, since this repo is https://github.com/mdelobelle/metadatamenu (without a dash between 'metadata' and 'menu').

**Comment by mdelobelle** [comment]
Thank you! I was wondering why the github stats weren't showing-up 😅
Fixed
