### ISSUE TITLE
No calendar after latest update

### ISSUE THREAD

**Issue by Asetnozama** [mdelobelle/metadatamenu#107]
After the latest update there's no calendar anymore on Windows and ios after selecting the "date" frontmatter

It only says: change value for <date>

Oh, I see it's also not possible anymore for the "multi" field setting
Here it also just displays: change value for <Tags>

I checked: it works fine until version 01.40

cheers

**Comment by mdelobelle** [comment]
I can't reproduce this.
What is your version of obsidian?
Do you see any error message in the console on windows (ctrl + shift + i)?

**Comment by Asetnozama** [comment]
Obsidian version: 0.15.9
No error messages in the console
before update:
![before update](https://user-images.githubusercontent.com/102867794/192109129-f196c4d0-747a-486c-9a7b-113379a996d6.jpg)
after update:
![after update](https://user-images.githubusercontent.com/102867794/192109140-047c4bf9-ae94-4ab4-b288-421b74fa6093.jpg)

**Comment by mdelobelle** [comment]
It looks like it is not recognized anymore as a `Date` field so the input falls back to a default `Input` field.

Could you paste your settings?

Could you also try the command from command Palette `Metadata Menu: Update lookup fields` (maybe it's a cache issue)?

**Comment by Asetnozama** [comment]
Update lookup fields didn't cha
![settings](https://user-images.githubusercontent.com/102867794/192111452-80949a60-f751-4d81-8e65-f7b4c8fe68e6.jpg)
nge the issue

**Comment by corinnekaryiu** [comment]
Hi, I've been having the same issue since the latest update.

Here are some examples that are showing as a standard input field instead of the preset field:

![Screenshot 2022-09-25 at 13 54 16](https://user-images.githubusercontent.com/100031232/192144497-9f9f94be-7da4-40ab-a605-ac08b21d5ceb.png)

Please let me know if any other information will help!

**Comment by mdelobelle** [comment]
Hi! your settings look ok. This may be an issue with the plugin indexing (new process that has been included in this version)
Here is a couple of thing I would like you to try:
- disable/enable the plugin (don't delete it to avoid loosing your settings) - check if that solves the problem, if not try the next idea
- delete one of the preset date field and create it again - check if that solves the problem, if not try the next idea
- create a new date preset field and see if it has the correct behaviour

**Comment by corinnekaryiu** [comment]
@mdelobelle I've tried all 3 options above and sadly none of them made any difference.

I am getting this error in the console, but I'm not sure that it's related, as I don't currently use the fileClass feature:

![Screenshot 2022-09-25 at 20 35 33](https://user-images.githubusercontent.com/100031232/192161954-d2393a16-0f2a-4a50-b29f-e0be8f02247c.png)

**Comment by mdelobelle** [comment]
This could be the reason.
Could you search your vault for a note or more containing the fileClass keyword?

this could be done with a dataview query like

```dataview
table where fileClass != null
```

if there are any, could you remove those lines with the fileClass field and see if the error goes away?

**Comment by corinnekaryiu** [comment]
Hmm, I'm not using fileClass at all and there isn't any reference to it anywhere in my vault 🤔 I used your DV query above, searched Obsidian and also searched via VS Code to be sure, and nothing. How confusing!

![Screenshot 2022-09-25 at 21 34 09](https://user-images.githubusercontent.com/100031232/192164397-aabb6e8d-5b72-40fe-b6a5-17a86c3d84eb.png)

![Screenshot 2022-09-25 at 21 38 57](https://user-images.githubusercontent.com/100031232/192164582-8d5d704f-aa0a-41e8-8f70-b27bee07ab97.png)

![Screenshot 2022-09-25 at 21 36 03](https://user-images.githubusercontent.com/100031232/192164456-8e9c774d-c67e-42b2-a5b4-72a52fc61ebb.png)

**Comment by corinnekaryiu** [comment]
@mdelobelle By the way, whatever it is you've changed in the release that went out as I was typing my reply has fixed this. Thank you! 🙌🏻

**Comment by mdelobelle** [comment]
glad to hear that! I've indeed found that I've forgotten a use case when people don't use fileClasses.
Nevertheless your `fileClass: Work` error log is strange... It may imply that you have a note with this line somewhere ... I agree this is confusing
