### ISSUE TITLE
[FR] DB Folder integration

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#108]
Would it be possible to integrate with db folder? To use metadata menu as the engine/filter for data entry?

**Comment by mdelobelle** [comment]
I'm not familiar with db folder.
Will try it and see how this could look like.

**Comment by mdelobelle** [comment]
After diving a bit into db folder, I think that the question is more for them. They could use the metadata menu api to get field definitions and updating capabilities.
There's no delegation protocol proposed by db folder to plug a different field validation engine for the moment.
Maybe you could open an issue in their repo
