### ISSUE TITLE
Feature: allow context menu to open in all contexts

### ISSUE THREAD

**Issue by pjeby** [mdelobelle/metadatamenu#11]
Currently, you can't access the functionality from a wide variety of plugins' file menus, including Kanban, Longform, Recent Files, and Quick Explorer,  not to mention built-in plugins like search and backlinks.

Rather than using an allow-list of specific contexts to enable the menu, perhaps it would be better to use a block-list of contexts to *not* enable it in?

**Comment by mdelobelle** [comment]
You're right, that was a very old check to ensure no conflict with other plugins. I assume that I can remove it since the "displayFieldsInContextMenu" setting can be toggled in case of a conflict.
Will do in next release
