### ISSUE TITLE
Loading plugin prevents loading of all other plugins

### ISSUE THREAD

**Issue by idanariav** [mdelobelle/metadatamenu#111]
When I open Obsidian (desktop version - 15.9) with Metadatamenu enabled, the program freezes, it doesn't load any other plugin, and the console is empty. once I cancel it, all other plugins load and messages appear.
similarly, enabling the plugin manually after all other plugins have loaded works successfully (i.e. it is disabled at startup, and then manually enable it through the settings).

**Comment by mdelobelle** [comment]
Do you use "lookup" fields in your vault?
If so, I've published a new version that improves the performance of field indexing when opening a vault with such fields 

Could update your plugin to 0.2.4 and check if that improves the situation?

**Comment by idanariav** [comment]
It seems that updating the plugin to 0.2.4 solved the situation. Thank you very much!
