### ISSUE TITLE
[FR] Grab field values from dataview query

### ISSUE THREAD

**Issue by cogscides** [mdelobelle/metadatamenu#112]
Similar to what you make for assigning fileClass based on dataview query, but for collecting all values to quickly insert them in the field instead of manually entering.
Maybe in the fileClass note something like this:

```
personClass.md
===
profession:: { "type": "dataview", "options: "dv.pages("#person").where(p.profession)"}
```

**Comment by mdelobelle** [comment]
good idea, I think this is more or less the same request as #110  ?

**Comment by cogscides** [comment]
@mdelobelle some kind of yeah. In my case areas are the tags. I saw that folk on [Better Inline Fields](https://github.com/dsarman/better-inline-fields) plugin working on a similar way to grab values from other inline fields. Would be good to have ways to manage them without manually entering them in the fileClass object.

**Comment by mdelobelle** [comment]
ok got it, it's not the same idea indeed.

I guess I could add an option to "Select" and "Multi Select" fields settings where the user can create a dataview request that returns a list of string to would populate the select options

in your example the setting would look like

```
personClass.md
===
profession:: { "type": "Select", "optionsFromDVQuery": "dv.pages("#person").where(p => p.profession !== undefined).map(p => p.profession.toString())"}
```

even more sophisticated thing would be feasible, such as removing duplicates:

```
personClass.md
===
profession:: { "type": "Select", "optionsFromDVQuery": "[...new Set(dv.pages("#person").where(p => p.profession !== undefined).map(p => p.profession.toString()).sort()]"}
```

It's for advance usage but yeah, I think this would be usefull

Am I understanding correctly what you have in mind?

**Comment by cogscides** [comment]
Yeah, that is absolutely right what I imagined! 😍

**Comment by mdelobelle** [comment]
Hi this is now available in 0.2.9. I hope it will suit your need

**Comment by cogscides** [comment]
@mdelobelle omg, you are magician! Is it possible to use dataview query from class file? Or only via the settings?

**Comment by mdelobelle** [comment]
thanks. yes it is
