### ISSUE TITLE
Bug: Changing value of key, which partially has same name as other keys, also changes other keys

### ISSUE THREAD

**Issue by Pachtjuilaard** [mdelobelle/metadatamenu#115]
I have three keys in my frontmatter:
class: 
subclass: 
cssclass: 

And I've set up Metadata Menu to change the "class" key. When I do so, picking a link from a dv.pages query, all keys with "class" in them also change. For example:
class: [[Monk]]
subclass: [[Way of Shadow]]
cssclass: dv

turns into the following when I change the class:
class: [[Cleric]]
class: [[Cleric]]
class: [[Cleric]]

**Comment by mdelobelle** [comment]
good catch! I will fix it in the next release
