### ISSUE TITLE
Global fields don't populate in flie class files

### ISSUE THREAD

**Issue by thecookiemomma** [mdelobelle/metadatamenu#117]
### Current Behavior: 
File which has a File Class does not pull up the Global field.  For example, defined a global field called "Watched" with a template.  It's not available in the list, nor is it available to add.  

### Expected behavior:
If a field is global, then it ought to be global even if it isn't in the file class.  

### System
Windows 10 
Insider build 0.16.4
MM version:  0.27

I'm enjoying this plugin, even without all the features (because I'm a dork and am attempting to learn dvjs)

**Comment by mdelobelle** [comment]
The way to achieve what you want is to move your global fields into a fileClass note (let's say global.md)
Then set this path in the settings in the "global fileClass" field.

Now your fields defined in this fileClass note are available everywhere even if there is no fileClass attribute defined in your frontmatter

By default a note with a fileClass defined only accepts fields defined in the fileClass. It wont accept fields neither defined in the plugin settings nor in the global fileClass, unless you tell it to do so:

If you want those global fields to be available in a note that has a fileClass attribute defined - let's say "movie" - then in the movie.md frontmatter you can set the attribute "extends" to "global". And voila, your note will accept both the fields define d in the global fileClass AND in the movie fileClass.
NB if those two fileClass share some fieldNames, the one defined in the "child" fileClass (here movie") will have the priority
