### ISSUE TITLE
Bug: Date fields with empty values throwing errors

### ISSUE THREAD

**Issue by frankreporting** [mdelobelle/metadatamenu#119]
Hi! I think there may be a bug in the API. Everything ultimately works as expected, but I noticed a lag when I created a dataview query that also called the metadata menu API. The console revealed a hint:

```
plugin:metadata-menu:7544 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'path')
    at DateField.validateValue (plugin:metadata-menu:7544:56)
    at FieldInfo.setInfos (plugin:metadata-menu:8909:37)
    at eval (plugin:metadata-menu:8984:27)
    at Generator.next (<anonymous>)
    at eval (plugin:metadata-menu:72:61)
    at new Promise (<anonymous>)
    at __async (plugin:metadata-menu:56:10)
    at eval (plugin:metadata-menu:8979:44)
    at Array.forEach (<anonymous>)
    at fileFields (plugin:metadata-menu:8979:27)
```

I have a "completed" date field on files tagged #task that I'm querying, but it's expected to be empty whenever it's a task I'm still working on. This date field is set up as a link to a daily note file in format `[[2022-10-07]]`. I'm trying to use a custom script calling Metadata Menu's API in order to update that field programmatically, but it's throwing the above error every time the file renders and the referenced "completed" field is empty.

This is the line of code that seems to be generating the error:

```
await mm.fileFields(page.file.path)
```

If I put a proper value in "completed," the error doesn't appear. Is it possible Metadata Menu isn't set up to handle empty fields? Is there some other way I can handle empty fields gracefully?

Expected behavior might be that when it sees a date field set up to accept daily note file links, and it sees an empty field, it does NOT attempt to traverse the file path. But maybe I'm misunderstanding the error. If so, any guidance appreciated!

**Comment by mdelobelle** [comment]
good catch! this is fixed in 0.2.10: empty date field are considered as valid now
