### ISSUE TITLE
Quotation marks

### ISSUE THREAD

**Issue by dxcore35** [mdelobelle/metadatamenu#120]
Please for the sanity of all of us allow all these quotation marks

-”
-"
-'

I spend lot of time checking why my definition of class is not working! The problem was I'm using different quotation marks...

**Comment by mdelobelle** [comment]
JSON.parse only accept double quotes ". So only those character can be used for class field definition. I'll add that in the documentation

**Comment by dxcore35** [comment]
What is the difference between (”) and (") ?

**Comment by dxcore35** [comment]
In dataview you can use any of these. Why you just not add cleanup function to replace quotation marks to correct JSON format?
