### ISSUE TITLE
Dataview queries not working

### ISSUE THREAD

**Issue by dxcore35** [mdelobelle/metadatamenu#121]
# Settings

![Screen Shot 2022-10-11 at 15 38 27](https://user-images.githubusercontent.com/7279156/195092777-b63e2a3f-7b04-4292-a7a7-f1213c31e487.jpg)
![Screen Shot 2022-10-11 at 15 38 21](https://user-images.githubusercontent.com/7279156/195092788-135a6fff-f1a7-4b68-aca5-bdda6c2ae610.jpg)

# Outputs

![Screen Shot 2022-10-11 at 15 40 06](https://user-images.githubusercontent.com/7279156/195093072-c69d06a9-5de0-46ea-9335-8607079472d8.jpg)

# Output via dataview
![Screen Shot 2022-10-11 at 15 19 43](https://user-images.githubusercontent.com/7279156/195093140-836f981c-3909-409e-84cc-a0d25a6d437d.jpg)

**Comment by mdelobelle** [comment]
none of this options work?
- right click on the line and select "update test" option
- click on the notés context menu and select "update test" option
- open command palette > choose "metadata menu: field options"> select "update test" option
