### ISSUE TITLE
Scroll bar not appearing

### ISSUE THREAD

**Issue by yurijserrano** [mdelobelle/metadatamenu#127]
After a certain number of values it impossible to interact with the UI as can be seen in the screenshot right below:

![scroll not appearing](https://user-images.githubusercontent.com/14169134/196521571-0b7ddead-4b1b-49e1-959e-0dafbc99bbad.png)

I've fixed this by changing the property overflow from the modal class from hidden to auto, as can be seen in the image right below:

![image](https://user-images.githubusercontent.com/14169134/196534776-aee15977-f20a-41d6-a257-4ec47e739c61.png)

However, some users cannot have some coding background, so here I am including the solution to give a glimpse for the developer to address this problem natively.

If you need any further clarifications, just let me know.

Have a great day ahead.

**Comment by AtlcatlQ** [comment]
try doing it as a pull request

**Comment by mdelobelle** [comment]
fixed in 0.3
