### ISSUE TITLE
FR: Lookup for same field in multiple file types

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#128]
I have a `Days::` field on my Week and Month type files. Each DNP has a `Week::` and `Month::` field. I would like to do a lookup field for both but it seems right now I can only do one? I have many cases where I would like to do lookups for the same field on many different types of pages.

**Comment by mdelobelle** [comment]
You can only have one lookup field definition for a given field name if you define it in plugin's settings.

For your need, You'd have to create two different fileClasses:
- one for Week
- one for Month

in each of them you define a `Days` lookup field:

in the Week fileClass:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/1233240/196601408-7d9dc165-3af3-47e1-800a-d851789c2932.png">

in the Month fileClass:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/1233240/196602605-2724e5b3-e46c-4cbe-b90b-954523417e05.png">


And here's the result:
(left tab: my DNP, center tab: my WNP, right tab: my MNP)
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/1233240/196602455-d327a11d-97f8-42f7-836f-2973b681decb.png">

Is that what you are looking for?
