### ISSUE TITLE
FR: Perform calculation on other fields in current page

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#129]
Is it possible for me to populate a field using a calculation on other fields from the same page? Say I have the fields `Num1` and `Num2` and I would like `Num3` on the same page to auto populate with the sum of `Num1` and `Num2`. Can I do this?

**Comment by mdelobelle** [comment]
Not at the moment (expect in a very hacky way by using an intermediate note and lookup fields) but it is definitely something feasible.
I think I would create a new type of field, like `ComputedField` of something, that behaves like lookupField but only dealing with inner note's metadatas and computed whenever one note's metadata is changing.

I will dive into it in the next days.
