### ISSUE TITLE
Best way to consolidate fileClass and templates

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#133]
I'm trying to find the best way to efficiently set up my metadata. Right now it seems I'm doing a lot of redundant work. 

I have fileClass files that have my metadata fields and the type of file
I also have template files that include my metadata and the type of file in the form of a tag. 

How can I avoid duplicating this information every time? Can metadata menu utilize my templates somehow? Can metadata menu automatically apply its own templates to files?

**Comment by AtlcatlQ** [comment]
Have you consider using [Templater](https://github.com/SilentVoid13/Templater)?

with a "master template" and a little of javascript you could set conditional templates to activates in certain note types. (I also use it in tandem with QuickAdd)

**Comment by balola** [comment]
What if when you wrote fileClass in the frontmatter matedata area a script writes the fileClass predefined fields under the fileClass row.
Like:
---
fileClass:: People
// than here comes the predefined fields after the command run
ID::
Name::
Age::
etc

---

With it you could fill out the **skeleton of your data structure** and after fill out the params with autocomplete.
It is "like" Tana works but wo UI.

Füles

**Comment by balola** [comment]
Sorry, just one ":" needs.

fileClass: People
// than here comes the predefined fields after the command run
ID:
Name:
Age:

**Comment by arminta7** [comment]
> Have you consider using [Templater](https://github.com/SilentVoid13/Templater)?
> 
> with a "master template" and a little of javascript you could set conditional templates to activates in certain note types. (I also use it in tandem with QuickAdd)

I had thought of Templater, although I'm really not that familiar with it. I saw that you can have a template automatically applied to new files in a folder. I was going to use that with Auto Note Mover so if I tagged a note, it would be moved automatically to the right folder and the template applied, but only empty notes can have a template auto applied. If I could figure that out, especially if I can use inline tags as the fileClass, that would simplify things a lot.

**Comment by arminta7** [comment]
> ## What if when you wrote fileClass in the frontmatter matedata area a script writes the fileClass predefined fields under the fileClass row.
> Like:
> fileClass:: People // than here comes the predefined fields after the command run ID:: Name:: Age:: etc
> 
> With it you could fill out the **skeleton of your data structure** and after fill out the params with autocomplete. It is "like" Tana works but wo UI.
> 
> Füles

That would be great! Especially if you could substitute an inline tag for the fileClass.

**Comment by mdelobelle** [comment]
I think Supercharged tags and bulk insert missing fields pretty much cover this need right? should we close this one?
