### ISSUE TITLE
Global field and fileClass?

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#134]
If I choose to use a fileClass on a page, is there any way for me to use a globally defined field on that same page? I tried the preset fields and the global fileClass but neither work on a fileClass page.

**Comment by AtlcatlQ** [comment]
to use a global field in a page with another fileClass you need to inherit the global class in the class you want to use it. Simple add `extends: <global fileClass>` in the fileClass where you need that field.

**Comment by mdelobelle** [comment]
@arminta7 does it suit you?  an we close this one?

**Comment by arminta7** [comment]
Yes!
