### ISSUE TITLE
Small typo and visual bug

### ISSUE THREAD

**Issue by brimwats** [mdelobelle/metadatamenu#135]
hello!

in this menu:

![Screenshot_20221019_140933](https://user-images.githubusercontent.com/73113656/196804902-33210335-b6ca-4fd0-935a-dfebd528608b.jpg)

the typo is "this" which should be "these"

the visual bug is that boxes are not hilighted in Obsidian 1.0 themes (this one is minimal with gruvbox applied)

**Comment by mdelobelle** [comment]
thanks for pointing this out.
For the visual bug I've noticed that, but i don't know how to improved it.
In light mode I've changed "Light mode background contrast" to "Low contrast" but that's not a great workaround so far

**Comment by brimwats** [comment]
> thanks for pointing this out. For the visual bug I've noticed that, but i don't know how to improved it. In light mode I've changed "Light mode background contrast" to "Low contrast" but that's not a great workaround so far

it might be worth asking in #appearance or similar, they'd have good knowhow

here's another typo

![image](https://user-images.githubusercontent.com/73113656/197067282-b438175d-fd81-45f9-ac86-a45c3418b952.png)

"fielClass"
