### ISSUE TITLE
FR: Showing or hiding metadata fields based on certain criteria

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#139]
In Tana you are given the ability to specify when a field is shown to edit based on if it's empty, not empty, always, etc. 
<img width="375" alt="Screenshot 2022-10-21 at 17 45 40" src="https://user-images.githubusercontent.com/7927356/197293468-06ebfcfd-a24a-4ba7-9786-4c5107822941.png">

Then it looks like this when hidden:
<img width="478" alt="Screenshot 2022-10-21 at 17 46 23" src="https://user-images.githubusercontent.com/7927356/197293531-97e732c6-8dfd-4492-acd5-441e5919c581.png">

Might be out of the scope of this plugin but would be a really awesome feature!!

**Comment by mdelobelle** [comment]
I'm in the waiting list for a Tana account. Can't wait to get my hands on it :)
I'm working on a metadata form view to group all metadata fields and facilitate their update. this capability could be included in such a form (see #131 )

**Comment by mdelobelle** [comment]
now that Metadata Menu modal is in place, I could add options in the fileClass definition to hide some fields from the modal:
- hide : [fieldA, fieldB, ...]
- hideIfEmpty : [fieldC, fieldD, ...]
- hideIfNotEmpty : [fieldE, fieldF; ...]

WDYT?

**Comment by mdelobelle** [comment]
I think this is now covered with the blocks and table view :)
Don't hesitate to fill a new issue if you have specific needs on top of the current features
