### ISSUE TITLE
Metadata form

### ISSUE THREAD

**Issue by balola** [mdelobelle/metadatamenu#143]
Hi,
First of all it is a great work and I am happy you work on it.
But one problem I met:
Some fields (Boolean in my case) don't appear on the form.
When first tried I could find them in some cases but now.
Or if it is because of unchecked or unsigned fields, we need all to see and choose by one click.
The concept is good.

![image](https://user-images.githubusercontent.com/24825268/198569722-0695cd40-f39a-4327-b5c9-0c53ad80385c.png)

The video is great on 0.3. It is a good source to learn the new features.

Füles

**Comment by mdelobelle** [comment]
good catch: the plugin doesn't consider empty as false.
I will fix that in the next version

**Comment by mdelobelle** [comment]
solved in 0.3.3
