### ISSUE TITLE
Metadata bulk insert fields

### ISSUE THREAD

**Issue by mdelobelle** [mdelobelle/metadatamenu#146]
single command to single shot write all fields defined in the schema

**Comment by mdelobelle** [comment]
shipped in v0.3.3

**Comment by kalmir** [comment]
It's amazing, exactly what I was looking for. Thx!

One question: is there a way to open this menu by a command? It doesn't look like it at the moment. I would like to set up a macro in which I locate a file and open its bulk insert field - at once.

**Comment by mdelobelle** [comment]
Hi thanks. Yes that's possible. Could you open a FR to keep track of this idea?

**Comment by kalmir** [comment]
On it!
