### ISSUE TITLE
Using date format “YYYY-MM-DD_ddd” with date picker always inserts “2022-09-22_Thu”

### ISSUE THREAD

**Issue by dancemonkey** [mdelobelle/metadatamenu#147]
The format YYYY-MM-DD_ddd is how I have my daily notes set up, but when I pick a new date using metadata menu (using any method) it will always select the date 2022-09-22_Thu. 

If I take the “_ddd” off the format and just use YYYY-MM-DD it works fine and I can select any date. 

Taking the underscore out of the formatting also seems to make it work fine, so the underscore may be the issue. 

Stepping the day forward works fine even if the format is not one the MM is able to set properly from a date picker.

**Comment by mdelobelle** [comment]
I can reproduce this. 
Do you have "natural-language" plugin installed?

**Comment by dancemonkey** [comment]
Yep, I can reproduce that as well. NLD @today returns the proper date in my daily notes format, but just like your example if I type it out fully (or try and use the MM picker) I get September 23. Wild, thank you for making that connection.

**Comment by mdelobelle** [comment]
Ok i'll close this one then an open an issue in their repo
