### ISSUE TITLE
Map with nested tag

### ISSUE THREAD

**Issue by kmaustral** [mdelobelle/metadatamenu#148]
Currently, the binding of metadata through tags in FileClass does not work for nested tags.

test.md
---
mapWithTag: true
---

This works for #test but not #test/complete. 

Thank you.

**Comment by mdelobelle** [comment]
good idea, I will include it in the next release

**Comment by mdelobelle** [comment]
shipped in v0.3.3

**Comment by AtlcatlQ** [comment]
How can I use the Nested Tags?
