### ISSUE TITLE
FR: Bulk insert fields action available via dedicated command

### ISSUE THREAD

**Issue by kalmir** [mdelobelle/metadatamenu#151]
Version 0.3.3 introduced a fantastic new feature, **bulk insert fields action**. 
As noted in release comments, this action could be called upon via note context menu or metadata menu button.

My feature request is:
### Create command for bulk insert fields action.

Commands in Obsidian are typically available:

- in Command Palette;
- via Hotkeys;
- via API (and then e.g. launched by URL through Advanced URI plugin).

I am not sure but I think once a command is assigned, all 3 options are immediately available.
If not, making all 3 triggers possible would be great.  

(I first introduced this idea in #146.)

**Comment by kalmir** [comment]
👏👏👏

**Comment by mdelobelle** [comment]
Shipped in 0.3.4

**Comment by kalmir** [comment]
Mhm, @mdelobelle, nothing really changed for me with the new release.
"Insert missing fields" does nothing.
But anyway, my FR wasnt specifically about missing fields, what I meant is to launch the same fields-bulk-edit menu which could also be triggered by the icon (in e.g. tab bar).
