### ISSUE TITLE
Use of tags in YAML

### ISSUE THREAD

**Issue by kmaustral** [mdelobelle/metadatamenu#154]
At the moment, to use the tag for FIleClass it needs to be inline. If the tag is in YAML it doesn't trigger the FileClass. 

For those who like to tuck their tags away in the front matter, it would be great to have the convenience of linking them to FileClass.

**Comment by mdelobelle** [comment]
I can't reproduce that.

Could you paste your YAML section please?

**Comment by kmaustral** [comment]
I seem to be adept at finding stray paths.

As far as I've been able to reproduce it, the critical variable seems to be
if there are lines after the YAML

---
tag: person
---


The FileClass applies only when I delete the lines after ---.

I've also seen the icon persist when the file is deleted:

[image: image.png]

These are minor glitches but hopefully useful for refining this wonderful
tool.

Kevin

**Comment by mdelobelle** [comment]
I've reworked the frontmatter management in 0.4.0. could you check if you can reproduce this behavior with this new version?

**Comment by kmaustral** [comment]
That seems to work well now, thank you.

And the new Canvas feature is awesome. I wasn't thinking this would be
possible, but as before I suspect it will become part of my workflow.

All the best.

**Comment by mdelobelle** [comment]
Great. Stay tuned, new funny features with canvas coming soon ;)
