### ISSUE TITLE
FR: Reducing the amount of options in the right click menu

### ISSUE THREAD

**Issue by ltctceplrm** [mdelobelle/metadatamenu#155]
Would it be possible to add a setting so we can choose which options to show in the right click menu?
I'd like to reduce the right click options to only those I actually use, namely changing a yaml field from true to false or inserting dates with the calendar, I know there's the "Display field options in context menu" toggle but that removes all of the options except one.

Thank you

**Comment by mdelobelle** [comment]
This would increase the complexity of the settings imho.
I've planned to bind some field actions with commands (and from there you can bind them to hotkeys) see #163 .
So you could toggle off "Display field options in context menu" and set a hotkey for your favorite fields

**Comment by ltctceplrm** [comment]
If I could toggle between true and false for a specific field with a hotkey then that would be a great solution as well, I'll look forward to that.
Thank you

**Comment by ltctceplrm** [comment]
I see that the hotkey has been added and together with the commander plugin I now have 1 "Manage field at cursor" button in my right click menu which is exactly what I was hoping for, thank you for the addition.
I'm going to mark this issue as closed since the hotkey solution works great.
