### ISSUE TITLE
Cascading tags / fileClasses, extends method questions

### ISSUE THREAD

**Issue by balola** [mdelobelle/metadatamenu#156]
If I want to use cascading fileClass I found some hardness.
- Datav.md fileClass = User/dolgozo which extends User/ember
I cannot see in datav.md's form the User/ember fileClass group but I can see its fields. (Név, Született, Lakhely)
![image](https://user-images.githubusercontent.com/24825268/199728851-4e3f7ae5-db63-44a7-ae1e-224cb1165388.png)
- Could you give a context menu "Add - **extends** fileClass" to choose fileClasses, like ![image](https://user-images.githubusercontent.com/24825268/199731319-fce7b8e9-1e7a-4dad-8df6-95407deab4cb.png)
- Is it possible to use tags to replace fileClass in "extends" method

**Comment by balola** [comment]
Plus, comment:
It would be nice to see all available fields (hide or unhide) for fileClasses in the form to hide/take out, unhide/insert fields.
Now you can insert **all** hidden fields of fileClasses

**Comment by mdelobelle** [comment]
> If I want to use cascading fileClass I found some hardness.
> 
> - Datav.md fileClass = User/dolgozo which extends User/ember
> 
> I cannot see in datav.md's form the User/ember fileClass group but I can see its fields. (Név, Született, Lakhely)
> 
> ![image](https://user-images.githubusercontent.com/24825268/199728851-4e3f7ae5-db63-44a7-ae1e-224cb1165388.png)
> 
> - Could you give a context menu "Add - **extends** fileClass" to choose fileClasses, like ![image](https://user-images.githubusercontent.com/24825268/199731319-fce7b8e9-1e7a-4dad-8df6-95407deab4cb.png)
> 
> - Is it possible to use tags to replace fileClass in "extends" method
> 
> 

those feature are now located in the fileClass view > fileClass setting tab. I wouldn't put that in the context menu (would be too clutered imo)

**Comment by balola** [comment]
I see.
Thanks.
