### ISSUE TITLE
FR: TagAlias to help with mapWithTag

### ISSUE THREAD

**Issue by MMoMM-org** [mdelobelle/metadatamenu#162]
How it is at the moment:

I have a FileClass called Plugin (FileClass) and I would like to use mapWithTag. This would require me to use a tag #Plugin (FileClass)

What I would like:

Be able to specify an Alias which will be used explicitly with Metadata Menu to be able to use a tag like #Plugin

How could this be done:

Adding a 
TagAlias: Plugin
to the frontmatter of the fileclass note, perhaps even with sub tag support, e.g #Obsidian/Plugin

**Comment by mdelobelle** [comment]
Hi

why don't you name you fileClass "Plugin.md" instead of "Plugin (fileClass).md"?

**Comment by MMoMM-org** [comment]
Because I already have Plugin 😀

**Comment by mdelobelle** [comment]
is "Plugin.md" also a fileClass?
if it's the case, i would recommend to put "mapWithTag: true" and "extends: [Plugin (fileClass)]" in its frontmatter.
If "Plugin.md" is not a fileClass i would recommend that you dedicate a folder only for fileClasses files so that the plugin works as expected.

Are you in a different situation?

**Comment by MMoMM-org** [comment]
There are really several issues here:
a) I have a note already with the name of Plugin, so I can't use Plugin as FileClass but my Tag is called #Plugin
b) I don't want to use a normal Alias as that would show up on open, completion etc too.. I would need to look at the location to figure out if Plugin is my note or the FileClass.

Substitute Plugin with anything you like... Obsidian for example. I have a Note Obsidian and a Tag Obsidian. If I now want to create a FileClass I run into the same issue again.

**Comment by MMoMM-org** [comment]
Oh, and when I create a new FileClass.. let's call it PKM and have already a link with [[PKM]] in some of the notes, the link will now point to the FileClass, instead to be still dangling... waiting for a note which explains what PKM is.

**Comment by mdelobelle** [comment]
One question: do you have a specific folder for your fileClass files?

**Comment by MMoMM-org** [comment]
yes

**Comment by mdelobelle** [comment]
okay! I see now
makes sense. I'll have a look at it

**Comment by MMoMM-org** [comment]
thanks.. looking forward to it..

**Comment by mdelobelle** [comment]
done: 0.3.6
