### ISSUE TITLE
FR: Option to make command from given "Update <field>" action

### ISSUE THREAD

**Issue by kalmir** [mdelobelle/metadatamenu#163]
We can update every single field via context menu > manage fields > choosing the given field.

It would be cool to have the **possibility to choose a field/update-action and tie it to a new command**.
Much like Templater allows to assign commands/hotkeys to templates.

This could then be used, e.g., to construct a macro in QuickAdd which would step-by-step introduce update-action for selected fields. Great for adding new tasks-notes.

**Comment by mdelobelle** [comment]
Hi good idea, this will be included in the next releaase

**Comment by mdelobelle** [comment]
done: 0.3.6

**Comment by cyb3rw0lf** [comment]
how does it work to create a command to update a field?
When clicking on "set a command for this field" is just create the command to add the field to a note.

For example I have a field to change status of a note: draft, in progress, complete and I would like a command that prompt the update field sub-menu directly.

**Comment by reorganice** [comment]
Yeah I have the same problem. 

Every note in my vault has a status.
 I just want to hit my hotkey and "change the value of status"
(using the suggester that normally comes up when clicking arrow down next to status in my properties pane)

This would be amazing! Thanks for this great Plugin btw. I have been using all day!
