### ISSUE TITLE
Fileclasses not working

### ISSUE THREAD

**Issue by kearalong** [mdelobelle/metadatamenu#167]
I can't seem to get file classes to work in my vault. To test, I used another test vault I had installed (The LYT Kit) and file classes worked easily. I tried turning off all community plugins and snippets, and going through and checking that all of my settings were the same as the LYT Kit ones to see if there was anything interfering. But in my main vault, Fileclasses don't work. 

The contextual menu options show up to add file classes and to add or edit the file class of a note, but when I add the file class, the note doesn't register any of that file class's fields and it doesn't show the icon beside the note title. In the test vault, these things do work. I can't figure out what it is in my vault causing this not to work.

**Comment by alancunha26** [comment]
It seems something with last update. I have a similar problem with my fileClass that have space in it title.

Here are a screenshot with the console error that i keep getting. Hope this will be fixed soon, this is the best plugin out there for rigid data modeling in Obsidian.

![image](https://user-images.githubusercontent.com/46824739/200488833-b1d4bc05-dd15-4ae2-9cfd-57d14e03e27e.png)

**Comment by mdelobelle** [comment]
Hi! thanks for pointing this out and for the console screenshot. 
I've pushed a hotfix (v0.3.5) to handle fileClasses with space in their names.
Though: they won't be usable with the "mapWithTag" (just like tags don't accept white spaces)

Could you test it please?

**Comment by alancunha26** [comment]
It is working now! Thanks for the quick fix

**Comment by kearalong** [comment]
Thanks for the quick fix! 
My fileclasses didn't have any space in the name, but it seems to have fixed itself after I completely deleted the plugin from .obsidian folder and then restarted a couple of times, not sure why.
