### ISSUE TITLE
Can't Add Fields to New fileClass

### ISSUE THREAD

**Issue by Annapox4** [mdelobelle/metadatamenu#168]
When I create a new note in the folder I've designated as the fileClass folder, or when I right-click on a note and choose "Add a new fileClass", I get a new fileClass as expected. But no matter what I try, I don't have the option to add or manage the fields for the fileClass, which renders it completely useless. I've tried renaming the fileClass folder (and changing the name in the plug-in settings), deleting the fileClass folder and making a new one, uninstalling and re-installing the plug-in, restarting Obsidian, disabling my other plug-ins, restarting my computer, and even uninstalling and re-installing Obsidian (and then installing the plug-in, obviously). On rare occasions I get the option to add a field to the fileClass as if it isn't a fileClass (as in, I see a menu for the name of the field and its value, but I don't have the option to set the input type for the field like I should be able to in a fileClass). For reference, I was following along with [this video](https://www.youtube.com/watch?v=7o9j7WJfhi0), or trying to, at least.

**Comment by Annapox4** [comment]
Apparently this is like when your car makes a funny noise until you take it to the mechanic. I restarted my computer one more time, and suddenly it works. No idea how that happened, but I guess it's resolved anyhow.

**Comment by Smitty010** [comment]
I saw the same thing.  I think it's probably a bug with how the menu item gets added to the right click.  If you've just installed the plugin, it's not there.  Restarting obsidian seems to make this work.  It might also relate to whether you have another app using the right click (I had Highlightr adding an item); however, i think this seems unlikely).  Regardless, restarting obsidian seems to fix the problem.
