### ISSUE TITLE
Automations

### ISSUE THREAD

**Issue by imeed166** [mdelobelle/metadatamenu#170]
Thanks again for the amazing updates.

I wanted to suggest a new section in the plugin setting, where the user could define automations that could be triggered either through the command palette or with a button in a dataview table.

The automation would be defined either with javascript or using the UI in the setting, for example (set property "text" to "something" and set property "date" to today and ... etc)

**Comment by mdelobelle** [comment]
I think it would be in the scope of another plugin (maybe quickadd but i’m not familiar) that could leverage metadata menu api to change the fields values.
