### ISSUE TITLE
Metadata Menu does not like emojis in fields

### ISSUE THREAD

**Issue by PhyberApex** [mdelobelle/metadatamenu#172]
Hey first of all, awesome plugin!

I am having some issues tho with my usage of inline fields. I really like to have a prefix emoji on my inline fields but metadata menu doesen't really seem to like it. Behaviour I have witnessed in trying to fix it for me:

1. In file classes if I give a specific field the name with the prefix emoji it just gets straight up ignored everywhere.
2.  If I want to update a field with a prefix emoji using metadata manager the update gets ignored (works fine as soon as I remove that emoji)

If you have any workaround for this I'd appreciate it! If you want to point me in the right direction code wise I'd also be open to do a PR on this one (given my zero experience with Obsidian plugins and my suspicion this has a lot to do with dataview internals I have no idea if I would be of any help tho).

~ Cheers

Edit: Here's an example from my notes
```
## 📇 Additional Metadata

- 🏷 Name:: Zombicide - Undead or Alive
- 🗂 Type:: #type/crowdfunding
- 🏁 Status:: #status/complete 
- 📆 OriginalExpectedDate:: 2022-03
- 📆 CurrentlyExpectedDate:: 2022-10-17
- 📆 LastUpdate:: 2022-10-08
- 💰 Spent::  1 $
```
With this fileClass file:
```
Spent:: {"type":"Number","options":{"min":"1"}}
Name:: {"type":"Input","options":{}}
OriginalExpectedDate:: {"type":"Date","options":{"dateFormat":"YYYY-MM-DD","defaultInsertAsLink":"false"}}
CurrentlyExpectedDate:: {"type":"Date","options":{"dateFormat":"YYYY-MM-DD","defaultInsertAsLink":"false"}}
ArrivedDate:: {"type":"Date","options":{"dateFormat":"YYYY-MM-DD","defaultInsertAsLink":"false"}}
```

**Comment by mdelobelle** [comment]
Hi, thank you for your feedback.
This behaviour is due to the fact that dataview remove forehead emojis when parsing inline fields (see https://github.com/blacksmithgu/obsidian-dataview/issues/1346).
So if you define a field containing an emoji in the fileClass, the only way to use it is to put your field in the frontmatter of the note (dataview isn't removing emojis from yaml fields' names)

**Comment by PhyberApex** [comment]
Okay that makes sense. But how about not using file classes? Because even without file classes I am not able to edit those fields with metadata menu. Is there anything that can be done there?

**Comment by mdelobelle** [comment]
the same problem occurs with fields defined in the plugin settings, not only with fields defined in fileclasses

**Comment by PhyberApex** [comment]
Hey, thanks for your fast responses! Too bad it does not work. I was just wondering because it does seem to work with the MetaEdit (https://github.com/chhoumann/MetaEdit) plugin. They are able to update the fiel. Not sure what kind of magic they do behind the scenes but maybe that could be a possible fix here as well?

~Cheers

**Comment by brimwats** [comment]
Just adding a +1 here and another datapoint: 

![image](https://github.com/mdelobelle/metadatamenu/assets/73113656/115eade9-8b67-4581-bf47-1b2b9ecfe98f)
![image](https://github.com/mdelobelle/metadatamenu/assets/73113656/c6101b40-b8af-47ab-8368-c4c2f5f10f39)
![image](https://github.com/mdelobelle/metadatamenu/assets/73113656/390fb321-b4b6-4c68-8f06-d9ae1fced186)

**Comment by mdelobelle** [comment]
A solution for that would be to have add another styling option for the field definition. 
We currently support **B** _I_ `code` and -strikethrough-, we could add a « character decorator » to prepend to the field name but not being part of the field name (the deocrator wouldn’t show in dataview tables, modals, etc)
WDYT?
