### ISSUE TITLE
Display in table view

### ISSUE THREAD

**Issue by balola** [mdelobelle/metadatamenu#177]
fileClass: [ fc1, fc2] 
- The note uses **more** fileClasses is not going to appear in the "display in table view" of fc1 or fc2.

- How I realized in the "display in table view" I can see the file name, not the file link. I can see the right pointer but I cannot link to the note.

Fülike

**Comment by mdelobelle** [comment]
good catch. will be fixed in the next version

**Comment by mdelobelle** [comment]
fixed in 0.3.7
