### ISSUE TITLE
Renaming fileClass links

### ISSUE THREAD

**Issue by abdcef** [mdelobelle/metadatamenu#178]
I like that I can have field options in md files that are stored in a folder. The only issue I have is that if I need to rename a file that contains field options, I need to manually update it in all fileClasses. Is there a way to make this automatic?

**Comment by mdelobelle** [comment]
Hi, unfortunately that is not yet possible because obsidian links aren't managed in frontmatter (they don't update automatically when the note's name has been changed).

Maybe it will be possible in a near future because obsidian team is reported working on improving frontmatter management.
