### ISSUE TITLE
Metadata Form - Icon Not Appearing

### ISSUE THREAD

**Issue by yurijserrano** [mdelobelle/metadatamenu#179]
Good Evening

Even after activating the metadata form button it is not appearing as can be seen in the images right below:

![image](https://user-images.githubusercontent.com/14169134/202335727-6e9a4772-2f17-4098-b172-9902b5e2e9eb.png)

![image](https://user-images.githubusercontent.com/14169134/202335788-38ff6648-e220-48eb-9867-580b0a2cdc30.png)

If you need anything else, just let me know

Have a pleasant day

**Comment by vkbytes** [comment]
I am having the same problem.. @mdelobelle for supertags the "right click" menu to add new field items also does not appear. I am just youing `cmd+p` to insert the fields.

**Comment by vkbytes** [comment]
FYI:

![CleanShot 2022-11-17 at 18 19 31](https://user-images.githubusercontent.com/79217316/202450960-7a49ec08-fe4e-4b49-846a-2b9f931dd2de.png)

**Comment by rlolingo** [comment]
> FYI:
> 
> ![CleanShot 2022-11-17 at 18 19 31](https://user-images.githubusercontent.com/79217316/202450960-7a49ec08-fe4e-4b49-846a-2b9f931dd2de.png)

i had this problem too.
I seemed to solve it by also adding "person" to the `tagNames: []` array.

Try: `tagNames: [person]` in the frontmatter. ^^

**Comment by vkbytes** [comment]
Thanks @rlolingo, I tried it but it did not work.

**Comment by mdelobelle** [comment]
> FYI:
> 
> ![CleanShot 2022-11-17 at 18 19 31](https://user-images.githubusercontent.com/79217316/202450960-7a49ec08-fe4e-4b49-846a-2b9f931dd2de.png)

Hi, do you have any other plugin installed in your TESTINGVAULT?

**Comment by mdelobelle** [comment]
> Good Evening
> 
> Even after activating the metadata form button it is not appearing as can be seen in the images right below:
> 
> ![image](https://user-images.githubusercontent.com/14169134/202335727-6e9a4772-2f17-4098-b172-9902b5e2e9eb.png)
> 
> ![image](https://user-images.githubusercontent.com/14169134/202335788-38ff6648-e220-48eb-9867-580b0a2cdc30.png)
> 
> If you need anything else, just let me know
> 
> Have a pleasant day

Hi, do you have any error message in the console?

Could you paste the frontmatter of your note?

**Comment by yurijserrano** [comment]
Good Afternoon @mdelobelle

**Regarding your first question:** 

> Hi, do you have any error message in the console?


No, no error is appearing


**Regarding your second question:** 

> Could you paste the frontmatter of your note?


Of course

`questionId: 771773
project: Critter Chronologer
nanodegree: Java Web Developer
questionLink: 
studentName: Patrizia G
questionType: Both
questionDuration: 169
answered: 2022-02-01
escalated: false
accepted: true
upvoted: true
codeFormFilled: true
followFormFilled: true
tags:
- knowledge_question
- jwd
- cc`



![image](https://user-images.githubusercontent.com/14169134/202870134-372dbe48-56dc-4452-9304-c30e2ee611ef.png)


I am waiting to hear from you

**Comment by mdelobelle** [comment]
therés no fileClass defined in your frontmatter. Donyou use a fileClass alias? which one?

**Comment by yurijserrano** [comment]
Good Afternoon @mdelobelle 

No, I do not use the file class because I do not want to use the properties on the inline mode but inside the frontmatter, so I registered all properties in the Presets Field Settings which I have seen that ended up supporting.

**Comment by mdelobelle** [comment]
that's it!

Preset fields in the plugin's setting are working fine but they don't provide the button.
buttons are only showing up for files that have a fileclass field defined.

You could define a global fileclass with all your fields definition (just like in the plugin's setting) and then you should get buttons for all your notes

**Comment by yurijserrano** [comment]
Good Evening @mdelobelle 


**Regarding this excerpt:**

> You could define a global fileclass with all your fields definition (just like in the plugin's setting) and then you should get buttons for all your notes

This is the problem, to define a global file class I have to use the inline syntax, but I want my properties to be inside the frontmatter and not outside.

In my opinion, this is one of the negative points of the plugin because it doesn't work with the properties inside the YAML block but only with the inline syntax.

Is it possible to make this portability @mdelobelle?

**Comment by vkbytes** [comment]
@mdelobelle I can confirm that the issue seems to have resolved with the new updates.. I'll keep testing it but for now I think this is solved at my end.

**Comment by mdelobelle** [comment]
> Good Evening @mdelobelle 
> 
> 
> 
> 
> 
> **Regarding this excerpt:**
> 
> 
> 
> > You could define a global fileclass with all your fields definition (just like in the plugin's setting) and then you should get buttons for all your notes
> 
> 
> 
> This is the problem, to define a global file class I have to use the inline syntax, but I want my properties to be inside the frontmatter and not outside.
> 
> 
> 
> In my opinion, this is one of the negative points of the plugin because it doesn't work with the properties inside the YAML block but only with the inline syntax.
> 
> 
> 
> Is it possible to make this portability @mdelobelle?
> 
> 

Hi you can use fileClass definition for fields that are in the YAML block. This is not at all limited to databiew inline fields syntax

**Comment by yurijserrano** [comment]
Good Evening @mdelobelle 

Thank you so much for the information :)

After installing the most up-to-date version, I was able to see that the icon appeared correctly and that in fact the fileClass also supports the properties inside the YAML block.

Have a productive day.
