### ISSUE TITLE
Hello world for dataviewJs

### ISSUE THREAD

**Issue by henryZrncik** [mdelobelle/metadatamenu#180]
Hello would it be possible to provide either some sort of minimal hello world for asynchronous dataviewJs (possibly also all dependencies that are necessary or brief mention of plugins it may clash with)
e.g.
```
---
someAttr: someVal 
---
```
````
```dataviewjs
const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api 
f(dv, dv.current(), "someAttr") 
```
````
I am failing on this example and also the more complicated one found on linked demo with following error: 

Evaluation Error: TypeError: fieldContainer.setAttr is not a function

**Comment by mdelobelle** [comment]
Hi! you can find a full example here https://mdelobelle.github.io/metadatamenu/controls/#syntax

**Comment by henryZrncik** [comment]
thanks for answer, 
i followed mentioned snipped (there is one extra `)` symbol in the end that should be removed). 
Sorry for bringing that again, but i still ended up with exactly same error message 
i.e. 
```
Evaluation Error: TypeError: fieldContainer.setAttr is not a function
    at fieldModifier (plugin:metadata-menu:8854:18)
    at eval (plugin:metadata-menu:9087:41)
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:10:13)
    at Array.map (<anonymous>)
    at Proxy.map (plugin:dataview:11738:39)
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:8:10)
    at DataviewInlineApi.eval (plugin:dataview:15671:16)
    at evalInContext (plugin:dataview:15672:7)
    at asyncEvalInContext (plugin:dataview:15682:32)
    at DataviewJSRenderer.render (plugin:dataview:16267:19)
```

Does it make sense with following code ? 

<img width="536" alt="image" src="https://user-images.githubusercontent.com/40673682/202860867-86c00403-d7f9-4652-ba82-698d738cd0e8.png">

**Comment by mdelobelle** [comment]
can you try to remove the double quotes in your frontmatter? they aren't necessary

**Comment by henryZrncik** [comment]
same result, 
I am running it on  MacOS Monterey 12.6.1
Obsidian Version 1.0.3 (Installer 0.15.8)
I have also Node.js v18.0.0. 

also tried it with almost all plugins disabled but again same result. Don't you know about some dependency or something like that which could cause this ?   

<img width="556" alt="image" src="https://user-images.githubusercontent.com/40673682/202874860-fc1667c7-5e17-4e4d-919b-130d003a2e6d.png">

Thanks for suggestion anyway.

**Comment by mdelobelle** [comment]
Can you paste the content of your music.md fileClass note?

**Comment by henryZrncik** [comment]
I do not know what you mean by fileClass (i assume it is field from yaml metadata inside file called `music.md`)
In that case it is again just 

---
fileClass : music
masterization: smt
tune : smt2

---
