### ISSUE TITLE
FR: Task fileClass

### ISSUE THREAD

**Issue by thomasdwood** [mdelobelle/metadatamenu#182]
Loving the app so far. Especially fileclasses... they've transformed all my vaults.

I would love to be able to set a global fileclass for all Tasks and to have tasks gain all the benefits of file classes

Context: All my tasks get a p:: (priority) and an e:: (effort) value.
I currently have them set as preset field settings so that I can quickly define them in tasks. 

I view all of my tasks mainly through Dataviews, which pull in tasks based on what file they're in or if they have a file linked in the task, or on due date or on emojis I've added to the task (etc). 

But task data views don't get all the fun options that table data views do from Metadata Menus. I'd love to be able to see all my tasks in my task dataview and right click on one to be able increase the priority, change the due date, or add an emoji (based on a set of emojis added to a new MM field on the tag). 

Would also be interesting to be able to define task specific metadata on file classes. Meaning all tasks made in notes with this file class would gain those specific fields as metadata for those tasks, like another fileClass but just for the tasks.

**Comment by mdelobelle** [comment]
Hi thank you for your feedback, much appreciated

This is really a great idea. Unfortunaltely fileClasses are deeply leveraging the "note" object. 
Therefore, it would require significant efforts to replicate those capabilities at task level and make sure that this fits well with the fileClass definition at file level.
I'm afraid I won't have enough time to work on it in the near future

**Comment by thomasdwood** [comment]
Totally understand. I really do love the plug in. Thanks for considering it!

**Comment by GamerGirlandCo** [comment]
i think this would be a nice enhancement to have. may i take a crack at implementing it?
