### ISSUE TITLE
[BUG/MISSING] Cycle fields

### ISSUE THREAD

**Issue by Alejandro-Stolz** [mdelobelle/metadatamenu#183]
I am loving this plugin so far but I wonder one thing. If I create a cycle field with eg. 3 fields and I want to switch between them, there are several posibilities to do it, like right click > select option with |>:
![image](https://user-images.githubusercontent.com/73649874/202740279-f827490f-5446-4257-8cc5-f8b2a1b92bdb.png)

But I like to use keyboard shortcuts wherever it is possible. The command I am using for the rest of the fields is 
> Metadata Menu: Manage field at Cursor

but I was expecting it to switch automatically to the next field, as theoretically, as far as I know,  it _should_ not be possible to not follow the designed order, but the outcome is the following:

![image](https://user-images.githubusercontent.com/73649874/202741043-2035c01c-c748-45ce-833a-be6ade88d1b0.png)
and I can choose whichever I want from the list.

When the command
> Metadata Menu: Fields Options

is executed, I can choose the desired field and it is replaced automatically
![image](https://user-images.githubusercontent.com/73649874/202741277-de942fc5-93f7-4837-a8e6-c31a6b0eb02e.png)

I hope this is easy to fix. Thank you again for this amazing plugin

**Comment by mdelobelle** [comment]
fixed in 0.3.7

**Comment by Alejandro-Stolz** [comment]
Thank you so much! Really appreciate your effort with this plugin
