### ISSUE TITLE
[Bug] Metadata menu plugin failed to load

### ISSUE THREAD

**Issue by kearalong** [mdelobelle/metadatamenu#184]
"Failed to load plugin metadata-menu" notification on opening Obsidian. On reinstall, although it shows in my community plugins list and I can enable it, the settings button for the plugin is missing and any metadata menu commands and functionality is missing.

I really love this plugin- not sure why it is so buggy for me!

**Comment by mdelobelle** [comment]
Thank you for the report
Do you see any error message in the console?

**Comment by kearalong** [comment]
I checked the developer console and saw that it was finding an error with one of my files for some reason. I deleted the file it referenced and it started working again. Strange! Sorry, I wasn't aware of the developer console before. Thank you!

**Comment by mdelobelle** [comment]
great. Did you keep a copy of the file that was responsible of the error? it may contain a usefull pattern to include in the indexing exceptions
