### ISSUE TITLE
Preset Fields settings - Display issue

### ISSUE THREAD

**Issue by willasm** [mdelobelle/metadatamenu#189]
For Select and Multi Select from lists if the number of items in the list is large the word list wrapping could be handled better perhaps? Easier to show you what I mean with this picture.

![PresetFieldsSettings1](https://user-images.githubusercontent.com/94352899/202867480-845974d5-17d9-419d-932b-357284dab982.png)

More importantly, every time I add a new item to the list, the edit fields dialog grows wider due to the `Preset options:` line.
For example...

![PresetFieldsSettings2](https://user-images.githubusercontent.com/94352899/202867632-b22c402c-8c16-484b-a33e-069fca294a32.png)

As you can see, this line should to be wrapped somehow, otherwise eventually the dialog will be wider than my screen.
Thanks for the great plugin!!

**Comment by mdelobelle** [comment]
ok, i think i'll remove the Preset options section. Since the list of items is just below, it's not useful.
I'll also try to fix the display issue in the settings in the next release

**Comment by willasm** [comment]
Removing the preset options makes sense as it is redundant with all the items also listed right below it. The settings display issue is not all that critical an issue to me. I can clearly make out what type it is, although it looks odd.
Thanks again.

**Comment by mdelobelle** [comment]
fixed with 0.3.9
