### ISSUE TITLE
Suggester via API

### ISSUE THREAD

**Issue by mayurankv** [mdelobelle/metadatamenu#192]
Is it possible to access the suggester via the API? The suggester would be really helpful when writing templates.

**Comment by mayurankv** [comment]
Just to add, I'm aware of templater's suggester and prompt but the UI and UX of this suggester is much better for metadata and it means I don't need to define all the possible options for the same piece of metadata across different templates

**Comment by mdelobelle** [comment]
Hi. Can you give me an example of how you would use it in your template?

**Comment by mayurankv** [comment]
I use this currently for example `const Languages = await tp.system.prompt("Languages Spoken","",false,true)` where I do not specify possible languages due to templater not allowing multiselect - by using metadatamenu, I could preset options and then set the Languages variable using the metadata menu (or rather than a variable, even just changing the frontmatter directly would be great).

**Comment by mayurankv** [comment]
To add, what I want is rather than typing `Cmd-P > Metadata Menu Update Fields > Update Languages > Suggester Prompt Opens`, to be able to call something in templater or dataview like metadatamenu.update_prompt(field: string)

**Comment by mdelobelle** [comment]
Unfortunately that would require a lot of work on the suggester to fulfill this request. I won't be able to implement it as it is quite at the edge of the plugin's scope
