### ISSUE TITLE
Support for the projects plugin

### ISSUE THREAD

**Issue by imeed166** [mdelobelle/metadatamenu#194]
I don't know how exactly this plugin will support the projects plugin. 
But I've noticed that this plugin handles different metadata types better than the projects plugin table view.

So I thought that maybe we could enable an option in the projects plugin setting, that would make all the fields in the table editable via metadata menu (just like we can do with dataview tables).

Do let me know if I need to open a FR in the projects plugin repo.

**Comment by mdelobelle** [comment]
Unfortunately, unlike dataview, projects isn't providing an api to build the views programmatically so I won't be able to propose a field modifier like for dataview.
You should probably open a FR in their repo plugin

**Comment by marcusolsson** [comment]
@mdelobelle Hi! I'd love to explore possible integrations. Unfortunately, I'm not as familiar with this plugin (I'll be sure to try it out as soon as I get the chance!). Right now, plugins can integrate via the experimental [Custom View API](https://github.com/marcusolsson/obsidian-projects/tree/main/obsidian-projects-types). Is that what you're looking for? If not, could you share some more details on what Projects would need to provide in terms of API support?

**Comment by mdelobelle** [comment]
Hi unfortunately I won't have time to look into it.
