### ISSUE TITLE
[FR] Support YAML Arrays

### ISSUE THREAD

**Issue by yurijserrano** [mdelobelle/metadatamenu#195]
Good Evening @mdelobelle 

I hope you are well

I noticed that the plugin supports regarding the array only the syntax:

```
key1: [value1,value2,value3,value4,value5]
```

But it does not support the syntax:

```
key1:
  - value1
  - value2
  - value3
  - value4
  - value5
```

Would it be possible to make the plugin also compatible with this second syntax?

I am waiting to hear from you

**Comment by mdelobelle** [comment]
Hi it would be possible with a future release of obsidian that will include api for better frontmatter management

**Comment by yurijserrano** [comment]
**Good Afternoon @mdelobelle**


I hope you are well


Regarding this excerpt:

> Hi it would be possible with a future release of obsidian that will include api for better frontmatter management


Glad to hear, this will allow the entire YAML workflow to be covered.


Have a wonderful day

**Comment by HyperEpsilon** [comment]
> Hi it would be possible with a future release of obsidian that will include api for better frontmatter management

What sort of frontmatter management would be required for this? Do you know if there is an ongoing [feature request](https://forum.obsidian.md/c/feature-requests/8) for what would be needed?

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by mdelobelle** [comment]
I close this issue. don't hesitate to open a new one in case you have specific needs regarding the recent yaml improvements
