### ISSUE TITLE
Add support for multiple key::value pairs per line

### ISSUE THREAD

**Issue by zackdn** [mdelobelle/metadatamenu#20]
I want to use DataView fields in my notes and have their values autocompleted. However, autocomplete does not work if you include the brackets (or parentheses).

**This works:**
![SNAG-0029](https://user-images.githubusercontent.com/13019690/180470771-32cb2620-b847-45a8-8b66-bdf9d5ca8ff1.jpg)

**This does not:**
![SNAG-0030](https://user-images.githubusercontent.com/13019690/180470792-2584614a-e8de-4c25-b0e0-eec4c4d24afc.jpg)

**Here is the field as defined in my fileClass file:**
![SNAG-0031](https://user-images.githubusercontent.com/13019690/180470897-ac7c352a-7d30-42d7-aa40-4cfe9610aae2.jpg)

_Originally posted by @zackdn in https://github.com/mdelobelle/metadatamenu/issues/10#issuecomment-1192681471_

**Comment by mdelobelle** [comment]
closed with #47
