### ISSUE TITLE
Can't save metadata field with emoji

### ISSUE THREAD

**Issue by alancunha26** [mdelobelle/metadatamenu#202]
When trying to save a metadata field with an emoji on title, it is not saving

![image](https://user-images.githubusercontent.com/46824739/205507953-7b2b66d2-c860-487e-9a27-a90eda430dff.png)

![image](https://user-images.githubusercontent.com/46824739/205507976-be25f282-6bca-41cf-9356-919f63abd21f.png)

**Comment by mdelobelle** [comment]
Hi! that's a limitation from Dataview: it remove the forehand emojis in field names. Unfortunately, that's a limitation I can't get around
