### ISSUE TITLE
Console bugs when deleting some files and using the metadatamenu api with quickadd

### ISSUE THREAD

**Issue by alancunha26** [mdelobelle/metadatamenu#204]
![image](https://user-images.githubusercontent.com/46824739/206041941-aff64932-2fbc-42ab-a46e-89106e4ba088.png)

**Comment by mdelobelle** [comment]
DO you still encounter this issue with the newer version of the plugin?

**Comment by alancunha26** [comment]
I think this can be closed already, didn't encounter the problem anymore.
