### ISSUE TITLE
Formulas leading to issues with TableView and FileClass Fields

### ISSUE THREAD

**Issue by stefanopagliari** [mdelobelle/metadatamenu#206]
First of all, thank you for this very helpful plugin. 

One of the use cases I have in mind for this is to create a formula to automatically generate a metadata field with the notes that are linking to the current one (and that have a certain value).

But I'm running in some troubles shortly after I introduce a formula-based field. In particular, the field editor stops being responsive, until I delete the formula from the note. I am not a JS expert but I wonder if my formula is triggering some circular behaviour.

<img width="502" alt="CleanShot 2022-12-11 at 22 41 05@2x" src="https://user-images.githubusercontent.com/30759878/206933268-a79747de-bc48-44ec-bb07-0a58bc6bc286.png">

More specifically, clicking on "edit" or "delete" next to the formula (or any other field) does not work anymore

**Comment by mdelobelle** [comment]
Hi. I think this query is wrongly formatted: dv.pages('#Test') is returning an array. so dv.pages().file would be undefined or something
