### ISSUE TITLE
YAML front matter - preview / view

### ISSUE THREAD

**Issue by balola** [mdelobelle/metadatamenu#207]
Hi,

In view mode the icon in fields cannot see 

![image](https://user-images.githubusercontent.com/24825268/207302974-53d52ef9-acac-4e52-ba4d-81acf44e441e.png)

---

![image](https://user-images.githubusercontent.com/24825268/207302890-5f706598-499c-4dfe-9c59-0037849585f5.png)

Fülike

**Comment by mdelobelle** [comment]
I presume this is related to Obsidian's core management of yaml block. There's pretty much nothing I can do about it sorry

**Comment by mdelobelle** [comment]
This has been fixed with the recent addidtion of Properties in obsidian
