### ISSUE TITLE
Heavy performance lag on note's editing

### ISSUE THREAD

**Issue by meskill** [mdelobelle/metadatamenu#208]
I have a big vault with a lot of tags. And if I enable metadata menu I have a lot of lags during typing in my notes.

According to performance profiling the issue comes from the plugin, and it can take up to 500ms every time.

Here is the report itself (every pink column is metadata function):
![image](https://user-images.githubusercontent.com/8974488/207696817-ed8d5917-e3f8-4a5e-8987-2345e4a6aee4.png)

[Profile-20221214T203157.zip](https://github.com/mdelobelle/metadatamenu/files/10231058/Profile-20221214T203157.zip)

The source code that is called located [here](https://github.com/mdelobelle/metadatamenu/blob/013c091b9a3ace2715d652220b0402d21250722b/src/components/FieldIndex.ts#L80)

Plugin version: 0.3.9

**Comment by mdelobelle** [comment]
Are you using Lookup and Formulas type fields?
If so. I would start by changing their setting to disable the automatic update of those fields and see if it improves the performance

**Comment by meskill** [comment]
> Are you using Lookup and Formulas type fields? If so. I would start by changing their setting to disable the automatic update of those fields and see if it improves the performance

No. I use only fields with predefined values from list that I've specified in settings

**Comment by mdelobelle** [comment]
I've made some changes in 0.4.0 in the way fields get indexed and updated. In some cases it reduces the number of read/write operations and therefore improves the performance. Could you give it a shot?

**Comment by meskill** [comment]
It didn't help much, the lags are pretty the same. I'm attaching performance profiles that you can open with Chrome DevTools on Performance tab and explore the things that taking too much time inside your plugin.
[Profile.zip](https://github.com/mdelobelle/metadatamenu/files/10361686/Profile.zip)

At quick view it seems that function [getFilesFieldsExists](https://github.com/mdelobelle/metadatamenu/blob/fbb351390ce4c9eecf2ac32e1f1363f3b5799984/src/components/FieldIndex.ts#L477) executes some heavy computation. Looks like the function traverses all of the notes inside vault (over 5k notes in my case) to check that some of them have predefined fields. I'm not sure that computations are even required when I updating single note and in most cases such computations should be cached to prevent high cpu usage.

**Comment by mdelobelle** [comment]
Thanks a lot! I didn't know about the performance profile. I'll dig into it.

**Comment by mdelobelle** [comment]
I've made some optimization. Can you try again with 0.4.10?

**Comment by meskill** [comment]
With 0.4.10 I see big improvement and now it feels almost as fluent as without the plugin. Thank you

Although, it seems like there are still some parts that should be considered to optimize.
![image](https://user-images.githubusercontent.com/8974488/211186829-247fe2a7-8f69-479f-b674-6303ea9ec82a.png)

**Comment by mdelobelle** [comment]
I'll close this one at this stage and see if the new datacore plugin from dataview developer will provide improvements on fields indexing that I can leverage to improve the speed of metadata-menu
