### ISSUE TITLE
Adding multi select option from modal overwrites last option

### ISSUE THREAD

**Issue by chauser10** [mdelobelle/metadatamenu#210]
Adding a field from the modal overwrites the last option. My expectation is this should add another entry instead. I've linked a video showing the bug. Single select fields work as desired.

[Youtube Video](https://youtu.be/00G6Qga2ERQ)

**Comment by mdelobelle** [comment]
I should be ok now with 0.4.1 . can you confirm?

**Comment by chauser10** [comment]
> I should be ok now with 0.4.1 . can you confirm?

From a quick manual test looks like it works. Thanks for the quick fix!
