### ISSUE TITLE
Mouse free operation

### ISSUE THREAD

**Issue by kmaustral** [mdelobelle/metadatamenu#214]
I find myself using your wonderful plugin more and more.

One form of friction is the need to always use the mouse to accept input. It would be ideal if this could be done with a return key, as with Quick Add. 

Thanks again.

**Comment by mdelobelle** [comment]
Hi,
This shouldn't be too difficult. Can you list the places where you'd need a key action instead of mouse click?

**Comment by kmaustral** [comment]
Great. With the command, Open this Note Field's Nodal, after entering new input into a field, it would be good to complete this using Enter on the keyboard. 

Same with Manage Field at Cursor.
