### ISSUE TITLE
FR: Cycle in reverse or "Undo"  

### ISSUE THREAD

**Issue by thecookiemomma** [mdelobelle/metadatamenu#218]
Use Case: I have several fields in my Daily Notes that are basically "Have I done this thing today?"  So, they're almost true / false set ups, but because of other plugins and the way they're set up, they're "null / 1" setups.  And sometimes, I click the wrong one. To fix it, I have to close the modal, navigate to the field, and clear it manually. 

Feature Request:  A reverse cycle, a "null" in list, or a "clear field" button.  Thanks.

**Comment by mdelobelle** [comment]
Good idea, I will probably add a generic "clear" action to every type of field

**Comment by mdelobelle** [comment]
I've added an option "Cycle begins by a null value" to cycle fields. It will be available in the next release

**Comment by mdelobelle** [comment]
Added in 0.4.3 Does it suit your need?

**Comment by thecookiemomma** [comment]
Yes!  Thank you!
