### ISSUE TITLE
FR: support page preview

### ISSUE THREAD

**Issue by ben1mit** [mdelobelle/metadatamenu#221]
It would be very nice if it were possible to hover over the links in the fileclass view and get page previews of the note, 
such as the one I get when I hover over links in my  markdown notes and press cmd

**Comment by mdelobelle** [comment]
This is something I was trying to achieve. Unfortunately that's not currently possible:
The fileclass view is a custom view where the "link" is just a regular html link and doesn't inherit all the cool features of internal links in markdown views.
I've barely managed to reproduce the click-to-open behavior, but couldn't do the same for the hover part.

**Comment by charleshan** [comment]
Dataview supports this out of the box including the use of html in Dataviewjs. For example, you can do this: `dv.el('span', "[[Test Page]]")`

Maybe worth looking into @mdelobelle?
