### ISSUE TITLE
FR: include extended fileClasses

### ISSUE THREAD

**Issue by ScottKillen** [mdelobelle/metadatamenu#223]
II think it would be great if you could flag a fileClass to list its extended fileClasses in its table view.

For instance: If I have a fileClass called `contact` which is extended by two other fileClasses: `person` and `business` I would like to be able to see all notes with fileClass `person` *and* `business` in the table view for `contact` showing of course only the fields derived from the `contact` fileClass

**Comment by lucas-wu-wakakak** [comment]
hello, I got a question. Can the fileClass of current version(1.1.9) support multiple extended fileClasses? Why can't I extend fileClass with more than one fileClass?

**Comment by mdelobelle** [comment]
> II think it would be great if you could flag a fileClass to list its extended fileClasses in its table view.
> 
> 
> 
> For instance: If I have a fileClass called `contact` which is extended by two other fileClasses: `person` and `business` I would like to be able to see all notes with fileClass `person` *and* `business` in the table view for `contact` showing of course only the fields derived from the `contact` fileClass

Hi. It's been a while, but this is now available in 0.6.9
