### ISSUE TITLE
Two bugs in Table View

### ISSUE THREAD

**Issue by koenbunders** [mdelobelle/metadatamenu#225]
1. Open 'Table View' for a FileClass
2. Click one of the listed pages (it opens in new tab)
3. Make change on the opened page
4. Return to the tab with the table view (from step 1)
5. Try to repeat step 2 for any of the listed pages. Bug: the page will not open, no repsonse.
6. Try to refresh using the 🔁 icon. Bug: the table view now completely disappears.

**Comment by mdelobelle** [comment]
Good catch.
The  second one is fixed. The first is more tricky, I'll need some assistance from dataview team.
One workaround would be to refresh the table after having updated any file in your vault

you can test it in 0.4.2
