### ISSUE TITLE
Yaml Front Matter doesn't work

### ISSUE THREAD

**Issue by Armand2022** [mdelobelle/metadatamenu#233]
Previously, in Filed Setting, I could quickly put several items on a single line in just a few clicks, now after the first item the cursor goes down and it is no longer possible to select other items, except by manually returning to the upper line. Also, after selecting an item, the word "null" appears for each item within the front matter.

**Comment by mdelobelle** [comment]
Could you make a screenshot of your issue please?

**Comment by Armand2022** [comment]
Sure

> 

Sure
![0 (1)](https://user-images.githubusercontent.com/114101375/210132899-e91fc2c8-59b8-4b40-8889-a2095fac53d6.jpg)
![0 (2)](https://user-images.githubusercontent.com/114101375/210132900-b0d2d3ea-de64-42db-8bcf-3cc064a654da.jpg)
![0 (3)](https://user-images.githubusercontent.com/114101375/210132901-4fed8d52-8c05-4e1a-87e8-0d7ee941d839.jpg)

**Comment by mdelobelle** [comment]
Yeah! I've noticed that too. It's really anoying. Metadata Menu and Obsidian core API are both changing the file when processing frontmatter. Sometimes obsidian gets the last update and therefore it seems to force the cursor position to the beginning of the line. 

I've tried some workaround, but still unsuccessful atm.

**Comment by toxfu** [comment]
I have the same problem. The problem doesn't appear in version 0.3.10

**Comment by mdelobelle** [comment]
This should be fixed in 0.4.5 can you confirm?

**Comment by toxfu** [comment]
No, the problem persists in 0.4.5

**Comment by mdelobelle** [comment]
could you make a screenshot of the issue please?

**Comment by toxfu** [comment]
![Obsidian_bMP8gdR4th](https://user-images.githubusercontent.com/92554009/210452971-566e7fde-16fd-4c4f-8023-7cd6f834d0f9.gif)

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by toxfu** [comment]
In this version it works fine. thanks for the hard work
