### ISSUE TITLE
add settings option to add a space between dataview inline field and metadata input by default

### ISSUE THREAD

**Issue by rushikb** [mdelobelle/metadatamenu#236]
I love this plugin, and it has dramatically improved the way I use metadata , Thank you!

for preset fields — the default option is to add the field **without** adding a space between the "::" used for dataview fields and the input— and the only way around this is to use shift+ enter. 

However, this is difficult/ not possible when using metadata menu on mobile, and adds unnecessary friction, especially when adding tags. 

Can this be changed?

**Comment by mdelobelle** [comment]
Yes sure! will be included in the next release

**Comment by mdelobelle** [comment]
shipped in 0.4.5

**Comment by rushikb** [comment]
Apologies if I'm being thick/ doing something really silly here. But i updated the plugin and restarted my system — still can't see this working. Currently using: Obsidian 1.1.9, installer version 1.1.9, plugin version. 0.4.5

Thank you again for being so responsive!

![CleanShot 2023-01-02 at 06 58 44](https://user-images.githubusercontent.com/6484525/210186889-980905ea-1e81-49ce-b500-181684d6a20a.gif)

**Comment by mdelobelle** [comment]
Oups. I forgot to change it also for autosuggest. currently, with auto suggest you have to shift+enter to put a space after the separator

**Comment by rushikb** [comment]
Got it! thank you— I should've clarified this from the beginning! This is what causes the biggest issue on mobile. Thank you again for taking a look!

**Comment by mdelobelle** [comment]
should be ok in 0.4.7
