### ISSUE TITLE
group issue

### ISSUE THREAD

**Issue by DannyHatcher-Git** [mdelobelle/metadatamenu#245]
I followed your youtube video but it still isn't working for the groups in canvas.

fileclass settings the same
group settings the same
files the same
dataview active

I am at a loss

**Comment by mdelobelle** [comment]
could you paste the content of your fileClass file ? (containing the definition of the field you'd want to be updated when moving nodes in a canvas' group)
And eventually (if no confidential data in it) a snapshot of the canvas?

**Comment by DannyHatcher-Git** [comment]
![image](https://user-images.githubusercontent.com/78496825/211009371-a1fdcb10-334c-4dff-8f58-507ef601fa29.png)

**Comment by mdelobelle** [comment]
oh crap! I've introduced a regression while fixing another issue with empty canvases. will push a hotfix right now

**Comment by DannyHatcher-Git** [comment]
all good now
