### ISSUE TITLE
FR: set "null" value default

### ISSUE THREAD

**Issue by thecookiemomma** [mdelobelle/metadatamenu#246]
Hey, it's me again.  Could we have a setting to set the default of a "null" field to 0 or blank?  The string throws off some of the other plugins' workflows.  Thanks.

**Comment by mdelobelle** [comment]
Hi! this issue has also been metionned by others : https://github.com/mdelobelle/metadatamenu/issues/233#issuecomment-1370295698

It's a core behavior of obsidian. I've asked the devs if they can improve it somehow https://discord.com/channels/686053708261228577/989603365606531104/1061219891149017119

I'm waiting for their feedback.

**Comment by toxfu** [comment]
> 

In version 0.3.10 of the plugin this does not happen. I have been using this version until the problem is fixed and it works fine

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by toxfu** [comment]
In this version it works fine. thanks for the hard work
