### ISSUE TITLE
Add an HTML class to prevent extra icon from appearing next to file link

### ISSUE THREAD

**Issue by Krakor92** [mdelobelle/metadatamenu#247]
I'm building a custom dvjs view that renders multiple file links (all of which are instances of a file class). I've made each of them fit in an icon, but the extra icons from this plugin keep appearing next to them and I haven't found a reliable/easy way to get rid of them (since I don't want to hide them in other contexts).

I've found [someone with the same problem](https://github.com/702573N/Obsidian-Tasks-Calendar/issues/43) using another dvjs view.

So imo, the best way to solve this would be to add an if check that would prevent the extra icon from being added if the file link contains a specific class name.

---

https://github.com/mdelobelle/metadatamenu/blob/1ef83549b695d88ea4df2b2659d70c69381c05f5/src/options/linkAttributes.ts#L18-L27

I've managed to do it by adding this line before the switch/case above:
```js
if (link.classList.contains("no-metamenu")) return;
```

but I'm not sure what class name would be appropriate, so I'd rather let you add it in a future version if you agree.

**Comment by mdelobelle** [comment]
released in 0.4.12

**Comment by mdelobelle** [comment]
if (link.classList.contains("metadata-menu-button-hidden")) return;
