### ISSUE TITLE
dv.current() seem to not work in Dataview Query (optional) in the "link" type setting

### ISSUE THREAD

**Issue by YoungChan404** [mdelobelle/metadatamenu#252]
Thanks for your magical plugin. I have a problem when using the "link" type field. I want to get files(links) directly related to the current page where the "link" field is added. However, the dv.current() seem to not  work for me. The following is my code:
dv.pages("#Group/Project/task").where(p => p.father_project===dv.current().father_project)
Basicly, I want to get all the task files within the same project of the current page. The field "father_project" and its value has been already written in the task files in the yaml.
Any suggestions? Thanks a lot again.

**Comment by mdelobelle** [comment]
Hi. you can use "current" variable that is set to be `dv.current()`
More details on the documentation https://mdelobelle.github.io/metadatamenu/settings/#file-multifile-options

**Comment by YoungChan404** [comment]
It works now. Thank you.
