### ISSUE TITLE
FR & Bug: Front matter can auto modifiy the style. 

### ISSUE THREAD

**Issue by YIRU69** [mdelobelle/metadatamenu#253]
Hi, firstly appreciate thank to you work for the plugin>
I don't remember what the plugin vision could cause the fron matter reload and the style broken.
Say what I happen when I use it.

When I want to change or add tags, the plugin can help me auto complement. When I use it, it broken my yaml style can rewrite all yaml string style. 

Look at the bottom pic, my fist tag disapper. It is not all problem, it also can cause change the other yaml style and auto complement "null". 
So what I want? I just want it don't change my yaml style, only auto complement the string like tags. You know I have often use a plugin like linter. Could you change the strategy or give a setting on the plugin to choose it.

Before
![image](https://user-images.githubusercontent.com/48148292/211492695-1e80a892-54bb-4251-ad31-bb65a1f8f9d4.png)
Using
![image](https://user-images.githubusercontent.com/48148292/211492859-1e5944f2-09b1-47f9-9315-c1f6387807e2.png)
After
![image](https://user-images.githubusercontent.com/48148292/211492951-620337f8-a2d1-4e92-81f3-be15ca791f1b.png)

**Comment by YIRU69** [comment]
Add note: When I choose fileClass auto complement, it also change my front matter style. Please change it!

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by YIRU69** [comment]
Thank you and happy new year!
