### ISSUE TITLE
Add option to disable autocomplete

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [mdelobelle/metadatamenu#256]
There are currently at least 3 other autocomplete plugins for tags in the frontmatter. Not only is this one currently bugged for me (#257), but considering that fact it should be a setting to disable autocompletion from this plugin.

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by mdelobelle** [comment]
I'll close this issue, don't hesitate to make feedbacks if it's not working as expected
