### ISSUE TITLE
Autocomplete is buggy

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [mdelobelle/metadatamenu#257]
I can't get this to happen reliably, but frequently when I hit enter it obliterates the existing text and fills only the remaining text on the following line
![MetaBug](https://user-images.githubusercontent.com/31261158/212841938-e30348c8-094b-4f01-bcc8-a80534104820.gif)

**Comment by AtlcatlQ** [comment]
I have the same Issues

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by AtlcatlQ** [comment]
It's working to me now, Thanks
