### ISSUE TITLE
updating frontmatter not working

### ISSUE THREAD

**Issue by menagerie198** [mdelobelle/metadatamenu#264]
With 0.4.11 and 0.4.12 clicking on the icon in the tab, for updating frontmatter no longer works when I update the field: values. Rolling back to v0.4.10 restores this function.
I realise this is not very clear, so here is a pic, that might help clarify what I am talking about...
![image](https://user-images.githubusercontent.com/7330436/213882717-c483766d-d04b-4726-aba9-5bc633501b06.png)

**Comment by mdelobelle** [comment]
good catch. should be fixed in 0.4.13

**Comment by menagerie198** [comment]
Working as expected with 0.4.13. Many thanks
