### ISSUE TITLE
Autocomplete is inserting space between double colons

### ISSUE THREAD

**Issue by tbogdal** [mdelobelle/metadatamenu#266]
Just updated from 0.4.9 to latest version 0.4.15 and started having autocompletion problems.

For a field written like so:
```
Field:: 
```
The autocomplete would enter an extra space between the collons, like so:

```
Field: :
```
That specific field has been setup to be a multi-file field. Not sure what triggers the issue, but will add that I had some metadata place in a callout like so:

```
> [!note] My Callout
>
> Field:: 
```

As a temporary solution I downgrade to 0.4.10, and the issue got resolved. I tried 0.4.11 and the issue started popping up again.

As a side note, I noted that not all field had autocomplete working (when a Dataview query is assigned). Some field I have setup via a global fileClass and some are tag specific. It's a little bit annoying, btw I am running version 0.4.10 and have this side issue.

**Comment by tbogdal** [comment]
As a temporary solution to the issue relating to global fileClass, I have manually added **Parent fileClass** to each fileClass.

This works for me:
![image](https://user-images.githubusercontent.com/53819365/214524228-367c5fc4-79d3-43f6-8260-18bc397401f7.png)

While the following stopped working:
![image](https://user-images.githubusercontent.com/53819365/214524317-582b4253-46c3-4fb5-8030-737ab2faabbf.png)

**Comment by senged** [comment]
@tbogdal thanks for sharing, same issue for me. Can you please share how you downgrade to previous version?

**Comment by puertoric** [comment]
I have the same issue with autocomplete. In my case I found out that adding three dashes (but not with front matter) triggers this behavior. When I delete any three dashes (which I use to separate sections in my notes) then the autocomplete issue does not appear.

**Comment by mdelobelle** [comment]
good catch. Should be ok with 0.4.16.

**Comment by puertoric** [comment]
Thanks for the quick update. It works now again in my case. Great work!
