### ISSUE TITLE
[Bug] FileClass file defining properties doesn't work

### ISSUE THREAD

**Issue by cogscides** [mdelobelle/metadatamenu#27]
FileClass file defining properties doesn't work on my setup. Tested on two vaults:

environment
![image](https://user-images.githubusercontent.com/50235526/181091552-56d29264-acf5-44e2-9bf0-7620db57b059.png)

settings
![image](https://user-images.githubusercontent.com/50235526/181091610-78e1679d-7879-4aea-8a8b-60fe0f7e91d7.png)

**Comment by mdelobelle** [comment]
Hello,

can you try to put a trailing slash in your settings for class Files path like that `fileClasses/`
I think this should solve your problem

If that's the case I may improve this settings by having the plugin inserting a trailing slash itself if the user hasn't

**Comment by cogscides** [comment]
@mdelobelle It's working, thank you!
