### ISSUE TITLE
Cannot modify column width

### ISSUE THREAD

**Issue by SaintAlexTheSleepy** [mdelobelle/metadatamenu#270]
Not sure if I'm missing something in the documentation, but I can't edit the column width to fit to the text in each cell.

**Comment by mdelobelle** [comment]
Where are you trying to modify the column width?

**Comment by SaintAlexTheSleepy** [comment]
I was trying to modify like an excel table, just dragging the edge.
![image](https://user-images.githubusercontent.com/74139630/214965765-4c1cae69-b7ec-4bb8-8f29-22c74d8e676e.png)

**Comment by mdelobelle** [comment]
Hi the two sections are independent. Hence the difficulty to have the same width for columns at the moment. I'm not sure I'll be able to fix it
