### ISSUE TITLE
Autocomlete is inserting single values from list as array

### ISSUE THREAD

**Issue by PhyberApex** [mdelobelle/metadatamenu#271]
With the most recent version available from the obsidian store, every time I let autocomplete fill one field that has "Accept a single value from a list" it inserts it as a yaml list with one entry and allows me to do multiple entries. It also asks me for the list style which makes no sense for a single select.

~ Cheers

**Comment by mdelobelle** [comment]
Thanks. this will be released in the next version

**Comment by mdelobelle** [comment]
this should be fixed now
