### ISSUE TITLE
[FR] Define input type in Dataviewjs code block

### ISSUE THREAD

**Issue by Pachtjuilaard** [mdelobelle/metadatamenu#273]
I'd like to state which input type should be used for a row of data in the Dataviewjs code block, instead of having to use templates for this. Maybe something like:

await f(dv, b, "hp", {input: number}, {options: {alwaysOn: true}})

**Comment by mdelobelle** [comment]
Hi, I think I can't do that. It would lead to integrity issue in some cases.

For example if you define 
await f(dv, b, "hp", {input: number}, {options: {alwaysOn: true}})
in a dataviewjs block

and 
await f(dv, b, "hp", {input: date}, {options: {alwaysOn: true}})
in another dataviewjs block that would trigger the same files as the first one

then the data could be corrupted
