### ISSUE TITLE
Feature: add <any value> inline field from selection

### ISSUE THREAD

**Issue by maggaou** [mdelobelle/metadatamenu#277]
New context menu command: add <any value> inline field from selection.

This command opens pop up selection similar to "Add field at cursor" but filtered only for input-type fields.

**Comment by mdelobelle** [comment]
do you mean that it should search for a matching field in the fileclass definition, or create a new field with the selected text as name?

**Comment by maggaou** [comment]
> do you mean that it should search for a matching field in the fileclass definition, or create a new field with the selected text as name?

I'm not sure if I thought this feature thoroughly if fileclasses are used. Because fileclasses help to construct yaml fields efficiently. I'm not familiar with using fileclasses, so you should think yourself if this feature is useful in case of the user utilize fileclasses. 

Maybe there are successful workflows that don't utilize fileclasses (I'm not sure about it). In case of that, my feature enhances making inline fields quickly. 

Currently my Metadata Menu is not working properly (Obsidian 1.3.5, mac ventura 13.0, Apple M2).I cannot see command to Add field at cursor. I see only Metadata Menu: field options and Metadata Menu: fileClass attributes options.

What was my original workflow:

Write sentences in language learning and then mark them somehow for later reference. This could be achieved several ways, like separating sentences by newline and then writing tag to the line. Or one could use some QuickAdd script (or Templater) to append the selection to some file (not very easy thing to do). Obviously the most elegant way is to make an inline field of the selection so that the selection itself is used as a value. Then there should be options to select previously used fields as field name (or to create new field name). 

One could store content for later reference by using links. This can be done by [[my reference | my content]]. This involves manual typing and I'm not sure how to query that content to my reference. Also there is possibility to use note blocks in the note you are editing, and then in your reference note make links to these note blocks. I think that is also very tedious work. 

One more solution: separate sentences by newline and then add separate link to the source. There could be several links. Then later query these lines that include certain link. The only bad thing here is that sentences are separated by new lines, making the text fragmented. But maybe one could use regular expressions to query content between {}. Then one could query text of the form {my text} ... links ... [[my link]]. 

Conclusion: I think data query fields offer easy way to find well defined objects. But in my case one sentence can belong to many categories. What is the most elegant way to classify text in a note that belongs to multiple categories. Could there be some new operator that assigns a value to multiple fields simultaneously or something completely different?

**Comment by mdelobelle** [comment]
I could start with a new « set as field value » command where the selected string "xyz" would be wrapped in a (fieldName:: xyz) or [fieldname::xyz]

A "full line" would be prefixed : 

fieldName:: full line

**Comment by maggaou** [comment]
I'm not sure if inline fields are as effective as I thought previously. But if you believe in them then go for making them better. 

Alternate workflow is to just capture selections to new notes and then use note-specific metadata for organization. When I think about that, it makes me wonder do you need inline metadata for anything.
