### ISSUE TITLE
Lookup not working

### ISSUE THREAD

**Issue by DannyHatcher-Git** [mdelobelle/metadatamenu#278]
I have followed your video and the lookup isn't working.

My lookup 
![image](https://user-images.githubusercontent.com/78496825/216636505-984272a5-097a-4051-a00e-61afa63cc3e6.png)

The note
![image](https://user-images.githubusercontent.com/78496825/216636599-074d1b1a-6e0c-4248-8422-a26148ff4010.png)

The result
![image](https://user-images.githubusercontent.com/78496825/216636663-8f91b883-8bee-4206-887b-af9f06129604.png)

**Comment by mdelobelle** [comment]
Hi!
the "Note" field can only contain links
example: 
if the note containing the "Lookup" field in named "My Note.md", 
put "Note:: [[My Note]]" in Danny.md
then [[Danny]] should appear in the field "Lookup" of "My Note"

**Comment by DannyHatcher-Git** [comment]
oh because it lists the links displayed?

**Comment by mdelobelle** [comment]
In its most simple "type of output" yes
but you can use "Custom list rendering function displayed inline" to display values of OTHER fields in the "Danny" note

for example
if "Danny.md" contains
```
Note:: [[My Note]]
Location:: Mars
```

and if you set `Type of output` to `Custom list rendering function displayed inline`
and then set `Query's results list rendering function`to 
```
page.Value
```

then "My Note.md" should contain `Lookup:: [Mars]`

**Comment by DannyHatcher-Git** [comment]
I cannot get the lookup field to work.

Do you have a video showing this?

**Comment by DannyHatcher-Git** [comment]
> 

I have tried this over and over and it doesn't work. I am missing something.

What I am doing:
"Source 1" has the lookup field
In "Danny" file I have a filed called "Written" with "Source 1"

Inside the lookup I have:
dv.pages('"Author"') 
The Danny page is in that folder

The related field is Written
List of related links displayed inline

And it shows nothing.
