### ISSUE TITLE
Dataview List help

### ISSUE THREAD

**Issue by DannyHatcher-Git** [mdelobelle/metadatamenu#279]
I have a field "Lecturer" in my #lecture files.

My goal is to get the Lecturer field to look for other lecturers as a multiple list option through a dataview query.

This is what I am using with no luck.

dv.pages("#Lecture").map(p=>p.Lecturer)

**Comment by Krakor92** [comment]
What type of field is `Lecturer`? Is it a `MultiFile` (contains [[links]]) or a `Multi` (contains strings)?

If it's the former, then your query should be fine and the suggester should show you the links you've already put in other `Lecturer::` fields... does it show anything in the devtools console?

If it is the second case, then the query should be changed to:

```
dv.pages("#Lecture").Lecturer.distinct()
```
---

I know it is tedious to have two different syntaxes depending on the context. I guess I should modify ListBasedField to support the same .map function syntax as FileBasedField...
