### ISSUE TITLE
[FR, maybe Bug] Can we collapse filters?  

### ISSUE THREAD

**Issue by thecookiemomma** [mdelobelle/metadatamenu#280]
I have lots of fields in my daily notes:  
![image](https://user-images.githubusercontent.com/15720918/217387800-162e0d10-8925-47fe-a245-ab4c18461539.png)

I would like to be able to open and collapse the filters so I can see content.  Thank you.

**Comment by mdelobelle** [comment]
Hi, this is available in 0.4.21

**Comment by thecookiemomma** [comment]
Thank you so much! It makes it so much more useful.
