### ISSUE TITLE
Metadata Menu Removes Quotemarks--breaks metadata

### ISSUE THREAD

**Issue by JaySpencer1234** [mdelobelle/metadatamenu#281]
So:
- I am using the plugin icon shortcodes to place emojis in my daily notes
- I have a Fileclass that has a bunch of fields defined
- Several of these fields refer to a note I call "check."
- All it is is this: ":luc_check_circle_2:"
   - The quotes are included in the file
- Last December (when I last wrote in my journal...) I could click on the define field icon and hit enter and it would past the Check file with the quotations
- Now when I do the same thing it removes the quotation marks and makes the YAML invalid because of the colon (:).
- At some point in the last 4 months, something changed that made Metadatamenu remove quotation marks when pasting from a file or from the Fileclass field itself.

Expected Behavior:
1. Open note
2. Press ctr + ; (My hotkey to open up the Fileclass menu)
3. Click the define fields button next to the filed I want to complete.
4. Hit enter to submit the option
5. Keep calm and carry on

Recent Behavior
1. Open note
2. Press ctr + ; (My hotkey to open up the Fileclass menu)
3. Click the define fields button next to the filed I want to complete.
4. Hit enter to submit the option
5. Brick the YAML, the Fileclass disassociates and note goes back to the "basic" File Class

Current Workaround:
Exit the menu and manually add quote marks to the field. Only after doing that you can continue using the plugin.

How can I fix this?
-Jay

I have attached the relevant files:
[Daily Note Template.md](https://github.com/mdelobelle/metadatamenu/files/10680151/Daily.Note.Template.md) 
   (The actual template)
[Daily.md](https://github.com/mdelobelle/metadatamenu/files/10680152/Daily.md) 
   (the Fileclass)
[Check.md](https://github.com/mdelobelle/metadatamenu/files/10680153/Check.md) 
   (the check note I mentioned)

**Comment by mdelobelle** [comment]
The values parsing has been reworked. Donyou still have the issue?

**Comment by mdelobelle** [comment]
Since Obsidian is reformatting the strings in the Yaml section, the way to achieved your goal is to encapsulate your string in single quote: `'":luc_check_circle_2:"'`
