### ISSUE TITLE
Values returned from Dataview query?

### ISSUE THREAD

**Issue by BarryBurton57** [mdelobelle/metadatamenu#284]
Hi there,

I'm not familiar with dataviewjs, but have a bit of experience with standard dataview. So, I'm trying to source values from the dataview query option. 

In the dataview function input, I'm guessing I can't simply add a standard dataview query here? 
<img width="561" alt="CleanShot 2023-02-11 at 21 24 52@2x" src="https://user-images.githubusercontent.com/123518382/218281867-8438c159-7a5c-4f34-bb5a-68c2db68ca0a.png">

I've tried the dataviewjs code also, but no joy.

Essentially, what I'm trying to do is make a list of values that are notes with the tag 'module'...

Apologies, I couldn't find a simple example like this in the docs.

Thanks for a great plugin by the way!!!

**Comment by dxcore35** [comment]
Check this! It works https://github.com/mdelobelle/metadatamenu/issues/274

**Comment by BarryBurton57** [comment]
Thanks for the reply. 

I don't know how to write js, was hoping this could be achieved with a standard dataview query. If not, how would one write this to simply return notes with a specific '#'/'tag'?

**Comment by dxcore35** [comment]
```
dv.pages("#your-tag")
.tags
.distinct()
```

**Comment by BarryBurton57** [comment]
Thanks, that seems to be closer. However, it's returning the specific tag name (e.g. "your-tag") as an option to choose. I was hoping to list pages/notes with `tag = "your-tag"`

So, it would be something like - 
- [[Note A]] (has "your-tag")
- [[Note C]] (has "your-tag")

Is this possible?

**Comment by dxcore35** [comment]
Im sorry I don't understand what you need. If you want to get "your-tag" then my query is correct. If you want list of all tags then:

```
dv.pages("")
.tags
.distinct()
```

**Comment by Krakor92** [comment]
You should replace the field type to `Accept a Link` and use this dvjs query instead:

```js
dv.pages("your-tag")
```

**Comment by BarryBurton57** [comment]
> You should replace the field type to `Accept a Link` and use this dvjs query instead:
> 
> ```js
> dv.pages("#your-tag")
> ```

Thanks, I now get a list of notes (which is want I want), but it is not respecting "#your-tag" piece - i.e. it is returning all notes in a list. 

I've double checked the name of the tag is correct etc.

<img width="509" alt="CleanShot 2023-02-17 at 19 12 51@2x" src="https://user-images.githubusercontent.com/123518382/219765806-30bf9d7e-0c27-45d6-8937-168ce2caf7d1.png">

**Comment by chaecramb** [comment]
I'm getting the same issue. With Field type set to `Accept a link`, and a Dataview query of:

```js
dv.pages("#Translator")
```

The resulting list is populated with all pages as options, not only those tagged with `Translator`.

Any suggestions?

**Comment by Krakor92** [comment]
I can't reproduce it unfortunately 😕 it's really weird...

May I know what version of dataview and metadatamenu you are using?
Also, in which version is your application and what is your operating system?

**Comment by chaecramb** [comment]
I discovered my problem...I just needed to turn on `Enable Inline JavaScript Queries` in Dataview, which is off by default when first installed. 

@BarryBurton57 I guess there's a good chance that should solve your issue as well, if you're still having the same problem.

**Comment by Krakor92** [comment]
Nice catch 👏. @mdelobelle It might be a good idea to update the code responsible to show and the notice that appears when dataview javascript requests are not enabled. 

Maybe telling the user to enable "dataviewJS AND inline dataviewJS"?

**Comment by BarryBurton57** [comment]
> I discovered my problem...I just needed to turn on `Enable Inline JavaScript Queries` in Dataview, which is off by default when first installed.
> 
> Thanks for investigating @Krakor92
> 
> @BarryBurton57 I guess there's a good chance that should solve your issue as well, if you're still having the same problem.

Yes, this resolved my issue! I had js turned on, but not the inline also. Many thanks!

On a related note, how does one exclude the fileClass note from the list that now displays? So, I have a list of module notes now, but the list also includes the fileClass note (assignment) as it appears this has the "#module" tag in the dv query on that note(?)

**Comment by Krakor92** [comment]
Just exclude the folder where your fileClass is located from your query.

From `dv.pages("#your-tag")` to `dv.pages('#your-tag AND -"path/to/your/classes"')

**Comment by BarryBurton57** [comment]
Thanks you! All good now, cheers!
