### ISSUE TITLE
Mobile: still on version 0.0.1 instead of the latest

### ISSUE THREAD

**Issue by systephan27** [mdelobelle/metadatamenu#286]
Could we also have the latest version on the mobile (esp. for those working on iPads) aswell please? :-) Really like the concept of this plugin!

**Comment by mdelobelle** [comment]
The latest version is always available on mobile and desktop. There should be no difference.
Maybe try to remove and reinstall the plugin to fix this?

**Comment by systephan27** [comment]
Thanks for your reply. I checked both on the iPad and iPhone under community plugins. Unfortunatelt, it still shows version 0.0.1.
![844C53A1-855E-4978-B7A4-F773897036A7](https://user-images.githubusercontent.com/125285095/219885233-81aea5d2-bfbe-4d19-b40d-6eafae4bf656.jpeg)

**Comment by mdelobelle** [comment]
I haven't been able to reproduce this issue. Is it still the case?

**Comment by Krakor92** [comment]
Yes it's still the case, I've noticed the same problem on all my devices (Android Phone, iPad and Linux Laptop). I'm on Obsidian 1.3.5 and just to make sure, I've created a vault from scratch on my laptop and got the same issue.

Though I think I've found the root of the problem but I'm only speculating as I'm not a plugin developer. When I compared your repository with others (like dataview for example), I found that your [`versions.json`](https://github.com/mdelobelle/metadatamenu/blob/master/versions.json) file is not granular enough:

As I said earlier, all my devices have Obsidian installed with an API equal to or lower than version 1.3.5. As your plugin's version.json file doesn't provide a version corresponding to the version of my API, it automatically falls back on the first available version: `0.0.1: "0.15.3"` in this case.

**Comment by eddiecooro** [comment]
I'm having the same issue. The latest version is not available in the obsidian plugins.
![image](https://github.com/mdelobelle/metadatamenu/assets/20463083/490f4655-4ee5-4055-83a5-22f650e05c18)

Also, it doesn't seem to be only a matter of version number. The functionallity is missing.
Here are the options after installing the plugin:
![image](https://github.com/mdelobelle/metadatamenu/assets/20463083/1516117b-a721-4649-af05-7d6a2c24dc49)
