### ISSUE TITLE
Canvas links in inline fields

### ISSUE THREAD

**Issue by EMBuwel** [mdelobelle/metadatamenu#287]
Hello !

I am trying to add links in the text of a note based on it's links with other notes in a Canvas. It is possible thanks to Metadata Menu and fileClass, thanks a lot !

However, is it possible for the Field automatically updated to be inline ? The idea is for the link to be place on a specific part of the note, not the frontmatter.

Thanks for your help !

**Comment by mdelobelle** [comment]
Hi, the frontmatter is the default location for canvas field but you can place them "inline" with a template or move them from frontmatter to "inline" afterwards (don't forget the "::")

**Comment by EMBuwel** [comment]
Hello,

Thank you for your answer ! 

By placing the metadata:: directly on my template, indeed it is not inserted in the frontmatter. So it weems to work as intended, many thanks !
