### ISSUE TITLE
postValue API call not working

### ISSUE THREAD

**Issue by RicSanOP** [mdelobelle/metadatamenu#288]
I was trying to use the metadatamenu api within a quickadd JS script in order to select a value that will be updated on multiple fields (some inline, some yaml). Here is the general flow of my code:

```
// Some QuickAdd API calls to select note and options beforehand
        const mm = app.plugins.plugins["metadata-menu"].api
        const fields = await mm.fileFields(file)
// Do some stuff to determine what should be posted
        const mmPayload = [
            { name: 'fieldYaml1', payload: { value: `blablabla1` } },
            { name: 'fieldInline2', payload: { value: `blablabla2` } },
            { name: 'filedInline3', payload: { value: `blablabla3` } },
        ]
        await mm.postValues(file, mmPayload)
```

Unfortunately, although I am certain that the file is read and that payload is read and parsed out of the document (I stepped through the postValue function in debugger), the metadata edits don't seem to take effect. I am not sure as to what could be the problem or why. Please provide some guidance on debugging and resolving the issue.

**Comment by RicSanOP** [comment]
I am not sure why, but it is now working. Could this have to do with whether the file is open or not? What other factors could affect this?

**Comment by erauner12** [comment]
not sure if this is helpful, but the following works for me. It's still pretty fresh as I've just introduced it yesterday:

```
    const { fileFields } = app.plugins.plugins["metadata-menu"].api;
    const { postValues } = app.plugins.plugins["metadata-menu"].api;
    const activeFile = params.app.workspace.getActiveFile();

    const getCurrentProperty = async (file, yamlKey) => {
        var currentFields = await fileFields(file)
        var currentValue = currentFields[yamlKey]["value"]
        // console.log(currentValue)
        return currentValue
    }

    const changeProject = async (file, yamlKey, newValue) => {
        var currentFields = await fileFields(activeFile, yamlKey)
        var currentValue = currentFields[yamlKey]["value"]
       
        var fieldsPayload = [
            {
                name: yamlKey,
                payload: {
                    value: newValue
                }
            },
        ];
        postValues(file, fieldsPayload)
    }
```

**Comment by RicSanOP** [comment]
Thank you for sharing. I somehow got my code to work without knowing
exactly what caused my issue in the first place. I just feel that
programmatically editing files in Obsidian can be buggy (especially if you
are making edits using several different plugins/apis/methods).

I am curious as to why you are creating assigned anonymous functions to use
the API and what your application usecase is, if you are willing to share.

**Comment by mdelobelle** [comment]
> I just feel that
programmatically editing files in Obsidian can be buggy (especially if you
are making edits using several different plugins/apis/methods).

You're absolutely right. I have hard times managing the concurrency between obsidian, dataview and metadata-menu updating their cache. Obsidian cache updating is espacially opaque and sometimes lagging a little behind in my experience. 

The new core method introduced by obsidian team "processFrontmatter" handles that better, but it has a significant drawback IMO: it rewrites the whole frontmatter, breaking the user's layout (forcing inline array lists into indented lists). That's the reason why I stick with my own method for the moment
