### ISSUE TITLE
Can't access buttons on the right

### ISSUE THREAD

**Issue by Asetnozama** [mdelobelle/metadatamenu#289]
Hello,
On mobile it's not possible the change the fields, because it doesn't display the buttons on the right like on desktop. See attached image. 
![image](https://user-images.githubusercontent.com/102867794/219572866-e8ec9860-d5fb-4835-87d3-ff512e1ce6aa.jpeg)

**Comment by mdelobelle** [comment]
Hi, can you try with version 0.4.20?

**Comment by Asetnozama** [comment]
It's still the same

**Comment by M1chael910** [comment]
I have the same issue, Any updates?

**Comment by StefanoRausch** [comment]
Same here: I started to use MDM and I love it! However, on an iPhone X, I need to rotate to landscape for accessing the controls.

**Comment by mdelobelle** [comment]
I'm not able to reproduce it on my Iphone 12. Could you give me the width of your display? (you can use an online tool to find it like whatismyscreenresolution.net

**Comment by StefanoRausch** [comment]
I have an iPhone X Max:

- Portrait screen resolution: 414 px width x 896 px height

I will post a screenshot to show what it looks like.

**Comment by mdelobelle** [comment]
This should be fixed, can you confirm?
