### ISSUE TITLE
[BUG] Problem with multiples formulas in fileClass

### ISSUE THREAD

**Issue by toxfu** [mdelobelle/metadatamenu#290]
when I establish 2 formulas for the same fileclass the behavior is not adequate. It either gets hung up, not doing the calculations or it also starts a loop between or and the result. Also makes obsidian freeze

**Comment by DannyHatcher-Git** [comment]
I am not sure if this is related but I can't reference a formula propery in a formula property.

My thinking was that once the value has been added to the file, the second formula would use that value and update itself.

This doesn't seem to work.

**Comment by mdelobelle** [comment]
this should be ok in v0.6.0
