### ISSUE TITLE
[Feature] Edit existing yaml frontmatter field's name.

### ISSUE THREAD

**Issue by ertugruluyar-github** [mdelobelle/metadatamenu#291]
---
nam: Frank
---

Think that there is a bunch of files that include this yaml field. In this situation, I want to change "nam:" to "name:" but  I didn't find a feature that exist in this plugin.

I could change the name of the field in fileclass' settings, but it doesn't change the files that include this field.

**Comment by mdelobelle** [comment]
Hi, renaming fields isn't in the scope of this plugin.
You could do this with a text editor such as VSCode for example : it has strong search and replace capabilities (that's what i'm using currently)

**Comment by ertugruluyar-github** [comment]
I am aware of VSCode search replace function but thank you. I mean this plugin is about metadata and I think that this should be in this plugin's scope. Because, I use this plugin for my academic research and analysing this data. So, I have lots of page and metadata. Therefore, I have to change the metadata name sometimes. 
Thank you very much because this plugin so helpful for me.

**Comment by carllx** [comment]
I fully support the viewpoint expressed by @ertugruluyar-github . While I understand that the requested feature might currently fall outside the scope of this plugin, I'd like to emphasize the significance of embracing a more object-oriented approach within Obsidian, especially considering the superior functionality provided by Supertags in Tana.


The capacity to seamlessly modify YAML frontmatter fields across multiple notes not only complements the principles of object-oriented programming and design, but it also aligns with the overall flexibility and adaptability that users seek. In an application embracing object-oriented principles, the ability to define and modify specific attributes for individual notes is essential for better reflecting the real entities and concepts represented within those notes.
