### ISSUE TITLE
Cycling through values from list is broken in my setup - offers only first option

### ISSUE THREAD

**Issue by kimmoo** [mdelobelle/metadatamenu#292]
Hi,

I have a (simple?) Obsidian setup that I believe to be up to date.

---------------
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64 19.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Metadata Menu v0.4.21
		2: Dataview v0.5.55

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

---------------

In the gif below I try to show a situation where I only get the first option again and again.

![CleanShot 2023-02-18 at 19 10 50](https://user-images.githubusercontent.com/4725324/219879144-3b44d552-841c-43ac-80fe-4c32be829425.gif)

**Comment by mdelobelle** [comment]
good catch. will be fixed in the next release
