### ISSUE TITLE
Misplaced comma.

### ISSUE THREAD

**Issue by willasm** [mdelobelle/metadatamenu#294]
https://github.com/mdelobelle/metadatamenu/blob/31ae628faa06caf6dbd616d9d7091de8c8619da8/src/commands/postValues.ts#L127

This should be `newContent.push(`${fieldName}: [${newValue.join(", ")}]`);`

The comma should come after the preceding word, not right before the following word.
Not a big deal as it does not break anything but it does look odd.

Eg. `[tag1 ,tag2 ,tag3 ,tag4]` when it should be, `[tag1, tag2, tag3, tag4]`

**Comment by mdelobelle** [comment]
good catch, will be fixed in the next release
