### ISSUE TITLE
[FR] Table View - Image Support

### ISSUE THREAD

**Issue by yurijserrano** [mdelobelle/metadatamenu#298]
Good Evening @mdelobelle 

I've noted that the metadatamenu does not support displaying images on the Table View.

I think this would be useful, and it would help not just me but other users to cover more scenarios.

This feature was included in the DBFolder plugin, and you can see it in the link right below:

**[LINK](https://github.com/RafaelGB/obsidian-db-folder/issues/298)**

If you need any further clarification, please let me know.

I wish you a wonderful day

**Comment by mdelobelle** [comment]
This is now possible with the recent addition of "Media" and "MultiMedia" field types
