### ISSUE TITLE
Can't trigger autocomplete

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#3]
Not sure what I'm doing wrong or if it's broken. 

Tried "::" in frontmatter and ":::" in an inline field.

**Comment by mdelobelle** [comment]
Can you confirm that you currently have the 0.0.5 version installed?

Do you see any error message in the console (alt+command+i on mac)?

**Comment by arminta7** [comment]
I do have 0.0.5 installed. 

I do not see any errors for that plugin in the console.

**Comment by mdelobelle** [comment]
I've experienced something similar right now on one of my vault.
I've disabled then enabled again the plugin (without removing it) and the suggestor worked again.
Can you try it?

**Comment by arminta7** [comment]
I think I found the issue! I disabled the Various Compliments plugin and now it works!

**Comment by mdelobelle** [comment]
Ok thank you for the report, I'll add a "know issues" section in the read.me file
