### ISSUE TITLE
Fields in list support

### ISSUE THREAD

**Issue by subhinay** [mdelobelle/metadatamenu#30]
I don't know whether this will fall under a bug or is it a new feature request, but here it is:

I have:
```
- Type:: [[whatever]]
- Category:: [[whathaveyou]]
```
and so on.

Thing is, Property Manager won't let me have `- Type` as an option. And they aren't recognized automatically either.

I am using lists because:
- I don't want to use YAML.
- I use Markdown's double space as new line option as it is more [CommonMark ](https://spec.commonmark.org/0.30/#hard-line-breaks) compliant. I will have to leave double space after every meta field.
    - Lists are more aesthetically pleasing.

**Comment by mdelobelle** [comment]
closed with #47
