### ISSUE TITLE
[BUG] Fields with emojis are not recognised

### ISSUE THREAD

**Issue by OmniNaut** [mdelobelle/metadatamenu#300]
Problem:
When trying to setup fileclass fields with emojis I notice that the plugin does not recognise it as a field.
In the example here, Mental is accepted as a field, where as 🚹Physical is not.

![image](https://user-images.githubusercontent.com/110312864/222343111-a69fbfb9-76b0-4699-90ba-d78d5a82ac4b.png)
![image](https://user-images.githubusercontent.com/110312864/222343296-d2aaf892-eb41-4294-9bc0-712cf357b5a0.png)

Expected result:
A field with an emoji is accepted by the plugin.

**Comment by Krakor92** [comment]
It's a known issue: https://github.com/mdelobelle/metadatamenu/issues/172

Since it's on Dataview's side, this plugin can't do much unfortunately
