### ISSUE TITLE
Nested callouts breaks editing

### ISSUE THREAD

**Issue by jpbruckler** [mdelobelle/metadatamenu#303]
Using nested callouts seems to cause issues with updating fields or triggering autocomplete suggestions. I've tested this with text, file, and number fields using both the right-click context menu and the table view. The modal comes up and data can be entered/selected, but the data is not written to/updated within the note itself.

I admit this is likely an edge case, but wanted to raise it. No errors are being emitted in the console.

Works as expected:

```
>[!info]
> - workPhone::
```

Field is not updated via UI, no autocomplete, etc:

```
>[!multi-column]
>
>>[!info]
>>- workPhone:: 
```

**Comment by mdelobelle** [comment]
good catch. this will be fixed in the next release
