### ISSUE TITLE
cannot convert undefined or null to object

### ISSUE THREAD

**Issue by nousernameavailableanymore** [mdelobelle/metadatamenu#305]
For me, metadata menu seems to be super buggy when used with fileclasses.
Sometimes notes with the correct tag are not "detected" at all to have a file class (despite the tag being set), sometimes it only shows the icon in the tab bar but not in the file explorer and today it even removed half of the fields for a file class.

At the moment, I get this error when opening one of my file classes:
![image](https://user-images.githubusercontent.com/45376324/226442163-4e8bea4e-5438-4cfa-b78d-c107a0787846.png)

The configuration looks like this:
```
---
mapWithTag: true
limit: 100
icon: clipboard-list
tagNames: 
excludes: 
extends: 
version: 5
---


wer:: {"type":"Multi","options":{"valuesList":{},"sourceType":"ValuesListNotePath","valuesListNotePath":"OBSIDIAN/00 Functional/Metadata Menu/wer.md","valuesFromDVQuery":""},"display":"asList"}

wo:: {"type":"Select","options":{"valuesList":{},"sourceType":"ValuesListNotePath","valuesListNotePath":"OBSIDIAN/00 Functional/Metadata Menu/wo.md","valuesFromDVQuery":""}}

behandlung:: {"type":"Multi","options":{"valuesList":{},"sourceType":"ValuesListNotePath","valuesListNotePath":"OBSIDIAN/00 Functional/Metadata Menu/behandlung.md","valuesFromDVQuery":""},"display":"asList"}
wieviel:: {"type":"Input","options":{}}

```

I have several notes with a certain tag.
All of the (tested) notes, have the "correct" menu when clicking on the icon, EXCEPT for one note (the latest one, created today), which only seems to have a subset of settings when clicking on the menu and which is also missing the bottom part with the "+" icon.

I have the latest metadata menu and Obsidian version (I just now re-installed it with 1.1.16 just to make sure).

Any clues on how to solve the current issue and improve consistency alltogether?

Thank you.

**Comment by mdelobelle** [comment]
what is the name of the fileClass?
Can you also provide a sample of the content of the note "OBSIDIAN/00 Functional/Metadata Menu/wer.md"?

**Comment by mdelobelle** [comment]
I'm closing it since the fileClass code has been rewritten quite a long time ago. Don't hesitate to file a new bug if necessary
