### ISSUE TITLE
Missing Metadata Menu Button

### ISSUE THREAD

**Issue by zcysxy** [mdelobelle/metadatamenu#311]
Hi, the Metadata Menu Button seems gone. I also tested in the sandbox vault.

**Comment by mblazeny** [comment]
I too experience the same issue, the button "Manage Fields" is not present in the settings. I use Obsidian v1.1.16 and Metadata Menu v0.4.21 and I use Ubuntu 20.04.

**Comment by ribber** [comment]
I too，and I use Obsidian v1.1.16 and Metadata Menu v0.4.21 and I use Win11

**Comment by ribber** [comment]
Sorry，When I use FileClass，I See the button. This feature must be used together with FileClass

**Comment by zcysxy** [comment]
> Sorry，When I use FileClass，I See the button. This feature must be used together with FileClass

Yeah I also noticed the issue is FileClass. I use a different field name, so I need to change it in the setting to make the icon appear.
