### ISSUE TITLE
Bug? with Metadata menu plugin and Dataviewjs dv.view()

### ISSUE THREAD

**Issue by A-Communist** [mdelobelle/metadatamenu#334]
### What happened?

I don't know if it is a bug really.

For each [[file link]] in dataview query result _Metadata menu_ plugin provides button to display its _Edit window_.

When I use `dv.view()` with custom view in dataviewjs that outputs [[file links]] in the form of

`<span><a data-tooltip-position="top" aria-label="${file.path}" data-href="${file.path}" data-file="${file.path}" href="${file.path}" class="internal-link" target="_blank" rel="noopener" file="${file.path}">${v.fileName()}</a></span>;`

which is a copy of dataview query's element, _Metadata menu_ plugin won't append [[file links]] with _Edit button_.

_Metadata menu_ uses postprocessor to automatically add _Edit button_ to certain html elements.
(you can search for these snippets in Metadata menu code:)
`
    this.plugin.registerMarkdownPostProcessor((el, ctx) => {
      updateElLinks(this.plugin.app, this.plugin, el, ctx);
    });`
`
function setLinkMetadataFormButton(plugin, link, destPath, viewTypeName, fileClassName) {
`

**Is there a way to trigger MarkdownPostProcessor on `dv.view()` result**?

Example Vault is in attachement: [DBViewPlusDataMenu.zip](https://github.com/mdelobelle/metadatamenu/files/11537585/DBViewPlusDataMenu.zip)

### DQL

```dataview
TABLE engine, date FROM #DB SORT file.name
```

### JS

```js
const query = 'TABLE engine, date FROM #DB SORT file.name';
await dv.view('inlinedb', {query: query});
```

### Dataview Version

0.5.56

### Obsidian Version

1.2.8

### OS

Windows

**Comment by mdelobelle** [comment]
I think this has been fixed. Can you confirm?
