### ISSUE TITLE
File Classes Not Working: No FileClass View for a FileClass or Ability to Assing FileClass to Note

### ISSUE THREAD

**Issue by johnkferguson** [mdelobelle/metadatamenu#339]
Hi,

I've recently started using Metadata Menu. I've enjoyed the Preset Field Settings Options and have recently tried to start using File Classes. However the fileClass functionality is not working. 

There are two issues:

1. FileClasses within the defined `fileClass` folder are not accessible when selecting the menu option "Add file class to..."
2. There is no icon for any FileClass nor the ability to access the FileClass view.

## More Details

This was done a Windows 10 PC on Obsidian v1.3.4.

I setup a fresh sandbox vault to help isolate any potential issues with my normal vault.

Within the vault, I did the following:

1. Installed Metadata Menu
2. Installed Dataview and enabled dataviewjs and inline queries
3. Created 4 notes: two example notes and two fileClass notes
4. Updated the fileClass settings

These are the changes I made to settings:
<img width="584" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/2823694/d767cbb3-871f-4c08-ad61-f22c20ccd82e">

This is the the content of the four files:

![image](https://github.com/mdelobelle/metadatamenu/assets/2823694/f0e35f0f-f15e-43bd-ba45-8706443b283f)

When I right click on either the Basic or Music Note and select, "Add fileClass to Music Note" a search modal opens and says no result found.

For the fileClasses, either global or music, when I right click on them, I only seeing the following options.

![image](https://github.com/mdelobelle/metadatamenu/assets/2823694/b6ff26b9-20c6-4a3b-b6e2-a80d0649ee51)

There is also no icon next to the title of any of the fileClass notes. 

I did manually add some info to the fileClasses. I wrote `status:: {"type": "Input"}` into the global fileClass and some other properties into the music fileClass. Unfortunately, this has not made any difference with the issue

**Comment by johnkferguson** [comment]
I'm not sure what happened exactly.

But this morning when I started the computer, this issue was gone. 🤷🏻

**Comment by see7e** [comment]
I have this same issue.
