### ISSUE TITLE
Dataview function not working to manage fileClass dropdown

### ISSUE THREAD

**Issue by jelphd** [mdelobelle/metadatamenu#340]
Hi,

I couldn't find any similar "issue," and this might not be an issue. I'm using fileClasses and the dataview functions to create dropdown values for my metadata. I have two pieces of metadata, Project and Subproject. After entering my Project field, I want to limit my Subprojects to only those that have the same Project value. I tried this code 

![image](https://github.com/mdelobelle/metadatamenu/assets/46376212/c149fbb9-4970-44b5-9f9a-98c6355ad900)

Unfortunately, the dropdown is empty with this code. 

The code works in Dataview. I created a query dataviewjs list query with the code, and it worked fine.

Am I doing something wrong, or does this type of query not work with fileClasses?

I tried to get help on the #dataview Discord channel, but people thought this did not work with Metadata Menu. 

Thanks for your response in advance.

JELPHD

**Comment by sinhaaritro** [comment]
The last time I tired it. dv.current() was not possible in the metadata menu.

For my case, I used something like this:
```
dv.pages('"tasks"')
.filter(p => p.file.link.path == current.file.link.path )
```

Here
1. `dv.pages('"tasks"')` will get me a list of all pages in a path (For you it should be changed to tags)
2. `.filter(p => p.file.link.path == current.file.link.path )` will take all files as p and only return the file where p and current files have the same path.

**Comment by rchaklashiya** [comment]
I have a similar issue, I've tried something that sometimes works, sometimes doesn't. Curiously, it fails whenever dataview fails...which is a whole other problem that inconsistently happens, and I'm not sure how to fix.

My syntax (which I know is correct and works when dataview doesn't fail) is: 
```dv.pages('#situationfolder').where(p=>p.is_crescendo===true)```

**Comment by mdelobelle** [comment]
You'll have to use current instead of dv.current()
