### ISSUE TITLE
Input incorrect if the files contain a comma, e.g. with "Accept Multiple Links".

### ISSUE THREAD

**Issue by tsteckenborn** [mdelobelle/metadatamenu#348]
For an input with a comma using a Dataview Query and "Accept Multiple Links", e.g. "Smith, Thomas", the output is `Smith]], [[Thomas`. Is there any way to change the character used for the joining (or are there any recommendations on how to work around this behavior)?

**Comment by marcelhuth** [comment]
Hi @tsteckenborn 
I do have the exact same problems with the plugin. I guess the only workaround would be avoiding a comma in the file name, which would lead to other problems in my notes.

Probably @mdelobelle can comment on this.

Thanks,
Marcel

**Comment by mdelobelle** [comment]
should be fixed in 0.7.7
