### ISSUE TITLE
Unable to get the example of the fieldModifier work

### ISSUE THREAD

**Issue by ooker777** [mdelobelle/metadatamenu#35]
# Code 1
I copy the exact code in the readme:
```
/```dataviewjs
const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api // destruct metadata-menu api to use fieldWithMeby function and give an alias: "_"

dv.table(["file", "status", "started"], 
    await Promise.all(                // await all modifier to resolve their promise
        dv.pages()
        .limit(10)
        .map(async p => [
            p.file.link, 
            await f(dv, p, "status")  // pass dv (dataview api instance), p (the page), and the field name to fieldModifier (: "f")
            await f(dv, p, "started") // pass dv (dataview api instance), p (the page), and the field name to fieldModifier (: "f")
            ])
    )
)
/```
```

The error:
```
Evaluation Error: SyntaxError: Unexpected reserved word
    at DataviewInlineApi.eval (plugin:dataview:15671:21)
    at evalInContext (plugin:dataview:15672:7)
    at asyncEvalInContext (plugin:dataview:15679:16)
    at DataviewJSRenderer.render (plugin:dataview:16267:19)
    at DataviewRefreshableRenderer.maybeRefresh (plugin:dataview:15995:26)
    at HTMLDivElement.r (app://obsidian.md/enhance.js:1:10007)
```
# Code 2
If I use a simpler code as in the [video](https://www.youtube.com/watch?v=fWVrzCc3B0Q), with no async and await keywords:
```
/```dataviewjs
const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api

dv.table(["file", "status", "started"], 
	dv.pages().map(p => [
	p.file.link, 
	p.status, 
	f(dv, p, "started")
]))
/```
```
then the table works, but the `started` column only displys `<Promise>`.

Also, it seems that you replaced `fieldWithMenu` with `fieldModifier`. Is that correct?

**Comment by mdelobelle** [comment]
Hi.
I need to replace the video since the function fieldWithMenu is now deprecated and the new one is async: Code 2 won't work anymore.
And for code 1, I've forgotten a comma in the copy/paste 😅. this is fixed now

/```dataviewjs
const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api // destruct metadata-menu api to use fieldWithMeby function and give an alias: "_"

dv.table(["file", "status", "started"], 
    await Promise.all(                // await all modifier to resolve their promise
        dv.pages()
        .limit(10)
        .map(async p => [
            p.file.link, 
            await f(dv, p, "status"),  // pass dv (dataview api instance), p (the page), and the field name to fieldModifier (: "f")
            await f(dv, p, "started") // pass dv (dataview api instance), p (the page), and the field name to fieldModifier (: "f")
            ])
    )
)
/```

**Comment by ooker777** [comment]
I get this error:
```
Evaluation Error: TypeError: fieldContainer.setAttr is not a function
    at eval (plugin:metadata-menu:1000:20)
    at Generator.next (<anonymous>)
    at eval (plugin:metadata-menu:69:61)
    at new Promise (<anonymous>)
    at __async (plugin:metadata-menu:53:10)
    at fieldModifier (plugin:metadata-menu:998:10)
    at eval (plugin:metadata-menu:1052:41)
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:9:7)
    at Array.map (<anonymous>)
    at Proxy.map (plugin:dataview:11738:39)
```

Some other questions:
- Is that correct that you always need to use async/await now?
- The comment for the first line should be `destruct metadata-menu api to use fieldModifier by function and give an alias: "f"` I think?
- Why can't this be applied with DQL? Or is it just you haven't had time to do it?
