### ISSUE TITLE
[FR] Ability to Format the field name when inserting as an inline field

### ISSUE THREAD

**Issue by thecookiemomma** [mdelobelle/metadatamenu#355]
Hello!  I use MDM every day and love the way it's helping me connect and shelve my thoughts into ideas.  
I also started using excalidraw and excalibrain for similar things, to see the info more visually.  I followed Zsolt's convention of **field**::  for inline fields.  Then, I realized that if I input the stuff in through MDM, I have to go through and bold the file field myself. Would it be possible, for certain fields, or even as a checkbox, to format the fields on insert?  Thank you!

**Comment by mdelobelle** [comment]
Nice idea! 
shouldn't be too difficult. I'll have a look at it

**Comment by mdelobelle** [comment]
Here's what I was able to do
<img width="1512" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/1233240/338c98a8-f2fc-40e8-afa1-ce3493446fef">
What do you think about it?

**Comment by thecookiemomma** [comment]
> Here's what I was able to do <img alt="image" width="1512" src="https://user-images.githubusercontent.com/1233240/255656843-338c98a8-f2fc-40e8-afa1-ce3493446fef.png"> What do you think about it?

That is exactly what I was looking for, thank you.  That way I can keep the formatting the same.  I appreciate it!
