### ISSUE TITLE
Autocomplete missing

### ISSUE THREAD

**Issue by elythh** [mdelobelle/metadatamenu#356]
Hello, I can't find the autocomplete settings. Has it been removed ?
[Options I have](https://imgur.com/iZY3UtQ)

**Comment by mdelobelle** [comment]
Hello, which version of the plugin do you have?

**Comment by dschense** [comment]
same for me. using obsidian on my ipad and installed v0.4.0 of the plugin

**Comment by elythh** [comment]
Honestly idk what happened, now the option is here. Might be because of another plugin but I can't tell what changed since last time I checked sorry
