### ISSUE TITLE
Canvas updates do not work if there is no frontmatter

### ISSUE THREAD

**Issue by sh-ghanique** [mdelobelle/metadatamenu#359]
Let me first state that this plugin is second only to DataView! What an impressive piece of work!

I think I found a bug, though. :-).

# Context

By using the field type "Updates with links in canvas" it is possible to change the value of a field depending on how the document has a connection to another document in the canvas.

# Summary

Metadata Menu is able to update the value of the field based on changes in the canvas, regardless of whether the field is in the document as a frontmatter field or a Dataview field. However, the document MUST have frontmatter. If the document does not have frontmatter, an exception occurs that changes to the canvas are not reflected in the field's value.

If the document does not have a frontmatter block, then Metadata Menu should not run into an exception, but proceed with checking the Dataview fields.

# Steps to Reproduce

## Working situation 1

This situation illustrates how the value of the field is updated, when the field is inside the frontmatter block.

### Set up

1. Create a document called "A"
2. Make sure A belongs to a File Class.
3. Make sure that the document has Frontmatter, and that the Frontmatter has more than 1 field.
4. Make sure the File Class has a Field called "CanvasField" of type "Canvas" that updates the value based on a Connection.
5. Create a Canvas.
6. Add A to the Canvas.
7. Add a random document called "B" to the Canvas.
8. Create a connection from A to B.

### Expected

A field with the name "CanvasField" is added to the frontmatter of A and has value "B". (Or: "[[B]]").

### Actual

A field with the name "CanvasField" is added to the frontmatter of A and has value "B". (Or: "[[B]]").

## Working situation 2

This situation illustrates that the value of the field is also correctly updated if the field is a Dataview field outside the frontmatter block, provided there still is a frontmatter block that contains other data.

### Set up

1. Continue from "Working Situation 1".
2. In A remove "CanvasField" from the Frontmatter. (The Frontmatter still contains other fields).
3. In the document of A add a Dataview-field "CanvasField", for example: `CanvasField:: Dummy`.
4. In the canvas add a random document called "C".
5. Move the connection between A and B to between A to C.

### Expected

Document A now contains a line below the Frontmatter that reads `CanvasField:: [[C]]".

### Actual

Document A now contains a line below the Frontmatter that reads `CanvasField:: [[C]]".

## Failing Situation

This situation illustrates how the value of the field is no longer updated if the field is a Dataview field and the document doesn't contain a frontmatter block at all. It also contains a Workaround.

### Set up

1. Continue from "Working Situation 2".
2. In A remove the frontmatter block. Notice that the field CanvasField is still in the document.
3. In the Canvas move the connection between A and C to between A and B.

### Expected

Document A now contains a line below the Frontmatter that reads `CanvasField:: [[B]]".

### Actual

Document A now contains a line below the Frontmatter that reads `CanvasField:: [[C]]". The value of CanvasField is NOT updated.

The console logs the following error:

plugin:metadata-menu:136 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'position')
    at getFrontmatterPosition (plugin:metadata-menu:136:32)
    at eval (plugin:metadata-menu:562:42)
    at Generator.next (<anonymous>)
    at eval (plugin:metadata-menu:60:61)
    at new Promise (<anonymous>)
    at __async (plugin:metadata-menu:44:10)
    at postValues (plugin:metadata-menu:557:10)
    at eval (plugin:metadata-menu:12359:19)
    at Generator.next (<anonymous>)
    at eval (plugin:metadata-menu:60:61)

### Workaround

Add the following frontmatter block:

```yaml
---
dummy: dummy
```

Now when the connection in the canvas is changed, the value of the Dataview field is updated.

**Comment by mdelobelle** [comment]
Hi, thank you for kind words and for pointing this out.
the "getFrontmatter" issue was more generic than just with canvas.

I've released a new version 0.5.1 can you try and see if it fixes your issue?

**Comment by sh-ghanique** [comment]
Wow, that's fast! :-).

Right away!

**Comment by sh-ghanique** [comment]
Working like a charm! You're the best!
