### ISSUE TITLE
Feature Request: Option to convert to dates to links by default

### ISSUE THREAD

**Issue by frankreporting** [mdelobelle/metadatamenu#36]
Love the ability to click the date toggle and type natural language to add a daily note link to the field (in conjunction with the natural language dates plugin). As I use this frequently, it would be nice not to have to click the toggle every time and instead make that the default, and toggle it OFF if needed.

**Comment by leoccyao** [comment]
Perhaps only marginally related, but I noticed that when the toggle is enabled, dates will always be inserted as links to daily notes. Some users may prefer having the dates not linked (links are not recognized in frontmatter still, and some users might use a different date format), so it would be great if link insertion could be controlled via a setting, or respect the "Add dates as link?" setting from the Natural Language Dates plugin.

Also possible that inserting dates could be overhauled; see my most recent feature request #54.

**Comment by leoccyao** [comment]
Should be closable given the `defaultInsertAsLink` option since 0.1.15?
