### ISSUE TITLE
Pages Formula struggle

### ISSUE THREAD

**Issue by DannyHatcher-Git** [mdelobelle/metadatamenu#363]
I am struggling to find any help documentation or video about how to use the pages part of the formula field - or any other options for the formula field.

I have tried putting pages.file name.field name but that didn't work.

The current.field works as expected.

Could you let me know what I need to do to reference a field from a different page?

In addition - can we round values to 2 decimal places?

Thanks again for all your work on this plugin!!

**Comment by mdelobelle** [comment]
Hi, the helper text is wrong.  "pages" is not accessible from the formula but the whole dataview api is with the "dv" keyword".
for example you can use `dv.page("<path to page>").file.name`

Could you try and see if it works? I will update the documentation accordingly

> In addition - can we round values to 2 decimal places?

I think this could be achievable with vanilla JS with something like Math.round(<your formula>*100)/100

**Comment by DannyHatcher-Git** [comment]
Thanks!

Sorry for the delayed response, been really busy.
