### ISSUE TITLE
Update with Links in Canvas incorrectly concatenates multiple links if Note has comma

### ISSUE THREAD

**Issue by sh-ghanique** [mdelobelle/metadatamenu#364]
Hello again,

I found another bug. It seems that if a Note in the Canvas contains a comma, that the plugin incorrectly concatenates the values for the field.

# Steps to Reproduce

## Global Setup

1. Create a Canvas called "Taxonomy".
2. Add a Note called "A, B" to the canvas.
3. Add a Note called "C" to the canvas.
4. Add a Note "Problem". This Note will demonstrate the issue.
5. Create a FileClass that applies to all three Notes. It defines the following field:

```json
parent:: {"type":"Canvas","options":{"direction":"outgoing","nodeColors":[],"edgeColors":[],"edgeFromSides":[],"edgeToSides":[],"edgeLabels":[],"canvasPath":"_metadata/Taxonomy.canvas","filesFromDVQuery":"dv.pages('#taxonomy')"}}
```

## Working condition 1

This illustrates how connecting "Problem" to one of the Notes works.

### Setup

1. Drag a Connection from "Problem" to "A, B".

### Expected

1. "Problem" contains a field "parent" with value "[[A, B]]".

### Actual

1. "Problem" contains a field "parent" with value "[[A, B]]".

## Working condition 2

This illustrates how connecting "Problem" to the other Note instead, also works.

### Setup

1. Remove the connection between "Problem" and "A, B".
2. Create a connection between "Problem" and "C".

### Expected

1. "Problem" contains a field "parent" with value "[[C]]".

### Actual

1. "Problem" contains a field "parent" with value "[[C]]".

## Failing Condition

This illustrates how the connection fails if Problem is connected to both Notes.

### Setup

1. Create a connection between "Problem" and "A, B".
2. Create a connection between "Problem" and "C".

### Expected

1. "Problem" contains a field "parent" with value "[[A, B]], [[C]]".

### Actual

1. "Problem" contains a field "parent" with value "[[A, [[C]]B]]"

## Workaround

None, really. Must remove comma's from the name of the Note.

Thank you! :-)

**Comment by mdelobelle** [comment]
Should be fixed in v 0.7.7
