### ISSUE TITLE
Canvas Group Field type missing

### ISSUE THREAD

**Issue by mrlinuxfish** [mdelobelle/metadatamenu#365]
I'm trying to add a canvas group field to automatically update the metadata based on canvas groups, but I can't find the option. I also appear to be missing the Canvas Group Link option in the Field type dropdown

![image](https://github.com/mdelobelle/metadatamenu/assets/444722/34a49fd9-e331-474e-a2a6-5325571debaf)

**Comment by mdelobelle** [comment]
Do you have any error message in the console?

**Comment by mdelobelle** [comment]
I've updated the version mapping between the plugin and obsidian. Could you try to update the plugin (you should get v0.5.1)?

**Comment by mrlinuxfish** [comment]
Updating the plugin to the new version fixed the issue. 

Thanks
