### ISSUE TITLE
Feature Request Date List Field type

### ISSUE THREAD

**Issue by mrlinuxfish** [mdelobelle/metadatamenu#366]
I would like the option to add multiple dates in a date field with the nice metadata menu interface for tagging the finish date of an item with multiple finish dates. This would be very helpful for updating metadata for re-reading books and cataloging the dates I have finished them.

**Comment by htmljenn** [comment]
I just came here to ask about this. I was debating marking the field as "any format" for the time being. As for your use case, that's exactly what I'd want it for - for re-reading books and for marking dates I've started and finished video media, such as the latest season of a show.

**Comment by mdelobelle** [comment]
Now you can do it with an ObjectList field
set `readings` as an ObjectList field
and `finishDate`as a Date field with "readings" as parent

you could add a `rating` field with "readings" as parent to rate each of you readings for example....
