### ISSUE TITLE
Latest plugin version in Obsidian in 0.4.0

### ISSUE THREAD

**Issue by artjomaverin** [mdelobelle/metadatamenu#369]
![image](https://github.com/mdelobelle/metadatamenu/assets/34308844/afdd0f37-a6b0-41db-a147-1e8b6e69b888)

**Comment by mdelobelle** [comment]
what is your version of obsidian?

**Comment by artjomaverin** [comment]
1.3.5 @mdelobelle

**Comment by mdelobelle** [comment]
I've changed the version file so that metadata menu v0.5.1 is available frop obsidian 1.3.5
Can you try to update the plugin?
(sometimes, the updated version is not availabléin the community plugins marketplace, you may have to close/open the app settings, or even restart obsidian)

**Comment by artjomaverin** [comment]
This works now, thank you!
