### ISSUE TITLE
[FR] Better UX to editing process

### ISSUE THREAD

**Issue by cogscides** [mdelobelle/metadatamenu#37]
1. Would be good to have an omnisearch box (like in quickswitcher, command pallet) when triggering the file "Field Options" command. It will add autofocus to the search field and will not require using a mouse to select the field I want to edit.

at the moment it opens a popup with selector which need to be triggered with mouse.
`current`
<img width="694" alt="image" src="https://user-images.githubusercontent.com/50235526/181904569-32e42eed-c2d4-460f-bd86-dcb594ab8399.png">

`idea to have`
<img width="500" alt="image" src="https://user-images.githubusercontent.com/50235526/181904686-0ad1848d-a036-4729-aff0-42f78fa852e8.png">

2. Same will be good for changing fileClass and selectors with predefined values. So it will be easy to change properties from UI

3. Make input autofocus for text value fields.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/50235526/181904651-17a7fa93-66e3-4996-b53b-15a8402699d7.png">

**Comment by mdelobelle** [comment]
hello. this is now available in 0.1.19
