### ISSUE TITLE
Updates with Groups in Canvas not showing

### ISSUE THREAD

**Issue by gBonvenuto** [mdelobelle/metadatamenu#371]
![image](https://github.com/mdelobelle/metadatamenu/assets/25495557/1abdd46d-64c6-472a-9c0d-533e5691f1ec)

Description: The only fields related to Canvas available is `Updates with links in Canvas`, and it works fine. But for some reason `Updates with Groups in Canvas` field does not appear.

Honestly, I won't use this feature too often, so if the problem is only with the selection menu, it would be enough if there is a way to manually set the field to `Group Canvas` (maybe by editing a file)

OS: Pop!_OS 22.04 LTS x
Obsidian: deb version

**Comment by mdelobelle** [comment]
Hi, is there any error message in the console?

**Comment by gBonvenuto** [comment]
![image](https://github.com/mdelobelle/metadatamenu/assets/25495557/b7b88c92-0233-478a-b905-49145ac530a2)

I don't really know how to use the console, but I filtered with `metadata`. Is this enough?

**Comment by mdelobelle** [comment]
What is your version of obsidian and your version of metadata menu?

**Comment by mdelobelle** [comment]
I've updated the version mapping between the plugin and obsidian. Could you try to update the plugin  (you should get v0.5.1)?

**Comment by gBonvenuto** [comment]
It worked. Thank you so much, your plugin is one of the most useful I've been using.
