### ISSUE TITLE
Modal when defining fileClasses?

### ISSUE THREAD

**Issue by biscotty666** [mdelobelle/metadatamenu#393]
In fileClass files I can see Table View but don't seem able to open the wonderful modal to edit fields. I don't see a way to do this in the table view either. Am I missing something or is the only way to edit fields in fileClasses themselves is with the menus?

Thanks

**Comment by mdelobelle** [comment]
When you access the fileclass view, there should be 3 tabs:
- Table view (default tab)
- Fileclass Fields (to edit the fields)
- Fileclass Settings (for mapWith tags, icon and so on...)
I think the second one is what you are looking for

**Comment by biscotty666** [comment]
Thank you. I knew I was just missing something. I didn't think to click on those headings. lol.
