### ISSUE TITLE
Inline button icon UI weirdness

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#399]
I think the icon is causing extra newlines to be added or something? In live preview. 

<img width="531" alt="Screenshot 2023-09-15 at 10 59 10" src="https://github.com/mdelobelle/metadatamenu/assets/7927356/d4c82195-438f-456d-ac96-7bfb5de79fd3">

**Comment by mdelobelle** [comment]
Is it fixed with the beta version?

**Comment by arminta7** [comment]
Yes!
