### ISSUE TITLE
Only First Field Shows in Context Menu without Supercharged Links

### ISSUE THREAD

**Issue by pixelswirl** [mdelobelle/metadatamenu#4]
I imported my settings to Metadata Menu from Supercharged Links using the button in settings.  Since it had its own "Display fields in context menu" setting I disabled the one in SL.  After that, the context menu only shows the first field.  (If I put the first one in the 'Ignore Fields' box, it only shows the second one)

This happens whether I only disable the "Display field options in context menu" option in SL, or if I disable SL entirely.  If I have "display field options" enabled in both plugins' settings it works as intended, but I thought that might become an issue when SL removes the functionality

I'm on the most recent versions of both plugins: 0.0.5 & 0.6.8

**Comment by mdelobelle** [comment]
Now that SL has removed the functionnality, do you still experience this issue?

**Comment by mdelobelle** [comment]
After testing again with 0.1.4, it seems that this issue is no longer showing up. I close this issue
