### ISSUE TITLE
Changing icon and plug in not found

### ISSUE THREAD

**Issue by melhopkop** [mdelobelle/metadatamenu#407]
Hi there! I'm new to Metadata Menu and trying to set it up.

One problem I'm having is changing the icons for the classes. Under Obsidian appearance I changed window frame to Obsidian frame and that helped the global icon show up. But the different icons for the different classes are not showing up.

I tried restarting Obsidian. If I close Obsidian when I have the pages open for the file class settings, then when I re-open Obsidian I get a message on those tabs saying "Plugin no longer active
The plugin that created this view
(FileClassView_Lecture Notes) has gone away"

Thanks for your help!

**Comment by mdelobelle** [comment]
available from v0.6.1
