### ISSUE TITLE
Fields and fileclasses stop working when using certain Tags 

### ISSUE THREAD

**Issue by SpocWeb** [mdelobelle/metadatamenu#413]
First of all I have to say that your plugin is awesome! It is so much more useful than even the new Standard Obsidian Properties. 

I have generated 800 FileClasses from the schema.org Models and most of them work. 
But if I use `mapWithTag: true` for some (83 i.e. 10%) of these FileClasses, it breaks the mapping and no File is mapped anymore. 

You can reproduce this by cloning this Repo as a Subfolder into any Vault and configure its `fileClass` Folder.

 https://github.com/SpocWiki/_Standards 
 
 My FileClass settings are: 
 - class File Path: _Standards/fileClass/
 - fileClass Field Alias: fileClass
 - global fileClass: _Standards/fileClass/FileClass~Thing.md
 
If you set `mapWithTag: true` for e.g. the `Car` and the `BusOrCoach` FileClass, no mapping works anymore after restarting Obsidian. 
 https://github.com/SpocWiki/_Standards/blob/main/fileClass/FileClass~Thing/FileClass~Product/FileClass~Vehicle/FileClass~Car.md 
 https://github.com/SpocWiki/_Standards/blob/main/fileClass/FileClass~Thing/FileClass~Product/FileClass~Vehicle/FileClass~BusOrCoach.md
 
 You need to restart Obsidian for the mapping to break. 
 If you undo it, and restart once more, it works again. 
 
Most of the FileClass.md Files I generated work and I even deleted and re-created this `Car` FileClass manually with the modal Editor 
to eliminate the possiblity of the Generation to introduce any hidden Characters, but I could not see the reason why some FileClasses break the System. 

The same holds true for e.g. `FileClass~BusOrCoach.md` in the same folder, but everything is fine with e.g. https://github.com/SpocWiki/_Standards/blob/main/fileClass/FileClass~Thing/FileClass~Product/FileClass~Vehicle/FileClass~Motorcycle.md which is also in the same Folder.

You can reproduce this issue by updating a few of the 83 Files in this Repo with `mapWithTag: false` to `mapWithTag: true`. 
Sorry that I cannot be more specific.

It would be nice if you could look into this. 
Thank you so much.

Here is the List of Files I had to switch Tag-Mapping off for: 

	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~Apartment.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~CampingPitch.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~House\FileClass~SingleFamilyResidence.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~House.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~Room\FileClass~HotelRoom.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~Room\FileClass~MeetingRoom.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~Room.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation\FileClass~Suite.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Accommodation.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~AdministrativeArea\FileClass~City.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~AdministrativeArea\FileClass~Country.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~AdministrativeArea\FileClass~SchoolDistrict.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~AdministrativeArea\FileClass~State.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~AdministrativeArea.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Airport.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Aquarium.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Beach.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~BoatTerminal.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Bridge.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~BusStation.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~BusStop.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Cemetery.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndEntertainmentBusiness\FileClass~MovieTheater.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndLodgingBusiness\FileClass~Campground.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization\FileClass~EducationalOrganization\FileClass~CollegeOrUniversity.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization\FileClass~EducationalOrganization\FileClass~ElementarySchool.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization\FileClass~EducationalOrganization\FileClass~HighSchool.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization\FileClass~EducationalOrganization\FileClass~MiddleSchool.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization\FileClass~EducationalOrganization\FileClass~Preschool.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization\FileClass~EducationalOrganization\FileClass~School.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization\FileClass~EducationalOrganization.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~CivicStructureAndOrganization.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Crematorium.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~EventVenue.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~GovernmentBuilding\FileClass~CityHall.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~GovernmentBuilding\FileClass~Courthouse.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~GovernmentBuilding\FileClass~DefenceEstablishment.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~GovernmentBuilding\FileClass~Embassy.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~GovernmentBuilding\FileClass~LegislativeBuilding.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~GovernmentBuilding.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Museum.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~MusicVenue.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Park.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~ParkingFacility.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PerformingArtsTheater.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PlaceOfWorship\FileClass~BuddhistTemple.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PlaceOfWorship\FileClass~Church\FileClass~CatholicChurch.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PlaceOfWorship\FileClass~Church.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PlaceOfWorship\FileClass~HinduTemple.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PlaceOfWorship\FileClass~Mosque.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PlaceOfWorship\FileClass~Synagogue.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PlaceOfWorship.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Playground.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~PublicToilet.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~RVPark.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~SubwayStation.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~TaxiStand.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~TrainStation.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure\FileClass~Zoo.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~CivicStructure.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~Canal.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~LakeBodyOfWater.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~OceanBodyOfWater.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~Pond.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~Reservoir.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~RiverBodyOfWater.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~SeaBodyOfWater.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater\FileClass~Waterfall.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~BodyOfWater.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~Continent.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~Mountain.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform\FileClass~Volcano.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Landform.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~LandmarksOrHistoricalBuildings.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Residence\FileClass~ApartmentComplex.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Residence\FileClass~GatedResidenceCommunity.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~Residence.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~TouristAttraction.md
	fileClass\FileClass~Thing\FileClass~Place\FileClass~TouristDestination.md
	fileClass\FileClass~Thing\FileClass~Product\FileClass~Vehicle\FileClass~BusOrCoach.md
	fileClass\FileClass~Thing\FileClass~Product\FileClass~Vehicle\FileClass~Car.md

**Comment by mdelobelle** [comment]
Hi
congrats for this repo, it's a great resource !!!
I've tested it on the new version I'm currently working on and it seems to work fine.
This version is under testing right now. If you're interested, I'm planning an alpha testing in a month or so.

This version bring new field types:
- Objects (nested fields)
- Object Lists (lists of nested fields)
- Yaml fields
- JSON fields

it has also its own full indexing system that is consuming less RAM/CPU than previous versions

SO there are a lot of changes that's the reason why I'd like to test it carefully before releasing it

**Comment by mdelobelle** [comment]
you can test this package and see if it solves your issue https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.0-beta-3
