### ISSUE TITLE
Metadata Menu Dataview integration stopped working

### ISSUE THREAD

**Issue by ryanjamurphy** [mdelobelle/metadatamenu#419]
(I'm sure this is on my end, but I can't figure it out, so I'll try here to see if I can triangulate the issue with people smarter than I.)

I have a simple callout for project info at the top of my project templates:

> [!TIP]+ Project info
> ```dataviewjs
> const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api;
> 
> 
> await f(dv, dv.current(), "review", {attr: {"style": "margin-left: auto; opacity: .6"} })
> await f(dv, dv.current(), "status", {attr: {"style": "margin-left: auto; opacity: .6"} })
> ```

While it previously worked fine, I recently noticed it no longer renders anything at all. 

Similarly, Metadata Menu fields in my Dataview tables have also stopped showing up.

I wish I knew when it started, but perhaps it was a recent dataview update?

Happy to provide any other info I can!

**Comment by mdelobelle** [comment]
I can reproduce it. It's indeed related to the update to dataview's version 0.5.62 or 0.5.63. I'll try to figure out how to fix it

**Comment by mdelobelle** [comment]
some other users are encountering the same issues and the devs are talking about a new version being. https://github.com/blacksmithgu/obsidian-dataview/issues/2136
I've tested their PR and this is fixing the issue. So we just have to wait for the next release 🤞

**Comment by ryanjamurphy** [comment]
I'm just glad it's not something I did for once... and that I don't need to fix the infrastructure of a whole bunch of notes!
