### ISSUE TITLE
FR: Please provide instructional videos to teach the new version's features.

### ISSUE THREAD

**Issue by YIRU69** [mdelobelle/metadatamenu#431]
I really enjoy watching your videos, I watch every one of them and they are really helpful. I am not a programmer, so honestly, I cannot understand the announcements and explanations you post. If you have some free time, could you please make an instructional video to explain the new version's features?

**Comment by mdelobelle** [comment]
Hi. I've made a quick tour of the new field types. Hopefully it will be usefull https://youtu.be/EhEJSxTzzBg

**Comment by YIRU69** [comment]
Thank you so much.
