### ISSUE TITLE
Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by quantumfate** [mdelobelle/metadatamenu#439]
I have the follewing dataview js query:

```js
let currentParents = dv.current().file.frontmatter.parents;
dv.table(["Parents"],[[currentParents]])
```

It renders a clickable link like this:
![image](https://github.com/mdelobelle/metadatamenu/assets/62796852/6731ca57-d390-4959-a3d5-4b1e7303419e)

When I click the link, the current tab crashes with the following message:

```
Uncaught TypeError: Cannot read properties of null (reading 'path')
    at addCommands (paletteCommands.ts:343:71)
    at eval (plugin:metadata-menu:14344:9)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:2028169)
    at t.activeLeafEvents (app.js:1:2014065)
    at l (app.js:1:254406)
    at c (app.js:1:254522)
```

## FileClasses

Note where query is clicked:
![image](https://github.com/mdelobelle/metadatamenu/assets/62796852/526010c7-6e36-4940-b1ee-8d9d23f40288)

Targeted note that is never reached due to crash:
![image](https://github.com/mdelobelle/metadatamenu/assets/62796852/1e96c6a7-426f-42b1-892d-a1a3d185e67e)

If there is anything else I can provide for troubleshooting, let me know.

**Comment by mdelobelle** [comment]
Hi, which version of the plugin are you currently using?

**Comment by quantumfate** [comment]
> Hi, which version of the plugin are you currently using?

0.5.2 @mdelobelle

**Comment by quantumfate** [comment]
@mdelobelle I figured out why it's crashing. The current tab/window crashes when the name of the file you are about to jump to is a substring of the name of the file you are currently on.

Example: Electrical Engineering -> Engineering, Quantum Physics -> Physics

**Comment by mdelobelle** [comment]
can you try with the latest beta version? 0.6.0-beta-9 ?

**Comment by quantumfate** [comment]
> can you try with the latest beta version? 0.6.0-beta-9 ?

yep that seems to fix it

**Comment by mdelobelle** [comment]
0.6.1 is now released
