### ISSUE TITLE
Metadata Menu buttons in the Properties pane

### ISSUE THREAD

**Issue by jayambede** [mdelobelle/metadatamenu#450]
Is it possible to "inject" the Metadata Menu buttons for the property fields into the **properties' pane**? 
Maybe next to the "Add property" button, like in the Reading Mode? This would make it available at any stage of the Production of a note, without having to change to Reading Mode? 

Thanks a lot for this wonderful plugin!!

**Comment by mdelobelle** [comment]
Thank you for your feedback. What would be your use case?

From what I can see in the property pane you can see the number of files having a given property. So it's not obvious in which file the property should be modified by a field control

<img width="1135" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/1233240/f6a026d0-f3d0-4b6e-abcf-f674f568568d">

**Comment by jayambede** [comment]
Yeah, sorry, my fault ... wrong name of the pane (was late for me yesterday ...). I was actually thinking of the "file properties" pane. That would make the fileclass properties available in all presentation stages of a note (source, live preview and reading mode). 

This one:
![Screenshot_20231125_115849](https://github.com/mdelobelle/metadatamenu/assets/109915967/c162cac4-a8a3-4e91-a6c6-0454eacacacf)

**Comment by jayambede** [comment]
A small addition to this feature request:

In reading mode, when the metadatamenu buttons are displayed in the Properties section, I get these buttons at the buttom (one for each fileclass (global field or tag-based) being used):
![Screenshot_20231125_174517](https://github.com/mdelobelle/metadatamenu/assets/109915967/de934192-f543-46d7-ac08-c7b5c7b6a45f)
clicking on them opens a modal that essentially replicates the modal that can be reached by the tab-button (clicking on the entries opens the respective "choice-modal") but there is also a "++NEW++" entry, which leads to this modal:
![Screenshot_20231125_175344](https://github.com/mdelobelle/metadatamenu/assets/109915967/e6513cc4-99ac-4c81-9ede-de6b94f0e3b3)
If you enter text into the fields and click the checkmark this does ... nothing.

Don't get me wrong, I am just curious: is that a bug? Or a preview of things to come? The buttons give the impression to make changes in the respective fileclasses directly - which would be really nice(!) but - at least in my case - that does not work ...

**Comment by mdelobelle** [comment]
> clicking on them opens a modal that essentially replicates the modal that can be reached by the tab-button (clicking on the entries opens the respective "choice-modal") but there is also a "++NEW++" entry, which leads to this modal:

this will be fixed in the next version 0.6.5

> was actually thinking of the "file properties" pane

I didn't even know about this pane existing 😅. Will try to do include the commands in it in a future version

**Comment by jayambede** [comment]
Yeah, the Obsidian Team doesn't seem to "advertise it" a lot, but in my view it's one of the *core* features of the overhaul of the frontmatter. It gives a metadata overview for all notes and offers the chance to manipulate the data from one place.  I am happy, you will try to use it in future versions ... and don't feel hasted about it ... ;-)

**Comment by netfly** [comment]
I would love this, because I only use this pane and hide the properties in the files.

**Comment by LemurTech** [comment]
+1 for this. I prefer having properties in the sidebar pane rather than cluttering the top of my document.

**Comment by mdelobelle** [comment]
It's now available since 0.8.7

**Comment by LemurTech** [comment]
Hooray, thank you!

**Comment by netfly** [comment]
Awesome .... thank you very much.
