### ISSUE TITLE
Double Display of first Property/metadata-item in metadata modal

### ISSUE THREAD

**Issue by jayambede** [mdelobelle/metadatamenu#451]
In version 6.1/6.2 the first metadata-/Property item of a fileclass is displayed twice in the metadata-Modal, when it is accessed via the Metadata-Menu-button, as displayed in this screenshot. There is only one property-item in the note. Looks to me like a doubled line in the construction-code of the Modal. Maybe I should add that the "typ" field is the fileclass field alias ...

![Screenshot_20231124_171607](https://github.com/mdelobelle/metadatamenu/assets/109915967/2c136f7c-3af5-4bbb-a8cc-f096f3e3be09)

**Comment by jhilker98** [comment]
I can also confirm this issue.

**Comment by mdelobelle** [comment]
Could you paste here the content of the ARTIKEL.md file?

**Comment by mdelobelle** [comment]
and the frontmatter of your `Climaxes and anticlimaxes`file please?

**Comment by jayambede** [comment]
Here the content of the ARTIKEL.md fileclass:
![Screenshot_20231125_115738](https://github.com/mdelobelle/metadatamenu/assets/109915967/0d095c43-c96e-43d1-9f0e-8e2083b15c07)

**Comment by jayambede** [comment]
And the content of the "Climaxes and anticlimaxes" file (with a few additions, since I was working on it the yesterday):
![Screenshot_20231125_120230](https://github.com/mdelobelle/metadatamenu/assets/109915967/6ca0261a-587e-4da0-94b2-7b160c5ff011)

**Comment by jayambede** [comment]
I just had another look at the "ARTIKEL" fileclass definition file. Looks like you have changed its structure (just an aside). 

What I did noticed is the following: 

- I have a "global fileclass named ALL, which contains the definitions for "typ", "autoren" and the fields "tags", "aliases" and "cssclasses". 
- The ARTIKEL-class *extends* ALL with the fields seen above. 
- Since I want the fields to be in a defined order in all notes, the templates contain all their fields in that order. 
- To make metadata-menu recognize the fileclass on creation of a note, the "typ" field is already filled with the respective value (e.g. "ARTIKEL"). 
 
Could it be that this causes the doubling?

**Comment by mdelobelle** [comment]
Alright, that was it: the "typ" definition is not needed anymore -> it is automatically displayed in the modal even if there's no definition for it in the fileClass

You can remove this "typ" field from the "global fileclass" field set

**Comment by jayambede** [comment]
Thank you! It's good, that I don't have to keep a proper List of the available fileclasses, as I did up to now. There is only one catch in my usecase:

I keep two types of fileclasses: 

1. One class based on the "typ" property (e.g. ARTIKEL or PERSON)
2. second class to extend these base classes via "tag-classes" for special subcategories (e.g. "#PERSON/Writer" or "#PERSON/Philosopher"). These add certain properties specific to the type of note.

I keep these "tag-classes" in a subfolder to the fileclass folder, to properly separate them. This worked fine and still they appear in the fileclass list, but when I  (by accident) choose one of them, they appear as (e.g.) "tagclasses/PERSON_WRITER" in the "typ" property, which is a bit irritating, and not what I created them for. They still work fine with all the base-properties *and* the extensions, though.

I can live with that, because I know what's going on (and because they appear at the end of the filecalss list ;-) ). And I actually have no idea how this could be solved (except for separating the "tag-classes" from the "global field-classes"  in the plugin (e.g. by a different folder)). But it's not for me to decide on this, I just wanted to leave a note ...

Still, thanks a lot for your time and effort and especially for this great plugin!

**Comment by mdelobelle** [comment]
Hi, adding automatically a "fileClass" field in the icon modal wasn't a good idea:
- it creates a redundant info for fileClasses inheriting another file class that has a field with the same name as the file class alias
- it's not so useful after all: If you have a file mapped with no file class, the icon modal won't show up so you won't be able to select a file class. And if your file is already mapped with a file class, then it very unlikely that you want to change it

The strategy of having a global file class with a field named like the file class alias, of type "Select", with the list of existing file classes as the values, is by far a better strategy that I didn't event thought about.

I'll remove this automatic addition of the "file class selector" in the modal in the next release

**Comment by OXiOSDev** [comment]
Thank you so much for taking the time to reply and once again, a huge thank you for this incredible plugin.

**Comment by jmonroynieto** [comment]
Hey, guys. I tried following some of the insights in this thread about disabling any extension to Global fileclass and now find myself with a new issue. Metadatamenu has stopped recognizing classes randomly in most of my files. I now have to add the global fileclass to the aliased field when I want the class to be recognized. This is to say that I have to add `typ: ALL, myclass` to follow the example given above.

All this for the fileclass modal to not show a fileclass selector at all and loosing autocomplete. What makes it strange to me is that adding the fileclass through the command menu gives me the correct list of possible file classes
