### ISSUE TITLE
Bug: Duplicate field in display

### ISSUE THREAD

**Issue by Smitty010** [mdelobelle/metadatamenu#453]
I have three fileClasses which are transitive.  There is "base"
![image](https://github.com/mdelobelle/metadatamenu/assets/3760075/2d3de6e4-3d87-4cda-9999-9777e8fb0538)

The second is "statuBase" (which is based on "base")
![image](https://github.com/mdelobelle/metadatamenu/assets/3760075/8c8e0b78-3193-4f47-81cc-335c8ff14151)

And there is "video" (which is based on "statusBase")
![image](https://github.com/mdelobelle/metadatamenu/assets/3760075/2f4870dc-efb7-4519-a240-8b48dcab2866)

If I look at a video file properties, I see:
![image](https://github.com/mdelobelle/metadatamenu/assets/3760075/12be5250-7e42-460e-a74a-4d596b04f8e4)

Note that there are two fileclass properties displayed.  I assume there should only be one.

**Comment by mdelobelle** [comment]
Is the `fileClass: video` line duplicated in your frontmatter?

**Comment by mdelobelle** [comment]
do you have a global fileClass defined with a "fileclass" field set in it?

**Comment by Smitty010** [comment]
I think the answer is no:

![image](https://github.com/mdelobelle/metadatamenu/assets/3760075/3bfe12f5-086a-4091-a552-1e47e2fc4ae2)

**Comment by mdelobelle** [comment]
Ok then it's pure inheritance between classes. I'll add a setting to toggle "auto add fileclass in modal" that will hide this extra field if toggle off.
WDYT?

**Comment by Smitty010** [comment]
I think that would work.  The reason I explicitly add the fileclass field
is so I can have a list of the fileClasses in my vault to choose from.

I didn't realize that it was being automatically added.  If it creates a
selection list from the fileclass folder, then I'm happy just to eliminate
it from my fileclasses and let you do it automatically.

**Comment by mdelobelle** [comment]
The drawback of the "auto propose a fileClass value modifier" is that you'll have to set a fileclass first. 
Your method is much more usefull IMO: every file is mapped with the generic fileclass that let's you choose the specific fileclass when the file is "empty".

This is a very good usage of global that I didn't event think about ! I think I'll get this idea  for my own vault ;)

**Comment by Smitty010** [comment]
Cheers

**Comment by mdelobelle** [comment]
there is now an option to remove them in v0.6.4
