### ISSUE TITLE
Low performance for entire vault and Auto Complete not working on newest update 0.6.2

### ISSUE THREAD

**Issue by vegata145** [mdelobelle/metadatamenu#454]
After updated to 0.6.2, I got some problems:

-  Low performance on my Vault. I think because the new indexing causes it. Is there any way to update indexs manually?
- After adding class to note, when run 'add missing fields to section', it take about 10s to load all fields (it was almost immediately).
-  Auto Complete not working anymore.
- In some notes, right click menu disappeared.

Thank for your plugin. It helps me so much.
Sorry for may bad English

**Comment by mdelobelle** [comment]
Hi do you have formula and lookup fields in your vault?

**Comment by mdelobelle** [comment]
If you do, you can try 0.6.3 : it removes the auto update of formula and lookups at start.
You could also toggle-off the "auto-update" setting of each of those fields

**Comment by vegata145** [comment]
Yeah, I have some self-lookup fields, but It works fine on last version. Ok, I'm going toggle off the auto-update. Hope this fix on up coming version. Thank you!!!

**Comment by vegata145** [comment]
Hey, I'm just check. There is no toggle off option here
<img src="https://github.com/mdelobelle/metadatamenu/assets/65795182/4262ac8a-9a54-41ba-bcf3-b889332eb383" width="400" height="500">

**Comment by mdelobelle** [comment]
> After adding class to note, when run 'add missing fields to section', it take about 10s to load all fields (it was almost immediately).

How large is the corresponding file where you are trying to insert the missing fields?

**Comment by mdelobelle** [comment]
could you try this version ? https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.4-beta-1

install it with BRAT or just put the main.js, styles.css and manifest.json in the ./obsidian/plugins/metadata-menu folder

**Comment by vegata145** [comment]
> How large is the corresponding file where you are trying to insert the missing fields?

The note is totally empty.


> could you try this version ? https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.4-beta-1
> install it with BRAT or just put the main.js, styles.css and manifest.json in the ./obsidian/plugins/metadata-menu folder

I've tried this version, disabled the whole note scope, but it's not much better. It's still low performance and can't use inline field auto complete.

**Comment by mdelobelle** [comment]
I've made a complete new approach:  https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.4-beta-2

is it better with this version?

**Comment by vegata145** [comment]
> I've made a complete new approach: https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.4-beta-2
> 
> is it better with this version?

Quick test here, It's much faster now, but still can't auto complete.
Now I can typing as fast as I can 😄

**Comment by mdelobelle** [comment]
ok would you mind filling a separate issue for the autocompletion please? i'll work on that later but I'd like to wrap a release to fix those performance issues asap

**Comment by vegata145** [comment]
> ok would you mind filling a separate issue for the autocompletion please? i'll work on that later but I'd like to wrap a release to fix those performance issues asap

Ok, thank you. Hope the auto-complete will be fixed soon.
