### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by koenbunders** [mdelobelle/metadatamenu#459]
Hi, first: thanks for you amazing plugin.
Since a day or two I notice a performance drop.
When I am typing in any note, the editor cannot keep up with the speed of my writing.
When I turn off the metadata menu plugin, the performance is as amazingly good as it used to be.
Hope this can be fixed

**Comment by mdelobelle** [comment]
Hi could you try this beta version and tell me if it improves the experience?

https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.4-beta-2

**Comment by koenbunders** [comment]
Thanks for the swift response, and I apologise for my noob question: I don't know how to install. I tried to install using BRAT, but got this error message:
![Xnip2023-11-26_09-47-09](https://github.com/mdelobelle/metadatamenu/assets/12957034/b42139f4-9839-4438-9479-b89517f39631)

**Comment by koenbunders** [comment]
I've installed 0.6.4-beta-2 and the issue seems to be gone! Will do some further testing! Thank you.

**Comment by koenbunders** [comment]
Plugin is still influencing performance. Opening a folder in the file explorer takes significantly longer when the plugin is enabled.

**Comment by mdelobelle** [comment]
Could you try to turn-off the metadata menu button in file-explorer and compare the performance ?
<img width="624" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/1233240/f88b5794-2b09-468a-be78-6f41f7c5a277">

**Comment by mdelobelle** [comment]
(you would have to disable/enable the plugin to take it into account)

**Comment by koenbunders** [comment]
That helped! Thanks

**Comment by mdelobelle** [comment]
great. I'll look later on how to include icons only when the folder is unfolded to reduce the DOM supercharging

besides that can you consider that the performance is ok now?

**Comment by koenbunders** [comment]
Unfortunately not. For example: when adding / removing file properties, the response is very slow. When the plugin is turned off, this is as quick as it used to be.

**Comment by mdelobelle** [comment]
If you have the time to do it, could you make a screen recording and post it here? It could be of a great help for investigating furthermore

**Comment by koenbunders** [comment]
Yes. No problem. I've been trying to reproduce the performance issue around adding /removing file properties, but can't reproduce at the moment! 🤞
