### ISSUE TITLE
Getting "Cannot read properties of undefined (reading 'table')" error after updating Metadata Menu

### ISSUE THREAD

**Issue by austinletson** [mdelobelle/metadatamenu#463]
# Issue
I recently updated Metadata Menu and now when I add a MultiFile setting to "Preset Fields settings" I get the following error when starting Obsidian:

![2023-11-27-10:39:30-screenshot](https://github.com/mdelobelle/metadatamenu/assets/21346448/28f459e3-ecff-4f52-a98e-cab91fc126bb)
![2023-11-27-10:39:34-screenshot](https://github.com/mdelobelle/metadatamenu/assets/21346448/9346f315-bce6-4acc-b1b9-ec7f752e1925)

## Settings
![2023-11-27-10:42:51-screenshot](https://github.com/mdelobelle/metadatamenu/assets/21346448/1fd48023-3a6a-4c45-9e65-8c8a0736ff81)
![2023-11-27-10:42:56-screenshot](https://github.com/mdelobelle/metadatamenu/assets/21346448/8fc8db90-0e1f-4040-a04e-fa60a785d746)

## What I have tried
- Reinstalling Metadata Menu
- Updating all plugins

I believe this is coming from [this](https://github.com/mdelobelle/metadatamenu/blob/0790f23c2c9b6e6bf452a969f880636289d1cc74/src/suggester/metadataSuggester.ts#L74) line in `metadataSuggester.ts` which was changed last week

**Comment by vervitee** [comment]
Getting same error as above and attempted same fixes without success. Adds significant startup lag.

**Comment by austinletson** [comment]
@mdelobelle thank you for fixing this so quickly. This plugin is absolutely amazing!

**Comment by mdelobelle** [comment]
Thanks a lot! Very much appreciated. Don't hesitate to propose new ideas and features
