### ISSUE TITLE
MetaData button icon wont change

### ISSUE THREAD

**Issue by EdFenner** [mdelobelle/metadatamenu#466]
I had picked a simple 3 dot bar icon that was working great. It has suddenly changed on me to a 3D box. No matter what icon name I give or go back to the default I get the same result.
![2023-12-01_21-36-26](https://github.com/mdelobelle/metadatamenu/assets/3855021/9757a0fb-8a34-49a4-8381-11a1590c7213)

**Comment by mobelby7** [comment]
Same issue for me.
I am on the minimal theme with the default hidden frame setting and all I can get is that 3D box
