### ISSUE TITLE
BUG: Canvas Links in frontmatter are not usable and error prone

### ISSUE THREAD

**Issue by quantumfate** [mdelobelle/metadatamenu#468]
Updating links in a canvas is a great feature for metadata menu. I just have a suggestion how to improve the feature with the current state of the property section in obsidian.

Take a look at my note's frontmatter:

![image](https://github.com/mdelobelle/metadatamenu/assets/62796852/7d74e31c-1358-4aa5-9865-9b3d4de7271e)

As you can see my "parents" field properly displays the links to it's parent notes. But the Link to the automated field "Assignment Relation" for the canvas is corrupted in two ways:

1. The type of the property can not be detected __It should be a list__
2. The link itself is not clickable

Now lets take a look at the difference in source mode: 

![image](https://github.com/mdelobelle/metadatamenu/assets/62796852/4216574f-d212-414d-b5ba-84ecf56e5a37)

As you can see for the "parents" field, this is what the links should look like. Changing the way the updated links are displayed would also make it easier for more javascript magic inside your notes.

**Comment by mdelobelle** [comment]
fixed in 0.6.6 https://discord.com/channels/686053708261228577/855181471643861002/1180919763371835453
