### ISSUE TITLE
[BUG] the fields repeat every time I open obsidian

### ISSUE THREAD

**Issue by toxfu** [mdelobelle/metadatamenu#469]
Every time I open Obsidian the fields that I have configured using FileClass are repeated. I have results like the following:

![notepad++_6TT0wmfW63](https://github.com/mdelobelle/metadatamenu/assets/92554009/ffde1bd9-34e4-4e03-82d5-7a34569689aa)

The code that always worked for me is the following

`Status:: {"type":"Formula","options":{"autoUpdate":true,"formula":"(current.PagesTotal === current.PagesRead) ? 'FINISHED' : ((current.PagesRead > 1) ? 'READING' : 'WITH STARTED');"}}`

**Comment by toxfu** [comment]
`---
banner: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1632024090i/27213329.jpg"
Tags: 💡Learning
Aliases: 
Category: 
Author: Angela Duckworth
Status: WITH STARTED
Score: 
Cover: https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1632024090i/27213329.jpg
PagesRead: 1
PagesTotal: 316
Status: WITH STARTED
Status: WITH STARTED
Status: WITH STARTED
Status: WITH STARTED
Status: WITH STARTED
Status: WITH STARTED
Status: WITH STARTED
Status: WITH STARTED
Status: WITH STARTED
---`

and this is my fileclass

`Status:: {"type":"Formula","options":{"autoUpdate":true,"formula":"(current.PagesTotal === current.PagesRead) ? 'FINISHED' : ((current.PagesRead > 1) ? 'READING' : 'WITH STARTED');"}}`

this file manage for **Query based FileClass settings**

**Comment by mdelobelle** [comment]
What is the version of your plugin currently? this fileClass definition is a legacy one
