### ISSUE TITLE
dv pages doesn't find all files

### ISSUE THREAD

**Issue by Pesssimist** [mdelobelle/metadatamenu#478]
I want to create a property that allows me to select a link from among the files in the folder. To do this, I use the construct in the Dataview query field
`dv.pages('"Foldername"')`
As a result, I only get .md files, But I need a list of all files (.pdf, office, etc) in this folder.
Please help!

**Comment by mdelobelle** [comment]
there's a new "Media" field type for it. Does it suit your needs?

**Comment by gssantana** [comment]
Could the Media field be enhanced to allow filtering by folder? For instance, displaying all files from a specific folder like "Resources," regardless of their extensions or media types.

Here's the structure of the vault:

```
Resources
  Canvas
  Drawio
  Excalidraw
```

It would be helpful if media property field could list all media from the "Resources" folder, allowing us to select and attach them. Nowadays, it just shows Drawio files.

Another suggestion is to implement filtering for these media files using DV. For instance, allow/filter all media from the "Resources" folder where the file names match the name of the note or other criteria using dv.

**Comment by gssantana** [comment]
> Could the Media field be enhanced to allow filtering by folder? For instance, displaying all files from a specific folder like "Resources," regardless of their extensions or media types.
> 
> Here's the structure of the vault:
> 
> ```
> Resources
>   Canvas
>   Drawio
>   Excalidraw
> ```
> 
> It would be helpful if media property field could list all media from the "Resources" folder, allowing us to select and attach them. Nowadays, it just shows Drawio files.
> 
> Another suggestion is to implement filtering for these media files using DV. For instance, allow/filter all media from the "Resources" folder where the file names match the name of the note or other criteria using dv.

If anyone needs something similar, here's how I managed to do it

```
this.app.vault.getAllLoadedFiles().filter(
file => file.path.startsWith("Resources")  && [ ".canvas", ".drawio", ".excalidraw", "excalidraw.md" ].some(
ext => file.path.endsWith(ext))
).map(file => "[[" + file.path + "]]"
)
```

![image](https://github.com/mdelobelle/metadatamenu/assets/57970850/e5faceaa-28c9-4aa9-936f-3848c8ec38c9)
