### ISSUE TITLE
Add missing fields at section stopped working

### ISSUE THREAD

**Issue by endlessblink** [mdelobelle/metadatamenu#483]
For some reason, I can't automatically add missing fields. 
And when I try to add them manually from the fields modal, it doesn't show any properties. 

![image](https://github.com/mdelobelle/metadatamenu/assets/37155282/14a779d9-b47d-4260-80df-eea0053097c3)

Is there a way to solve this?

Thanks!

**Comment by mdelobelle** [comment]
do you have any error in the console?
Can you paste the content of:
this file's frontmatter
the related fileClass file's frontmatter

**Comment by endlessblink** [comment]
Thanks for getting back to me. 
After reinstalling the plugin, it got sorted out. 

You can close this ticket 🙏🏽
