### ISSUE TITLE
Two new tabs open upon every change made to obsidian

### ISSUE THREAD

**Issue by psychsatani** [mdelobelle/metadatamenu#487]
I was using the plugin for a while since yesterday and this issue did not happen. Out of nowhere I noticed two new tabs open upon any change made to obsidian. I tried to turn off commands to add file class on note creation, but that did not work. This resolved only on disabling the plugin. 

https://github.com/mdelobelle/metadatamenu/assets/78266798/acc79526-f6cc-4c14-9eea-5933c6d03349

**Comment by mdelobelle** [comment]
Some steps to try to solve: reload obsidian
go to console → application tab → indexedDB → look for metadata-menu-..... in the list → click on "delete database", reload the plugin

**Comment by psychsatani** [comment]
Thanks, deleting database worked.

**Comment by psychsatani** [comment]
The issue has quickly come back. The error in console (not sure if related, not sure if I am even copying something relevant) seems to be this: 


Error: Impossible to restore field hierarchy, check you fileclass configuration
    at FileClassFieldsView.buildSettings (plugin:metadata-menu:2867:15)
    at new FileClassFieldsView (plugin:metadata-menu:2835:10)
    at FileClassView.buildFieldsView (plugin:metadata-menu:5204:23)
    at FileClassView.buildLayout (plugin:metadata-menu:5189:10)
    at new FileClassView (plugin:metadata-menu:5179:10)
    at eval (plugin:metadata-menu:5360:33)
    at t.<anonymous> (app.js:1:1822934)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)

**Comment by mdelobelle** [comment]
thanks

i'll add a fix in a couple of hours to solve this

**Comment by mdelobelle** [comment]
Should be fixed with 0.6.10

**Comment by mdelobelle** [comment]
can you confirm?

**Comment by psychsatani** [comment]
Yes this seems to be fixed. Thanks a bunch!
