### ISSUE TITLE
[Bug] Obsidian on android unusable since most recent update

### ISSUE THREAD

**Issue by the1gofer** [mdelobelle/metadatamenu#489]
Since installing, I can't use obsidian on my android phone (Samsung s23).  The app will load, then imidealy crash.  It's difficult to say which version of the extension I have running on the phone, because I can't get into the settings to find out.

**Comment by mdelobelle** [comment]
I don't have a samsung to try to reproduce.
Could you install an old version on your desktop (0.6.7 for example) see if it sync with your mobile and work properly, then upgrade one version at a time until you encounter this issue again?

**Comment by the1gofer** [comment]
I'm not sure that would work ... the app won't load long enough to sync.  I'll try uninstalling and see what happens

**Comment by mdelobelle** [comment]
I've published a new version that has a better lifecycle management for dataview tables. this may improve the performance (0.6.11)

**Comment by the1gofer** [comment]
I'm not sure what was causing the issue, but unistalling the app and reinstalling it seems to have fixed it.

**Comment by mdelobelle** [comment]
glad to hear that. Can we close this issue?
