### ISSUE TITLE
Severe performance degradation when performing actions in Metadata Menu

### ISSUE THREAD

**Issue by gnosthi** [mdelobelle/metadatamenu#493]
# Description

Over the past couple of days, I've noticed that whenever dealing with MetadataMenu, that it seems to cause a significant amount of hanging and slowness in Obsidian. 
This seems most notable when opening FileClass fields view, adding FileClass fields, and modifying FileClass Fields. 

Here is a video showing significant slowness in the UI becoming responsive after modifying a field name.

https://youtu.be/LbsrssNoiiQ

Whenever an action is performed, the issue with performance is triggered and  'violations' begin appearing in the console. 

# System Details

OS: Arch Linux x86_64 
Host: Beastly-Beast_2.3
Kernel: 6.1.41-1-Arch 
Uptime: 9 hours, 59 mins 
Shell: zsh 5.9 
WM: awesome 
CPU: 13th Gen Intel i9-13900KS (32) @ 5.600GHz 
GPU: Intel Raptor Lake-S GT1 [UHD Graphics 770] 
GPU: NVIDIA GeForce RTX 4090 
Memory: 6857MiB / 128628MiB 
GPU Driver: Micro-Star International Co., Ltd. [MSI] Raptor Lake-S GT1 [UHD Graphics 770] [1462:7d25] 
CPU Usage: 2% 

# Obsidian Details

Obsidian version 1.5.2

# Issue Details

Violations begin to appear in the console whenever a field is edited or field editor is opened. 
Other actions in Obsidian do not produce these violations. 

```
[Violation] 'setTimeout' handler took <N>ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 4173ms
plugin:dataview:14861 [Violation] 'setTimeout' handler took 116ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 444ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 4022ms
plugin:dataview:14861 [Violation] 'setTimeout' handler took 105ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 411ms
plugin:image-captions:37 [Violation] 'message' handler took 4322ms
plugin:image-captions:37 [Violation] 'message' handler took 4237ms
[Violation] Forced reflow while executing JavaScript took 48ms
```

However, no consistent errors or exceptions occur.

This shows up more than any other: 
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'frontmatter')
    at OnFileModifyAutomatorManager.onFileModify (plugin:metaedit:5331:22)`

Here is a full trace from the moment a new field was added to the point where the UI became responsive again: 

```
plugin:metaedit:5331 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'frontmatter')
    at OnFileModifyAutomatorManager.onFileModify (plugin:metaedit:5331:22)
7
[Violation] 'setTimeout' handler took <N>ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 5824ms
plugin:dataview:14861 [Violation] 'setTimeout' handler took 396ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 573ms
app.js:1 [Violation] 'setTimeout' handler took 70ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 58ms
app.js:1 [Violation] 'setTimeout' handler took 77ms
plugin:image-captions:37 [Violation] 'setTimeout' handler took 62ms
plugin:image-captions:37 [Violation] 'message' handler took 11413ms
app.js:1 Uncaught (in promise) Error: File system operation timed out.
    at e.kill (app.js:1:542802)
    at l (app.js:1:254714)
    at c (app.js:1:254830)
2
app.js:1 Uncaught (in promise) DOMException: Transaction timed out due to inactivity.
app.js:1 Sync Error!
app.js:1 TypeError: Cannot read properties of null (reading 'send')
    at e.send (app.js:1:2653122)
    at e.<anonymous> (app.js:1:2652313)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at e.request (app.js:1:2652182)
    at e.<anonymous> (app.js:1:2649153)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
app.js:1 Uncaught (in promise) Error: Disconnected
    at e.disconnect (app.js:1:2647328)
    at t.<anonymous> (app.js:1:2626880)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at t.asyncGetServer (app.js:1:2626711)
    at t.getServer (app.js:1:2626588)
    at t.<anonymous> (app.js:1:2628303)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at t._sync (app.js:1:2628044)
    at t.<anonymous> (app.js:1:2626044)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
```

**Comment by mdelobelle** [comment]
Can you test with 0.6.11.

I've made several changes to avoid tableview being refreshed when it's not necessary → divides by 3 the time to open a tableview
The table won't refresh when the tab isn't displayed
The table won't refresh when there's a change in the fileclass. There's a button to rebuild the table after a fileclass change now. 
I've alse default hidden the "insert field" buttons. There's a button to show them now→ reduces by 30% the building time of the building time of the table

Hopefully it will improve the experience for you

**Comment by mdelobelle** [comment]
And wow, your hardware configuration is incredible!

**Comment by guix54** [comment]
Hi, I have the same problem but after your recommandations it's ok. 
(row limit 5)
I confirm the slowdown with 0.6.11 version.
mais mon ordi n'est pas survitaminé ;-)

**Comment by gnosthi** [comment]
0.6.11 Does show an increase in performance but the greatest increase came from limiting the number of records returned for the Table View.  
Once the Table view was limited to 5 everything works perfectly again. 

Thank you so much for your assistance on this! 

Happy Holidays

**Comment by guix54** [comment]
Hello, in fact not real improvements after downsizing the number of files in table view (juste one for me). My hardware configuration is very low tech... (I5-4570) perhaps a first limitation in my vault...(3500 files 1GB data)
