### ISSUE TITLE
[BUG] Metadata Menu opens on notes

### ISSUE THREAD

**Issue by Lmasey** [mdelobelle/metadatamenu#497]
I have never submitted a bug before, hopefully I am putting this in the correct location. 

When I open a new note the metadata menu options automatically appear on top. This is happening on mobile and desktop versions of Obsidian. 

![Screenshot 2023-12-21 at 4 11 23 PM](https://github.com/mdelobelle/metadatamenu/assets/121703468/3e777a32-6bff-42f0-8c71-73a1e6a64795)
![Screenshot 2023-12-26 at 10 48 11 AM](https://github.com/mdelobelle/metadatamenu/assets/121703468/e4ddb5e3-c40f-4993-b54c-f382d54be777)
![Screenshot 2023-12-21 at 10 23 16 AM](https://github.com/mdelobelle/metadatamenu/assets/121703468/f7acb47b-6d60-4e47-9e22-f79051d46334)

**Comment by mdelobelle** [comment]
Hi. You just have to toggle off "Add a fileclass after create" in the settings

**Comment by Lmasey** [comment]
I feel dumb! Thank you😂Sent from my iPhoneOn Dec 26, 2023, at 11:11 AM, mathieu ***@***.***> wrote:﻿
Hi. You just have to toggle off "Add a fileclass after create" in the settings
