### ISSUE TITLE
Asks to select fileclass for non-markdown files

### ISSUE THREAD

**Issue by AmalSalman** [mdelobelle/metadatamenu#507]
When the "Add a fileclass after create" settings option is enabled (which is a wonderful feature!) it applies to files that are not markdown like pdfs and images. When I add such files to my vault, I would like the plugin not to ask me to add a fileclass. This is especially problematic when multiple pdfs or images are added to the vault at once, then I get that fileclass selection screen multiple times (over each other) and have to exit out of each one of them.

Thank you for this incredible plugin!

**Comment by mdelobelle** [comment]
good catch. will fix it in the next release

**Comment by AmalSalman** [comment]
Great, thank you!

**Comment by mdelobelle** [comment]
fixed in 0.7.0
