### ISSUE TITLE
What is the limit under nested properties?

### ISSUE THREAD

**Issue by AESakhawy** [mdelobelle/metadatamenu#509]
Hello I was wondering what the limit of properties I can have under one nested property?

for example 

---
x:
 1
 2
 3
 ....
---

**Comment by AESakhawy** [comment]
I have a pretty long list and the bottom 6 have <missing>

**Comment by mdelobelle** [comment]
There's no limit

> I have a pretty long list and the bottom 6 have

did you finish your sentence? I don't understand what's the issue you are facing?

**Comment by AESakhawy** [comment]
Sorry I meant the bottom 6say <missing>

**Comment by AESakhawy** [comment]
> There's no limit
> 
> > I have a pretty long list and the bottom 6 have
> 
> did you finish your sentence? I don't understand what's the issue you are facing?

**Comment by AESakhawy** [comment]
I meant to say it says missing
