### ISSUE TITLE
MultiFile Fileclass Field with Comma in Filename

### ISSUE THREAD

**Issue by ipxfer** [mdelobelle/metadatamenu#515]
MultiFile fileclass selecting filename containing a comma displays as broken link.  I'm using filename format "lastname, firstname.md". 

![image](https://github.com/mdelobelle/metadatamenu/assets/42286468/1e0d31d5-cbf2-4338-92f4-7e1577676a71)

![image](https://github.com/mdelobelle/metadatamenu/assets/42286468/bd96a657-abfe-4e55-9340-c003adad52bb)

As shown, the single File field is working.  Just the MultiFile is not working.

**Comment by mdelobelle** [comment]
fixed in 0.7.7
