### ISSUE TITLE
Icons in fileClass not being respected

### ISSUE THREAD

**Issue by matthewturk** [mdelobelle/metadatamenu#519]
Hi!  I'm trying to debug why icons have disappeared for me in recent Obsidian versions.  I'm on the current version of metadatamenu (0.7.1) and Obsidian (1.5.3) and the icons specified in fileClass (in this case, `clipboard-list`) are not showing up in my file explorer.

![image](https://github.com/mdelobelle/metadatamenu/assets/89019/52b84721-b56d-4e69-ab90-b968d71474b4)

These all have the `fileClass` `meeting-notes` which has the property `icon: clipboard-list`.  The "fileClass settings" view suggests I have this correct:

![image](https://github.com/mdelobelle/metadatamenu/assets/89019/1a970277-6ba1-41f3-9917-6f9b4de55b57)

I assume this is on my end, *however*, I haven't been able to determine which theme or plugin is causing the conflict.  I've attempted to turn them off (and started with the most likely culprits of "Style Settings" and the "ITS-Theme") but nothing restores the file icon.

Digging into the CSS, it looks like the variable for the icon is set to `var(--file-icon)` but I don't know how to dig further in to determine where this variable is being set, and if it's being overridden somehow.  I understand if you close this for being out of scope, but if there are any insights you can share or ways I can contribute to the project to help surface the cause I appreciate suggestions.

**Comment by mdelobelle** [comment]
Hi. the fileClass icon is displayed after the file name, not before. The icons displayed in the image aren't managed by metadata menu.

**Comment by matthewturk** [comment]
Thank you -- that gave me just the push I needed.  I discovered that these were only displayed when the "Metadata Menu Buttons" were turned on.  I should have known this, but didn't.  Now everything is great!
