### ISSUE TITLE
Ability to change the name of the object lists

### ISSUE THREAD

**Issue by Paining1** [mdelobelle/metadatamenu#523]
Perhaps a feature that allows us to change the name of the object lists. We can keep the [0], [1], [2] for identification purpsoses. But having the ability to change the name would be amazing.

**Comment by mdelobelle** [comment]
Good idea.
I could give the possibility to set a display name of each item based on the values of the children fields WDYT

Let's say you have an ObjectList "Attendees"
With children: "Name", "Position", "Company"

so in the ObjectList setting you would put:
Display label: `{{Name}} - {{Company}}`

And therefore the [0], [1], ... would be replaced with [John - ACME] , [Anne - NewCo], ....

WDYT

**Comment by Paining1** [comment]
Yea this is perfect. Could there also be on option to only limit the name to just one of the children fields as well?

**Comment by mdelobelle** [comment]
Will be released in 0.8.0
