### ISSUE TITLE
Is it possible to nest object lists or is it an error on my end?

### ISSUE THREAD

**Issue by Paining1** [mdelobelle/metadatamenu#529]
Hello, I was wondering if nesting object lists was possible, or if im just having problems

**Comment by Paining1** [comment]
"Object and Object List field can also have parent, therefore you can nest "infinitely" "

Must be an issue on my end, let me keep trying...

**Comment by Paining1** [comment]
![image](https://github.com/mdelobelle/metadatamenu/assets/155585187/bb6da0ff-9ee3-44e4-af2a-dc51695cbce2)

I keep receiving this issue, even though my fields are good:

![image](https://github.com/mdelobelle/metadatamenu/assets/155585187/9355c47a-6253-4096-b9c3-28a1913ddd94)

**Comment by Paining1** [comment]
This issue only occurs with object list nesting, objects work fine

**Comment by mdelobelle** [comment]
Good catch. should be fixed : 0.7.4
