### ISSUE TITLE
Feature Request: Option to always show dataview field table controls

### ISSUE THREAD

**Issue by leoccyao** [mdelobelle/metadatamenu#53]
I'm currently working on my todo management system in Obsidian, and recently started using your plugin. I'm already impressed by how cleanly the `fieldModifier` method amends the dataview table interface, while also adding a lot of power to edit the underlying fields!

However, I would love to have an option to have the edit and selection options for fields always visible, to allow for easier updating of fields from the table. I know that other users may prefer the cleaner interface that currently is an option, so perhaps this would be better implemented behind an option. Perhaps another parameter passed to the `fieldModifier` function?

Current view:

![image](https://user-images.githubusercontent.com/45076643/184559962-762a919e-2260-413b-b1b5-988db85ae036.png)

Proposed view available as an option, even when not hovering (shows dropdown, and edit button):

![image](https://user-images.githubusercontent.com/45076643/184559993-eb49cda0-1030-4fcf-b822-e690615f1868.png)

This change would allow this already awesome plugin to be an even better competitor to Notion tables, ClickUp, and other DB folder plugins, for users finding those options limited.

**Comment by mdelobelle** [comment]
Hi. Thank you for your feedback.
This is a good idea, I will include it in the roadmap

**Comment by mdelobelle** [comment]
Shipped in 0.1.12

**Comment by leoccyao** [comment]
Works perfectly, thank you so much!
