### ISSUE TITLE
Is there an undo button for deleted fields?

### ISSUE THREAD

**Issue by Paining1** [mdelobelle/metadatamenu#532]
Is it possible to have an undo button or a trash bin for deleted fields, it is so easy to accidentally delete them.

**Comment by Paining1** [comment]
Or maybe even a confirmation box that appears that can be enabled in the settings

**Comment by mdelobelle** [comment]
> Or maybe even a confirmation box that appears that can be enabled in the settings

A confirmation box wil be added in the next version when removing a field from the fileclass view
