### ISSUE TITLE
[bug] Table error in one fileclass.  All others work. 

### ISSUE THREAD

**Issue by thecookiemomma** [mdelobelle/metadatamenu#535]
I don't know what it is about this one file class.  It keeps getting errors like the one below.  I thought maybe it was because it was a nested tag, but it's not, because the other nested tags work fine.  This is inside the table view. 

![image](https://github.com/mdelobelle/metadatamenu/assets/15720918/a6e255bc-2ab3-477f-b792-42dc90ccbd94)

other notable things I've tried:  The dataview query for the same thing works fine. I've got it in like two or three other notes.  I changed some file names that had punctuation in them.  Didn't fix.  
I have turned off a couple plugins (namely pane relief and one other I can't remember) to see if that helped.  It didn't.

**Comment by mdelobelle** [comment]
Could you paste the content of the fileClass file? I would like to check the configuration of your Multi type fields.
One of them seems to be the root cause of the problem

**Comment by thecookiemomma** [comment]
I deleted the file and remade it, and it seems to work now. Thank you. It might have been that I had the same field in a parent class.
