### ISSUE TITLE
some fields not regonized

### ISSUE THREAD

**Issue by the1gofer** [mdelobelle/metadatamenu#537]
I'm using a field called `note(s)`.  

Metate data menu doesn't seem to like that. 

<img width="996" alt="Screenshot 2024-01-13 at 10 26 17 AM" src="https://github.com/mdelobelle/metadatamenu/assets/2140724/e7f5ade3-591d-4fd8-b048-795d9a4ceed8">

as you can see in this screenshot  the field exists ... 

It also causes issues becuase if I click add missing fields as front matter it will delete anything saved in that field.

**Comment by the1gofer** [comment]
It seems to be related to the `(s)`.   I have other fields with the same format that have the same issue.

**Comment by fidrick** [comment]
Thanks for posting @the1gofer. I had exactly the same issue with '(s)' added to infer plural optionality in the Field Name. Removing the parentheses solved the issue for me too :thumbsup:

**Comment by mdelobelle** [comment]
Hi. You're right, since the parenthesis in the field name are conflicting with the dataview inline-field syntax `(fieldname:: value)` they where excluded from the parsing. but I can have them parsed in frontmatter. Will include that in the next version

**Comment by mdelobelle** [comment]
fixed in 0.8.1
