### ISSUE TITLE
Feature Request: Date handling improvements

### ISSUE THREAD

**Issue by leoccyao** [mdelobelle/metadatamenu#54]
I've recently noticed a small issue with editing dates in Dataview tables:

Let's say I have define a date in frontmatter:

```yaml
fileClass: schema-task
created: 2022-08-14T16:32:00-04
due: 2022-08-15
status: Open
```

And it displays nicely in the table:

![image](https://user-images.githubusercontent.com/45076643/184560350-c74c3868-e847-421c-9c12-e0f3e0cdc85d.png)

However, when I hit the edit button, the input is initially filled with the full `DateTime`:

![image](https://user-images.githubusercontent.com/45076643/184560377-614014bb-e308-4053-89d6-3920d56b4b1b.png)

This seems to happen as the initial value for the input is whatever the value the Dataview API gives (in https://github.com/mdelobelle/metadatamenu/blob/4ff5516bca3710c94887c0f1eb85105332ec96fd/src/fields/fieldManagers/InputField.ts#L63). As Dataview internally coerces date-esque strings to Luxon `DateTime` objects, when these are serialized to strings via `toString`, we get a much longer representation. Checking the result of the `toString` method on a Luxon object confirms this:
```js
> dv.current().due.toString()
2022-08-15T00:00:00.000-04:00
```
And if I hit enter, the `due` field is replaced by this longer representation.

It's okay to work around this on desktop (select all and delete), but definitely more a hassle on mobile.

Also interestingly, using the modal to update the `due` field doesn't run into this issue: 

![image](https://user-images.githubusercontent.com/45076643/184560773-1e5f6fb5-dff1-4ee9-8820-1ac05b07361c.png)

Perhaps the easiest way to fix this is to use whatever logic is present in the modal to get the raw input value, to initially populate the input in the Dataview table.

---

Ideally, we'd be able to have a Date field type specifically for working with dates (and maybe times as well). Editing Date type fields either in the modal or in a Dataview table could open some form of date picker. If this is better as a separate issue, feel free to split it and mention me into the discussion!

Thanks so much for bringing first-class support to many different types of fields (boolean, select, even multi-choice); I'm hoping that datetimes (useful for due dates, reminders, calendar events, etc.) can also get comprehensive support as well!

**Comment by mdelobelle** [comment]
You're right, dataview is automatically detecting the date format and converting it into a luxon date object, whereas the modal has no logic at all 😅 so it doesn't convert it unless you toggle the date checkbox.

I was thinking of DateTime as a good candidate for the next type the plugin should manage. It looks like it the right time to do it. I'll add it on the roadmap.

This way i can remove the date toggle from input type modal and Input will then really be a "raw" input type with no validation or formatting logic attached to it.

**Comment by leoccyao** [comment]
Amazing! Interestingly, I had some issues with 0.1.15 with rendering of the DataviewJS table, but those seem to have gone away with 0.1.16.

This is just a small nitpick, but I've noticed that the same issue, with Dataview automatically converting to Luxon format when opening the modal, still exists. If I immediately save from the modal, the date processing code still writes the date in my desired format (for me, YYYY-MM-DD), but when shown in the modal, it still shows as the longer representation:

![image](https://user-images.githubusercontent.com/45076643/185717164-33e465f6-df50-417c-8375-6a0d5a6bfa25.png)

Fixable either via getting the raw input value or by checking if Dataview is giving us a Luxon object (and running format on it if it is) before display?
