### ISSUE TITLE
missing files count - tableview

### ISSUE THREAD

**Issue by sdaognklwb** [mdelobelle/metadatamenu#553]
Hiya. Thanks for making the plugin. I really appreciate it. 

I am just wondering how can I see the total number of files included in the list? I have seen the tutorials/guides and they all have it. But I am not sure what did I do wrong as it did not show up. I suspect it is to do with the recent update and I am just wondering if there's any option which can let me see the total files?

Thanks!

<img width="830" alt="Screenshot 2024-01-29 at 13 33 17" src="https://github.com/mdelobelle/metadatamenu/assets/100029725/7a71d640-1afc-46f3-b4ad-76b7c0cfe476">
The circled area is supposedly to have the total number of files, according to various youtube guides. Now they are gone.

**Comment by Felharrim** [comment]
You can limit the number of rows displayed on a page. And then at the top there will be a list of pages with the number of lines in it, if this number exceeds the limit of lines on the page

**Comment by sdaognklwb** [comment]
@Felharrim Thanks for the tip. I really appreciate it ^o^

I do use it as a workaround for now but it is perhaps not the most intuitive for long-term use/large scale database. I am just wondering if the creator would be interested in fixing it and bringing the feature back, as shown in the previous versions.

**Comment by mdelobelle** [comment]
Will be fixed in the next version

**Comment by sdaognklwb** [comment]
thanks @mdelobelle
