### ISSUE TITLE
Sort not working with 'file' type

### ISSUE THREAD

**Issue by symph0nic** [mdelobelle/metadatamenu#56]
Hello! Something strange is happening when I try to use the 'file' type - the query:

dv.pages('#client and -"templates"').sort(p => p.file.name, 'asc')

...doesn't sort correctly - it sorts in descending order no matter what I do. I've tested the query works correctly in a normal page.

Am I doing something dumb...?

**Comment by mdelobelle** [comment]
Hi, it looks like we can't sort the results and having the order presisted in the fuzzy suggester provided by Obsidian api. I suppose that it's linked to how the core fuzzy search function is working. I'll ask the developer if there's a way to do it. In the meantime I've removed this "sort" capability from the documentation of the plugin

**Comment by symph0nic** [comment]
Ok, makes sense. Glad it wasn't just me!

**Comment by mdelobelle** [comment]
Didn't find a way to do that. So I will close this issue and check the obsidian api for capability to do that in the next versions

**Comment by mdelobelle** [comment]
I've found a way to do this, will include in the next version
