### ISSUE TITLE
Number fields don't sort correctly in table view

### ISSUE THREAD

**Issue by scatterlogical** [mdelobelle/metadatamenu#560]
Number fields are sorting as string types, ie: 1,2,22,3,320,4 etc. rather than sequentially. I assume this is down to javascript's ridiculous dafault sort function. Additionally, I am unable to correct this with a custom filter function, as the 'current' parameter doesn't supply valid objects from the table view.

**Comment by mdelobelle** [comment]
> Number fields are sorting as string types

will be fixed in the next version
