### ISSUE TITLE
Metadata menu opens on Obsidian startup

### ISSUE THREAD

**Issue by ziahassan** [mdelobelle/metadatamenu#568]
I've noticed that one of my classes opens up automatically everytime I open obsidian on Desktop or mobile. Not sure what I did to inspire this behavior but it slows down mobile a lot. I looked at the global settings as well as the class settings and not sure.

**Comment by mdelobelle** [comment]
Do you have a tab opened on a fileclass view in your mobile app?
I'm not 100% sure of how the mobile app sequence works when one opens Obsidian but if it's trigerring a relaunch of the plugin, then - like on desktop - it's looking for tabs that were opened on a fileclass view prior to the shut down of the app and automatically reopen them at start.
You could ensure that you close the fileclass view's tab when you don't need it anymore on mobile to prevent this unwanted behaviour

**Comment by mdelobelle** [comment]
Glad to hear that. I'll close this issue. If it's happening again, you could also try to disable the plugin, close all fileclass tabs, enable the plugin. This should flush the cache database that may be in a weird state.
