### ISSUE TITLE
Dataview every kind of field shows the same as input field

### ISSUE THREAD

**Issue by AndyLiu9** [mdelobelle/metadatamenu#57]
With the latest version of Dataview and Metadata menu, seems every kind of field (single selection, boolean, etc.) rendered the same as input (a pen shows instead of the drop down list or checkbox).

**Comment by mdelobelle** [comment]
Hi, I'm not experiencing this behaviour:
Obsidian 0.15.9,
Dataview 0.5.41,
Metadata Menu 0.1.13

Could you make a screenshot of your settings, your dataviewjs codeblock and the fileClass if you have one defined ?

**Comment by AndyLiu9** [comment]
Hi, thanks for your reply. I tried again and finally found that I made mistakes on case of letters. Correct one should be `f(dv, p, "Status")` but I wrongly typed `f(dv, p, "status")`.
Sorry for causing your trouble. Thanks for your plug-in, currently I use it for managing several of my projects and it really helps me a lot!
