### ISSUE TITLE
"@" symbol causing Multi-Select field not to work?

### ISSUE THREAD

**Issue by mwisnefsky** [mdelobelle/metadatamenu#575]
I have a folder of notes that start with "@" (how I differentiate people).  I am trying to add a field to notes that allows me to select people from that folder, but it doesn't let me select any file that starts with the "@" symbol.

I click the checkmark and nothing happens.

**Comment by mdelobelle** [comment]
Hi, I can't reproduce the issue.
Could you paste here some screenshot of the steps you're trying to achieve and any error that would be logged in the console?

**Comment by mdelobelle** [comment]
thanks, I didn't try it in frontmatter but inline, that's the reason why I couldn't reproduce...
Well it seems that it is a limitation from YAML

I would recommend to remove the "@" before the name of your persons files to comply with YAML syntax.
You could use "supercharged links" plugin (also one of my plugins) to add a visual way to identify "person" files (with a color or an emoji) without cluttering the name of your file

**Comment by mwisnefsky** [comment]
Ah, gotcha, thanks for looking into it!
