### ISSUE TITLE
Mobile app crashes when you try to select a link from metadata menu table

### ISSUE THREAD

**Issue by cameronj86** [mdelobelle/metadatamenu#576]
https://streamable.com/u3yund

To replicate, create a table and then try to access one of the links through the mobile app by clicking it

**Comment by RaviVanam** [comment]
I'm also facing the same issue

**Comment by mdelobelle** [comment]
Hi I don't have an Android to try to reproduce but U have notice another behavior since the last mobile version update on IOS.
I've made a modification that fixes this behavior on IOS, maybe this will also fix this issue on Android.
I will push it in the next beta release

**Comment by mdelobelle** [comment]
I've release the version 0.8.0 can you test on your android mobile if this fixes your issue?

**Comment by RaviVanam** [comment]
Thanks for the release! looks like it's working now! 😀

**Comment by RaviVanam** [comment]
Sorting doesn't seem to work properly after version 0.8.0. Can you look into it. I was sorting based on date.

**Comment by cameronj86** [comment]
Just gave it a shot myself and it works for me! 

As far as I can tell I don't have any glitches with the sort functionality either... On the contrary I can finally sort numerical values so I'm guessing that was in the beta as well 🙌🏾. 

There is a slight visual bug that might be new where the unique value is off kilter when you scroll: ![Screenshot_2024-02-17-10-08-32-586_md.obsidian.jpg](https://github.com/mdelobelle/metadatamenu/assets/8635023/bbf56bac-35e5-4934-92b5-44fba9398163)

My uneducated guess is that the unique values count might be throwing off the functionality for the column. Personally this is a much lower priority for me because I can still complete my workflow but let me know if you want me to load a separate ticket

**Comment by RaviVanam** [comment]
hi @cameronj86 are u sorting using filename? can u try sorting a field that is set as date in metaclassfields.

**Comment by cameronj86** [comment]
> hi @cameronj86 are u sorting using filename? can u try sorting a field that is set as date in metaclassfields. 

Hey. 

I don't have any fields that are set as date.  If I recall correctly, there's a potential conflict between obsidian's date and metadata menu plugin's date, especially if time is used, so all of my date columns are technically just text fields

**Comment by RaviVanam** [comment]
I was sorting obsidian's date (time is used) before. It worked fine. But started to break after the new release. Tried it again on another vault that was running on older version. it was working fine, updated to 0.8.0 and it started to break there too.

**Comment by RaviVanam** [comment]
I opened an issue for the sorting issue. This thread can be closed.
