### ISSUE TITLE
Fileclass Settings won't save after recent insider update

### ISSUE THREAD

**Issue by dml0sc** [mdelobelle/metadatamenu#578]
It seems that after the recent insider update, Fileclass Settings are not responsive. I am experiencing issues with the Button Icon (which will not change and after saving goes back to default) and parent file classes which I can select but are not acknowledged. In the Release Note of the 1.5.5 Obsidian insider update, I read: 'File Explorer and Tags pane both received a small code refactor. This might affect some plugins that rely on the internal JS structure'. Could that cause the problem?

**Comment by mdelobelle** [comment]
Could you test with 0.8.0-beta-4 please? Do you still encounter this issue?
https://github.com/mdelobelle/metadatamenu/releases/tag/0.8.0-beta-4

**Comment by Felharrim** [comment]
I faced the same problem. Icons assigned to properties in a class are not displayed. Everything works by default. I also checked it with the beta version. All the same.

**Comment by mdelobelle** [comment]
I can't reproduce this issue.
Could you paste some screen shots of what is happening? (and any error console that may be printed when you try to change an icon?)

**Comment by Felharrim** [comment]
Setting Class properties
![image](https://github.com/mdelobelle/metadatamenu/assets/151380890/d972febd-0dda-4830-ad3e-64ff2e4c59fb)
view window setting
![image](https://github.com/mdelobelle/metadatamenu/assets/151380890/f8fe2003-4ce8-4c7d-b076-d351a6fe053f)
or from context menu
![image](https://github.com/mdelobelle/metadatamenu/assets/151380890/60147cd4-6d61-454d-82ca-2a4486190ff6)

**Comment by mdelobelle** [comment]
This is not a bug. Unlike the icon for the fileclass button, the icons for field actions (that you have underlined in your screenshots) have always been fixed and cannot be customized.

**Comment by Felharrim** [comment]
Thank you! This helped clarify the point. But why is there no information about this in the interface itself? (for example - Icon settings for the mobile version)

**Comment by mdelobelle** [comment]
fair point. I'll improve that in the next version

**Comment by mdelobelle** [comment]
CHanged in 0.8.1
