### ISSUE TITLE
[FR] Deselect file in singlefilemodal

### ISSUE THREAD

**Issue by renekalff** [mdelobelle/metadatamenu#584]
Currently it is not possible to "deselect" the value of the file field type. The multifile field modal has a button to empty the value. I think it would be the most consistent to have the same button on the singlefilemodel. 

An other option would be to be able to "deselect" the currently selected file so clicking on the file with the checkmark behind it. The current behaviour is that it stays selected. This would probably also require that the currently selected file is always on the top of the list to assist in deselecting it.

**Comment by mdelobelle** [comment]
fair point. I'll add that in the next version
