### ISSUE TITLE
Sorting order of MultiFile and File types is broken

### ISSUE THREAD

**Issue by dml0sc** [mdelobelle/metadatamenu#601]
In MultiFile and File FileTypes, there is a handy option to sort the order of the links by entering a.basename < b.basename ? 1: -1 OR a.basename > b.basename ? 1: -1. This worked perfectly but not anymore – the order is random (even with the 0.8.0 beta 4 version installed)

**Comment by mAAdhaTTah** [comment]
I am also experiencing this.

**Comment by mdelobelle** [comment]
good catch, will be fixed in the next release

**Comment by mdelobelle** [comment]
can you test the 0.8.4-beta-1 release?

**Comment by dml0sc** [comment]
> can you test the 0.8.4-beta-1 release?

It works like a gem – Thank you
a.basename > b.basename ? 1: -1 retrieves files in alphabetical order A-Z
a.basename < b.basename ? 1: -1 retrieves files in alphabetical order Z-A
