### ISSUE TITLE
Failed to install plugin "Medatada Menu"

### ISSUE THREAD

**Issue by 23426356587** [mdelobelle/metadatamenu#627]
Hello - I'm seeing this error "Failed to install plugin "Medatada Menu"" on my main and testing vault.

I'm not super technical but I can follow directions to troubleshoot if anyone can help.

Thank you!

**Comment by mdelobelle** [comment]
Hi do you see any error in the console?

**Comment by 23426356587** [comment]
I saw the error on the top right corner, didn't go into console.

Just now, I went to open the console and try it again and ... it successfully installed

I have not restarted the app or my machine... not sure why it would work all of a sudden... but thank you!

**Comment by 23426356587** [comment]
Yay!
