### ISSUE TITLE
Fields Indexing Status icon keep showing even if disabled

### ISSUE THREAD

**Issue by rebornsick** [mdelobelle/metadatamenu#639]
Disabled `Fields Indexing Status` option and restart Obsidian, the indexing status icon still shows up in status bar

<img width="887" alt="Snipaste_2024-03-16_15-48-46" src="https://github.com/mdelobelle/metadatamenu/assets/28842872/4842e225-58e8-440d-9a07-34a67224312c">

**Comment by mdelobelle** [comment]
good catch, will be fixed in the next version

**Comment by mdelobelle** [comment]
fixed in 0.8.6
