### ISSUE TITLE
Bug: cannot set an empty Date field

### ISSUE THREAD

**Issue by leoccyao** [mdelobelle/metadatamenu#65]
Very happy that the Date modal has verification for parsing valid dates! But but... what if my task doesn't have a due date anymore? Am I stuck in overdue-task purgatory forever?

![image](https://user-images.githubusercontent.com/45076643/185717562-54c06bb9-ebc8-4647-8ea5-94a8dcb7727c.png)

Possible fixes:
- Either allow completely empty input to clear the field by default, or
- For more customizability, add a new option `allowEmptyDate` perhaps to control the behavior (true allows a completely empty input, false retains current behavior)

**Comment by mdelobelle** [comment]
fixed in 0.1.20
