### ISSUE TITLE
Feature Request: Control options available for a field using frontmatter

### ISSUE THREAD

**Issue by matthewturk** [mdelobelle/metadatamenu#68]
Hi!  I'd very much like to be able to use metadatamenu to be able to control the options available for me via frontmatter metadata.  For instance, if I have a file where I have something like:

```
---
attendees:
 - Me
 - Someone Else
 - Another Person
```

I'd like to be able to say that all instances of the field `assigned` should be chosen from that list.  So, if I start to do `[assigned:: ` in the body of the note, my available options should be drawn from `Me`, `Someone Else` and `Another Person`.  I watched the videos and wasn't able to figure out how to do this, although I think it may be possible somehow with the `dv` API.  Is it possible to make this work as a built-in field type?

Thank you!

**Comment by AtlcatlQ** [comment]
You just have to create it in settings of the plugin > Preset Field Settings. Choose the name of the field, then set the type to: "Accept a value from a list". Add the preset options and you'll get what you want.

Alternative in FileClass Settings, you could set a directory where all files of that directory will be used as "types" of notes you can even choose how the name of the field is called (examples: category, type). To set the fields for that specific type of note, first you have to have a file with the name of the type of note, then go to editor menu and select `manage <type> fields` then you just have to configure like above. 

Hope you find this useful.

**Comment by matthewturk** [comment]
@AtlcatlQ Thank you -- I was hoping I could have the fields defined *within* a note, so that my metadata menu would draw the options from within the note (for instance, if meeting attendance changed each time.)  I'm not sure I can do that with what you suggest, but I will give it a shot and explore it.

**Comment by AtlcatlQ** [comment]
The thing is... You may want to use the same options for more than one file, so having the list only in one place is more useful than have it copied in a lot places.

Will it help you if I add screenshots?

**Comment by matthewturk** [comment]
@AtlcatlQ no, I think I understand.  I think my workflow doesn't quite fit with it as-is, so I should rethink the workflow to integrate.

**Comment by AtlcatlQ** [comment]
Oh, okay, maybe a template with the predef options would work better for you
