### ISSUE TITLE
remove "X" when using `options: {alwaysOn: true}`

### ISSUE THREAD

**Issue by imeed166** [mdelobelle/metadatamenu#72]
In dataview, when using select options and the option `options: {alwaysOn: true}`. I don't think the user want to revert to the default view : `options: {alwaysOn: false}` so I don't see the utility of displaying an "X" after every select.
In my opinion, the X should be removed just like in your [video](https://youtu.be/7bvIAkJf0OE?t=606)
#### old
![image](https://user-images.githubusercontent.com/38974541/186873743-ce21f2a3-f0a0-4b7f-b2cc-85d1cef7cd1b.png)
#### new
![image](https://user-images.githubusercontent.com/38974541/186875771-bdf193d2-4519-4a57-8e21-27e15458cbe5.png)

That would also help when viewing the table in mobile, the "X" takes too much space.

**Comment by imeed166** [comment]
Or maybe add an option to disable the "X", something like`options: {showX: false}`

**Comment by balola** [comment]
Yes, it is a problem.
The last 3 are right, it is after clicking (closing) the "X"

![image](https://user-images.githubusercontent.com/24825268/198209042-d0cec06e-4893-4566-87c1-c090464afba1.png)

**Comment by mdelobelle** [comment]
solved in a previous version
now the select and multi select fields buttons open a dedicated modal
