### ISSUE TITLE
FR: Support for tags

### ISSUE THREAD

**Issue by spiritualgeek** [mdelobelle/metadatamenu#76]
Support for tags inside frontmatter would push me to use this plugin

So:

```
tag/optiona
tag/optionb
tag/optionc
```

Therefore, if typing
`- tag/`

It should provide the 3 aforementioned options to select

Thanks

**Comment by mdelobelle** [comment]
Is it the same idea as #112 ?

**Comment by spiritualgeek** [comment]
Not totally related from what I can see, although there is brief mention of it
https://github.com/mdelobelle/metadatamenu/issues/112#issuecomment-1263369760

It's the only thing preventing me from putting your plugin to good use
