### ISSUE TITLE
To use local menu (right click) to choose predefined fieds

### ISSUE THREAD

**Issue by balola** [mdelobelle/metadatamenu#80]
Hi, 

It would be more effective to choose predefined fields from local menu (right click).
The note menu is very long, packed and harder to click on it.

Thanks
Füles

**Comment by AtlcatlQ** [comment]
I would like that feature too. 

I think an option in the settings of the field like `myField:: {"type":"type","options":{"Options"},"showInContextMenu":"true"}` would make easy to manage this.

**Comment by balola** [comment]
Great, waiting for it.
Füles

**Comment by AtlcatlQ** [comment]
I just was suggesting how that feature could be done, I don't think feature is included already. Please, reopen this issue and wait until it gets included into the plugin to close it.
