### ISSUE TITLE
Add to frontmatter problem - invalid YAML

### ISSUE THREAD

**Issue by balola** [mdelobelle/metadatamenu#81]
Hi,

It shows invalid Yaml problem if I use ```:``` caracter in field template.
I don't belive that it is a real problem, just can not be used this solution in this case.

Füles

---

Temp in field:
> version:: {"type":"Input","options":{"template":"Ver: {{version}}"}}

Add to frontmatter:
![image](https://user-images.githubusercontent.com/24825268/187618024-96685052-a915-42da-b1c8-0c9cfba0c43d.png)

Created Metadata:
> version: Ver: 4.4

Result:
![image](https://user-images.githubusercontent.com/24825268/187617770-c0335927-bee7-44b8-8f30-0e9aba820438.png)

**Comment by AtlcatlQ** [comment]
Try putting the values inside double quotation marks

**Comment by balola** [comment]
Hi,
After update to 0.1.22 all of my metadata menu items disappeared from menus.
Füles
________________________________

**Comment by mdelobelle** [comment]
do you have dataview plugin installed?
can you post a screenshot?

**Comment by balola** [comment]
________________________________

**Comment by balola** [comment]
I have dataview plugin, everything before update did work.
________________________________

**Comment by mdelobelle** [comment]
I've released a hotfix, can you retry?

**Comment by balola** [comment]
I changed the main, manifest, style files but nothing changed, no metadata in menus.
________________________________

**Comment by mdelobelle** [comment]
can you paste a screenshot of one note with metadata, a screenshot of your settings and , if you have a fileClass defined for this note, a screenshot of this fileClass?

**Comment by balola** [comment]
I updated to 0.1.31, but nothing changed, I have no menus on right-click.
Füles

**Comment by balola** [comment]
Hi,

What is interesting, that your icons and components changed. Some part shifted a little and I cannot see what I could (the same I found in your help) before update.

![image](https://user-images.githubusercontent.com/24825268/188437827-ba280be9-1f03-42fb-b93e-726991d59786.png)

Füles

**Comment by mdelobelle** [comment]
I think I've found a workaround: can you install the latest version (0.1.32) and try again?

**Comment by balola** [comment]
Hi,

Great, works again.
Thanks
Füles

**Comment by balola** [comment]
But autocomplete works.
________________________________
