### ISSUE TITLE
Value disappear in number field when try to update

### ISSUE THREAD

**Issue by SebastianoRegini** [mdelobelle/metadatamenu#82]
![number disapp](https://user-images.githubusercontent.com/48477163/188015458-c08ebc43-572c-4766-b5cf-67393acee6b7.gif)
When a number is set and I try to edit with the "update" menu voice, the number isn't stored in the popup window.
Increasing function works, as shown.

**Comment by mdelobelle** [comment]
Hi, good catch. will be fixed in the next release

**Comment by mdelobelle** [comment]
fixed in 0.1.22x
