### ISSUE TITLE
Support updating field at section, cursor and frontmatter

### ISSUE THREAD

**Issue by wenlzhang** [mdelobelle/metadatamenu#88]
Currently, one can Add field at section, cursor, frontmatter in the context menu. It would be great if one can also update these. This way, only those are defined can show up when updating, e.g. a field at cursor.

**Comment by mdelobelle** [comment]
I don't get the difference with #91 . could you develop a little bit your idea?

**Comment by wenlzhang** [comment]
> I don't get the difference with #91 . could you develop a little bit your idea?

Indeed. It seems a little overlapped as I see it now. Closing this for now. Maybe I would re-open it when having more thoughts on this.
