### ISSUE TITLE
Field names with spaces cannot be added to Globally ignored fields

### ISSUE THREAD

**Issue by wenlzhang** [mdelobelle/metadatamenu#89]
For instance, I would like to add "created at" to the ignored list. However, once I do that it would be saved as "createdat". This means that the desired field "created at" cannot be correctly ignored.

**Comment by mdelobelle** [comment]
good catch, will fix that in the next release

**Comment by mdelobelle** [comment]
this os fixed since version 0.1.32. Can you check that it is working as expected?

**Comment by wenlzhang** [comment]
Yes. It's working for me now.
