### ISSUE TITLE
Distinguish inline fields and other fields

### ISSUE THREAD

**Issue by wenlzhang** [mdelobelle/metadatamenu#90]
It would be great if one distinguish inline fields, e.g. `[p::1]`, with Dataview fields and front matter fields as they may have different purposes. For instance, I use the inline field for denoting task priorities for use with Dataview.

Therefore, it would be great if the following can be achieved:

- One can define inline fields differently from other fields
- When right click on an inline field, only preset inline fields would be suggested, not other fields.

**Comment by mdelobelle** [comment]
I think that with your issue #91 this won't be necessary: only the option for the current line's field will be proposed. Does that make sense?

**Comment by wenlzhang** [comment]
> I think that with your issue #91 this won't be necessary: only the option for the current line's field will be proposed. Does that make sense?

Thanks for the prompt reply!

Yes. This feature does not seem necessary any more.
