### ISSUE TITLE
Controls are not working anymore (for me)

### ISSUE THREAD

**Issue by Asetnozama** [mdelobelle/metadatamenu#94]
Hello,
First of all, thank your for this great plugin!!

Now my problem, after the last update or the update before the ways to change the metadata no longer work. I can only go through it by going into the command palette.
So there is no right click, file explorer, note, calendar and context menu of a link. I know for sure it worked before, but now it just disappeared from the context menu. I'm using version 015.9 of Obsidian, your latest plugin and the minimal theme. Switching to the default theme and reinstalling the plugin didn't solve the problem. 
Do you maybe know what's going on?

Thank you very much!

**Comment by mdelobelle** [comment]
Hi, do you have dataview plugin installed and enabled?

**Comment by mdelobelle** [comment]
and another question: which OS are using?

**Comment by Asetnozama** [comment]
Hi, thank you for your quick reply.
I've the dataview plugin installed and enabled and running Obsidian on Windows 11

The funny thing is, on my iPhone (so the mobile app) it's working

**Comment by mdelobelle** [comment]
Thanks. I thibk we've narrowed the  problem.
I'm developping on macOS, and I've indeed changed the way menus are displayed. So maybe therés something Win11 doesn't like.
I'll try to ger my hands on a PC and see if I can fix this.
Does by any chance the console throw an error that you could paste here?

**Comment by Asetnozama** [comment]
Hi,
That could be the issue indeed!
I really would like to help you, but I don't know how the search for an error in the console. I'm sorry :-(

**Comment by mdelobelle** [comment]
I think I've found a workaround: can you install the last version (0.1.32) and try again?

**Comment by Asetnozama** [comment]
> I think I've found a workaround: can you install the latest version (0.1.32) and try again?

It's working again!!!
Thank you very much! you are a genius

**Comment by mdelobelle** [comment]
I'm glad to hear that! I'll close the issue
