### ISSUE TITLE
Feature request: Log metadata updates

### ISSUE THREAD

**Issue by leoccyao** [mdelobelle/metadatamenu#97]
Thanks again for all the continued updates and new features! Already, this plugin has transformed the way I manage tasks, allowing for functionality equal to or exceeding that of existing task managers while enjoying a deep integration with all other aspects of Obsidian knowledge management.

One feature that I still miss a bit though: an activity log. Keeping track of status updates, priority and due date changes (how many times did I postpone that task again?). Or in a more general context, keeping track of history of metadata in addition to current values.

Idea: add an option (either at the plugin level or at the schema level) to have metadata updates through the plugin (edit field at currsor, context menu, dataview, API) also create a log entry either in a central log file, or in the file being updated. Being able to provide a custom format for the log entry with tokens (field name, file name, old and new value, timestamp) would also be really helpful.
(Detecting all metadata updates, such as those made through other plugins or manually, is probably significantly harder and is explicitly not included in this feature request)

If this feature is too specific, functionality like this could also be enabled via a custom hook in the metadata update function. Either a pre-metadata update hook (which might also allow for functionality such as custom transformations of input data, or custom validation schemes that may reject the update entirely), or a post-metadata update callback function (allowing for success/error handling).

**Comment by mdelobelle** [comment]
This is indeed interesting. I'm currently working on a new core component to index fields and their settings for faster calculation. Once this field Index is proven robust enough, I think I could make an option to test the change of a field's value through a metadata menu command and log this change in a file.
The log format part shouldn't be difficult. Do you already have some format in mind?

**Comment by leoccyao** [comment]
Personally, I would prefer updates of the form "(datetime): field (field) in file (file) changed from (initial value) to (final value)", though there's a lot of room for customizability here. Some users may prefer something more human-readable, others something more machine-readable (I could even envision having my log be a JSON array, with querying on that). Some users may also prefer this data to be logged to the file where the change occurred, while others may prefer having a central log file that then gets queried over.
If this is too much customization to implement (and perhaps this is also not the core purpose of this plugin), perhaps there could be an advanced mode where the user could define a custom callback function (that takes the filename, field name, and initial and final values, and does whatever the user wants with the log entry). This could either support a function exported from another plugin (which could work well with the [user plugins plugin](https://github.com/mnowotnik/obsidian-user-plugins)), or the function could be loaded from a JS file. This might be a good first step (and I would be happy with it!), and perhaps some preset parsing functions (log to same file, new file, etc.) could be built on top of it if there is user demand.
