### ISSUE TITLE
Splitting the template value by ":" doesn't work well if the value actually *has* a colon in it.

### ISSUE THREAD

**Issue by nazgul** [mdelobelle/metadatamenu#98]
I tried to set up an option menu of times (e.g. `["09:00", "10:00"]` and it didn't work because the resulting value of optionsString was "[09".

https://github.com/mdelobelle/metadatamenu/blob/2bc765202da8161a50bcca759f5dfba8c8e69079/src/optionModals/fields/InputModal.ts#L38

**Comment by mdelobelle** [comment]
good catch, will be fixed in the next version

**Comment by mdelobelle** [comment]
fixed in 0.2.0
